#!/usr/bin/python

# [Icarus] Batch Render Queue Manager queue__main__.py
# v0.2
#
# Mike Bonnington <mike.bonnington@gps-ldn.com>
# (c) 2016 Gramercy Park Studios
#
# A UI for managing the render queue.


from PySide import QtCore, QtGui
from queue_ui import * # <- import your app's UI file (as generated by pyside-uic)
import datetime, os, socket, sys, time

# Import custom modules
import renderQueue
import sequence as seq
import verbose


class gpsRenderQueueApp(QtGui.QMainWindow):

	def __init__(self, parent = None):
		super(gpsRenderQueueApp, self).__init__()
		self.ui = Ui_MainWindow()
		self.ui.setupUi(self)

		self.localhost = socket.gethostname()
		self.slaveStatus = "idle"
		#verbose.registerStatusBar(self.ui.statusbar)

		# Instantiate render queue class and load data
		self.rq = renderQueue.renderQueue()
		self.rq.loadXML(os.path.join(os.environ['PIPELINE'], 'core', 'config', 'renderQueue.xml'))

		# Connect signals & slots
		self.ui.jobSubmit_toolButton.clicked.connect(self.launchRenderSubmit)
		self.ui.refresh_toolButton.clicked.connect(self.updateRenderQueueView)

		self.ui.jobPause_toolButton.clicked.connect(lambda *args: self.changePriority(0, absolute=True))
		self.ui.jobDelete_toolButton.clicked.connect(self.deleteRenderJob)
		self.ui.jobPriority_slider.sliderMoved.connect(lambda value: self.changePriority(value)) # valueChanged
		self.ui.jobPriority_slider.sliderReleased.connect(self.updatePriority)

		self.ui.taskComplete_toolButton.clicked.connect(self.completeTask)
		self.ui.taskRequeue_toolButton.clicked.connect(self.requeueTask)

		#self.ui.slave_toolButton.clicked.connect(self.launchRenderSlave)
		self.ui.dequeue_toolButton.clicked.connect(self.dequeue)
		#self.ui.close_pushButton.clicked.connect(self.exit)

		self.updateRenderQueueView()
		#self.updateSlaveView()


	def updateRenderQueueView(self):
		""" Populates the render queue tree view widget with entries for render jobs and tasks.
		"""
		self.rq.loadXML(quiet=True) # reload XML data

		self.ui.renderQueue_treeWidget.clear()

		# Populate render jobs
		for jobElement in self.rq.getJobs():
			renderJobItem = QtGui.QTreeWidgetItem(self.ui.renderQueue_treeWidget)

			jobTotalTimeSeconds = 0
			completedTasks = 0

			# Populate render tasks
			taskElements = jobElement.findall('task')
			for taskElement in taskElements:
				renderTaskItem = QtGui.QTreeWidgetItem(renderJobItem)

				renderTaskItem.setText(0, "Task %s" %taskElement.get('id'))
				renderTaskItem.setText(1, taskElement.get('id'))
				renderTaskItem.setText(2, self.rq.getValue(taskElement, 'frames'))
				taskStatus = self.rq.getValue(taskElement, 'status')
				renderTaskItem.setText(3, taskStatus)
				if taskStatus == "Done":
					completedTasks += 1
				try:
					totalTimeSeconds = float(self.rq.getValue(taskElement, 'totalTime')) # use float and round for millisecs
					jobTotalTimeSeconds += totalTimeSeconds
					totalTime = str(datetime.timedelta(seconds=int(totalTimeSeconds)))
				except (TypeError, ValueError):
					totalTime = None
				renderTaskItem.setText(7, totalTime)
				renderTaskItem.setText(8, self.rq.getValue(taskElement, 'slave'))
				renderTaskItem.setText(9, self.rq.getValue(taskElement, 'command'))

			renderJobItem.setText(0, self.rq.getValue(jobElement, 'name'))
			renderJobItem.setText(1, jobElement.get('id'))
			percentComplete = (float(completedTasks) / float(len(taskElements))) * 100

			if percentComplete == 0:
				jobStatus = "Queued"
			elif percentComplete == 100:
				jobStatus = "Done"
			else:
				jobStatus = "In Progress (%d%%)" %percentComplete
				renderJobItem.setExpanded(True)
			self.rq.setStatus(jobElement.get('id'), jobStatus) # write to xml
			renderJobItem.setText(3, jobStatus)

			# if percentComplete > 0:
			# 	if percentComplete >= 100:
			# 		jobStatus = "Done"
			# 	else:
			# 		jobStatus = "In Progress (%d%%)" %percentComplete
			# 	self.rq.setStatus(jobElement.get('id'), jobStatus) # write to xml
			# 	renderJobItem.setText(3, jobStatus)
			# else:
			# 	renderJobItem.setText(3, self.rq.getValue(jobElement, 'status'))

			renderJobItem.setText(2, self.rq.getValue(jobElement, 'frames'))
			renderJobItem.setText(4, self.rq.getValue(jobElement, 'priority'))
			renderJobItem.setText(5, self.rq.getValue(jobElement, 'user'))
			renderJobItem.setText(6, self.rq.getValue(jobElement, 'submitTime'))
			try:
				jobTotalTime = str(datetime.timedelta(seconds=int(jobTotalTimeSeconds)))
			except (TypeError, ValueError):
				jobTotalTime = None
			renderJobItem.setText(7, str(jobTotalTime))

			# Retain selection

			# Expand tree item(s)
			#if self.rq.getValue(jobElement, 'status') == "In Progress":
			#	renderJobItem.setExpanded(True)

			# Resize columns
			for i in range(0, self.ui.renderQueue_treeWidget.columnCount()):
				self.ui.renderQueue_treeWidget.resizeColumnToContents(i)

			# Hide ID column
			#self.ui.renderQueue_treeWidget.setColumnHidden(1, True)

			# Sort by submit time column
			self.ui.renderQueue_treeWidget.sortByColumn(6, QtCore.Qt.DescendingOrder)

		self.updateSlaveView()


	def deleteRenderJob(self):
		""" Removes selected render job from the database and updates the view.
		"""
		jobIDs = []

		try:
			for item in self.ui.renderQueue_treeWidget.selectedItems():
				if not item.parent(): # if item has no parent then it must be a top level item, and therefore also a job
					jobIDs.append( int(item.text(1)) )

			for jobID in jobIDs:
				print "Deleting job: ID %d" %jobID
				self.rq.deleteJob(jobID)

			self.updateRenderQueueView()

		except ValueError:
			pass


	def completeTask(self):
		""" Mark the selected task as completed.
		"""
		jobTaskIDs = [] # this will hold a tuble containing (job id, task id)

		try:
			for item in self.ui.renderQueue_treeWidget.selectedItems():
				if item.parent(): # if item has parent then it must be a subitem, and therefore also a task
					jobTaskID = int(item.parent().text(1)), int(item.text(1))
					jobTaskIDs.append(jobTaskID)

			for jobTaskID in jobTaskIDs:
				print "Completing task: Job ID %d, Task ID %d" %jobTaskID
				self.rq.completeTask(jobTaskID[0], jobTaskID[1], 0)

			self.updateRenderQueueView()

		except ValueError:
			pass


	def requeueTask(self):
		""" Requeue the selected task.
		"""
		jobTaskIDs = [] # this will hold a tuble containing (job id, task id)

		try:
			for item in self.ui.renderQueue_treeWidget.selectedItems():
				if item.parent(): # if item has parent then it must be a subitem, and therefore also a task
					jobTaskID = int(item.parent().text(1)), int(item.text(1))
					jobTaskIDs.append(jobTaskID)

			for jobTaskID in jobTaskIDs:
				print "Requeuing task: Job ID %d, Task ID %d" %jobTaskID
				self.rq.requeueTask(jobTaskID[0], jobTaskID[1])

			self.updateRenderQueueView()

		except ValueError:
			pass


	def changePriority(self, amount, absolute=False):
		""" Changes priority of the selected render.
		"""
		try:
			for item in self.ui.renderQueue_treeWidget.selectedItems():
				if not item.parent(): # if item has no parent then it must be a top level item, and therefore also a job
					index = int(item.text(1))
					minPriority = 0
					maxPriority = 100

					if absolute:
						newPriority = amount
					else:
						currentPriority = self.rq.getPriority(index)
						newPriority = currentPriority+amount

					if newPriority <= minPriority:
						item.setText(4, str(minPriority))
					elif newPriority >= maxPriority:
						item.setText(4, str(maxPriority))
					else:
						item.setText(4, str(newPriority))

					if absolute:
						self.updatePriority()

		except ValueError:
			pass


	def updatePriority(self):
		""" Store the changed priority value(s).
		"""
		try:
			for item in self.ui.renderQueue_treeWidget.selectedItems():
				if not item.parent(): # if item has no parent then it must be a top level item, and therefore also a job
					index = int(item.text(1))
					priority = int(item.text(4))
					self.rq.setPriority(index, priority)

			self.updateRenderQueueView()

		except ValueError:
			pass

		self.ui.jobPriority_slider.setValue(0) # reset priority slider to zero when released


	def launchRenderSubmit(self):
		""" Launches GPS Submit Render dialog.
		"""
		import submit__main__
		reload(submit__main__)


	# def launchRenderSlave(self):
	# 	""" Launches GPS Render Slave dialog.
	# 	"""
	# 	import slave__main__
	# 	reload(slave__main__)


	def updateSlaveView(self):
		""" Update the information in the slave info area.
		"""
		self.ui.slaveStatus_label.setText("%s (%s)" %(self.localhost, self.slaveStatus))


	def dequeue(self):
		""" Dequeue a render task from the queue and start rendering.
			THIS IS ALL A BIT ROPEY ATM
		"""
		import signal, subprocess

		timeFormatStr = "%Y/%m/%d %H:%M:%S" # "%a, %d %b %Y %H:%M:%S"
		startTimeSec = time.time() # used for measuring the time spent rendering
		startTime = time.strftime(timeFormatStr)

		#self.rq.loadXML(quiet=True) # reload XML data - this is being done by the dequeuing function

		# Look for a suitable job to render
		jobElement = self.rq.dequeueJob()
		if jobElement is None:
			print "No jobs to render."
			return False
		jobID = jobElement.get('id')

		# Look for tasks to start rendering
		taskID, frames = self.rq.dequeueTask(jobID, self.localhost)
		if not taskID:
			print "Job ID %s: no tasks to render." %jobID
			return False

		print "Job ID %s, Task ID %s: Rendering..." %(jobID, taskID)
		frameList = seq.numList(frames)
		startFrame = min(frameList)
		endFrame = max(frameList)

		# Fill info fields
		self.ui.taskInfo_label.setText("Rendering %s %s from '%s'" %(verbose.pluralise("frame", frameList), frames, self.rq.getValue(jobElement, 'name')))
		self.ui.runningTime_label.setText(self.rq.getValue(jobElement, 'submitTime')) # change this to display the task running time

		# try:
		# 	renderCmd = '"%s"' %os.environ['MAYARENDERVERSION'] # store this in XML as maya version may vary with project
		# except KeyError:
		# 	print "ERROR: Path to Maya Render command executable not found. This can be set with the environment variable 'MAYARENDERVERSION'."
		#renderCmd = '"%s"' %os.path.normpath(self.rq.getValue(jobElement, 'mayaRenderCmd'))
		renderCmd = self.rq.getValue(jobElement, 'mayaRenderCmd')
		# if not os.path.isfile(renderCmd): # disabled this check 
		# 	print "ERROR: Maya render command not found: %s" %renderCmd
		# 	return False

		sceneName = self.rq.getValue(jobElement, 'mayaScene')
		if not os.path.isfile(sceneName):
			print "ERROR: Scene not found: %s" %sceneName
			self.rq.requeueTask(jobID, taskID)
			#self.rq.setStatus(jobID, "Failed")
			return False

		cmdStr = ''
		args = '-proj "%s"' %self.rq.getValue(jobElement, 'mayaProject')
		frameRangeArgs = ''

		mayaFlags = self.rq.getValue(jobElement, 'mayaFlags')
		if mayaFlags is not None:
			args += ' %s' %self.rq.getValue(jobElement, 'mayaFlags')

		# Construct command(s)
		if True: # replace with check if the job jas any tasks
			frameRangeArgs = '-s %d -e %d' %(int(startFrame), int(endFrame))

			cmdStr += '"%s" %s %s "%s"' %(renderCmd, args, frameRangeArgs, sceneName)

		else:
			cmdStr = '"%s" %s "%s"' %(renderCmd, args, sceneName)

		self.slaveStatus = "rendering"
		self.ui.dequeue_toolButton.setEnabled(False)
		self.ui.slaveStatus_label.setText("%s (%s)" %(self.localhost, self.slaveStatus))

		self.ui.command_lineEdit.setText(cmdStr)
		# print "waiting 3 sec"
		time.sleep(1) # wait a second
		if os.environ['ICARUS_RUNNING_OS'] == 'Windows':
			verbose.print_(cmdStr, 4)
			#self.renderProcess = subprocess.Popen(cmdStr, shell=True) #, stdout=subprocess.PIPE, shell=True)
			output = subprocess.Popen(cmdStr, stdout=subprocess.PIPE).communicate()[0] # find a way to do this without locking the UI
			self.ui.output_textEdit.setPlainText(output)
			#os.system(cmdStr) #, stdout=subprocess.PIPE, shell=True)
		else:
			#print cmdStr
			self.ui.output_textEdit.setPlainText(cmdStr)
			#self.renderProcess = subprocess.Popen(cmdStr, stdout=subprocess.PIPE, shell=True, preexec_fn=os.setsid)

		# Disable UI to prevent new renders being submitted
		#self.tglUI(False)

		totalTimeSec = time.time() - startTimeSec # calculate time spent rendering task

		self.slaveStatus = "idle"
		self.ui.dequeue_toolButton.setEnabled(True)
		self.ui.taskInfo_label.setText("")
		self.ui.runningTime_label.setText("")
		#self.rq.setStatus(jobID, "In Progress (0%)")
		self.rq.completeTask(jobID, taskID, totalTimeSec)
		self.updateRenderQueueView()


	def exit(self):
		""" Exit the dialog.
		"""
		self.hide()


if __name__ == "__main__":
	app = QtGui.QApplication(sys.argv)

	# Initialise Icarus environment
	#os.environ['ICWORKINGDIR'] = "N:\Dev\icarus\core\ui" # temp assignment
	sys.path.append(os.environ['ICWORKINGDIR'])
	import env__init__
	env__init__.setEnv()

	import rsc_rc # TODO: Check why this isn't working from within the UI file

	# app.setStyle('fusion') # Set UI style - you can also use a flag e.g. '-style plastique'

	# Apply UI style sheet
	qss=os.path.join(os.environ['ICWORKINGDIR'], "style.qss")
	with open(qss, "r") as fh:
		app.setStyleSheet(fh.read())

	renderQueueApp = gpsRenderQueueApp()
	renderQueueApp.show()
	sys.exit(app.exec_())

else:
	renderQueueApp = gpsRenderQueueApp()
	print renderQueueApp
	renderQueueApp.show()

