#!/usr/bin/python

# [Icarus] render_submit.py
#
# Mike Bonnington <mike.bonnington@gps-ldn.com>
# (c) 2015-2017 Gramercy Park Studios
#
# Batch Render Submitter
# A UI for creating render jobs to send to a render queue manager.


import os
import subprocess
import sys
import time

from Qt import QtCompat, QtCore, QtGui, QtWidgets
import rsc_rc  # Import resource file as generated by pyside-rcc

# Import custom modules
import osOps
import renderQueue
import sequence
import userPrefs
import verbose


# ----------------------------------------------------------------------------
# Configuration
# ----------------------------------------------------------------------------

# Set window title and object names
WINDOW_TITLE = "Render Submit"
WINDOW_OBJECT = "renderSubmitUI"

# Set the UI and the stylesheet
UI_FILE = "render_submit_ui.ui"
STYLESHEET = "style.qss"  # Set to None to use the parent app's stylesheet

CREATE_NO_WINDOW = 0x08000000


# ----------------------------------------------------------------------------
# Main dialog class
# ----------------------------------------------------------------------------

class RenderSubmitUI(QtWidgets.QMainWindow):
	""" Main dialog class.
	"""
	def __init__(self, parent=None):
		super(RenderSubmitUI, self).__init__(parent)

		# Set object name and window title
		self.setObjectName(WINDOW_OBJECT)
		self.setWindowTitle(WINDOW_TITLE)

		# Load UI & stylesheet
		self.ui = QtCompat.load_ui(fname=os.path.join(os.environ['IC_FORMSDIR'], UI_FILE))
		if STYLESHEET is not None:
			qss=os.path.join(os.environ['IC_FORMSDIR'], STYLESHEET)
			with open(qss, "r") as fh:
				self.ui.setStyleSheet(fh.read())

		# Set the main widget
		self.setCentralWidget(self.ui)

		# Set window flags
		self.setWindowFlags(QtCore.Qt.Tool)
		# self.setWindowFlags(QtCore.Qt.Dialog)
		# self.ui.setWindowFlags(QtCore.Qt.CustomizeWindowHint | 
		# 	                   QtCore.Qt.WindowTitleHint)

		# Connect signals & slots
		self.ui.submitTo_comboBox.currentIndexChanged.connect(self.setQueueManagerFromComboBox)
		self.ui.type_comboBox.currentIndexChanged.connect(self.setJobTypeFromComboBox)
		self.ui.sceneBrowse_toolButton.clicked.connect(self.sceneBrowse)

		self.ui.pool_comboBox.currentIndexChanged.connect(self.storeComboBoxValue)
		self.ui.group_comboBox.currentIndexChanged.connect(self.storeComboBoxValue)
		self.ui.pool_comboBox.editTextChanged.connect(self.storeComboBoxValue)
		self.ui.group_comboBox.editTextChanged.connect(self.storeComboBoxValue)
		self.ui.getPools_toolButton.clicked.connect(self.getDeadlinePools)
		self.ui.getGroups_toolButton.clicked.connect(self.getDeadlineGroups)
		self.ui.priority_spinBox.valueChanged.connect(self.storeSpinBoxValue)
		self.ui.comment_lineEdit.textEdited.connect(self.storeLineEditValue)

		self.ui.frameRange_lineEdit.editingFinished.connect(self.calcFrameList)  # was textEdited
		self.ui.taskSize_spinBox.valueChanged.connect(self.calcFrameList)

		self.ui.submit_pushButton.clicked.connect(self.submit)
		self.ui.close_pushButton.clicked.connect(self.exit)

		# Context menus
		self.ui.frameListOptions_toolButton.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)

		self.actionFrameListOption1 = QtWidgets.QAction("Shot default", None)
		self.actionFrameListOption1.triggered.connect(self.setFrameListPreset)
		self.ui.frameListOptions_toolButton.addAction(self.actionFrameListOption1)

		self.actionFrameListOption2 = QtWidgets.QAction("Timeline", None)
		self.actionFrameListOption2.triggered.connect(self.setFrameListPreset)
		self.ui.frameListOptions_toolButton.addAction(self.actionFrameListOption2)

		self.actionFrameListOption3 = QtWidgets.QAction("First, last, sequential", None)
		self.actionFrameListOption3.triggered.connect(self.setFrameListPreset)
		self.ui.frameListOptions_toolButton.addAction(self.actionFrameListOption3)

		self.ui.frameListOptions_toolButton.setEnabled(False)  # TEMP DISABLE

		# Set input validators
		frame_list_validator = QtGui.QRegExpValidator(QtCore.QRegExp(r'[\d\-, ]+'), self.ui.frameRange_lineEdit)
		self.ui.frameRange_lineEdit.setValidator(frame_list_validator)

		# Instantiate render queue class and load data
		self.rq = renderQueue.renderQueue()
		self.rq.loadXML(os.path.join(os.environ['IC_CONFIGDIR'], 'renderQueue.xml'))


	def display(self, frameRange=None, flags=None):
		""" Display the dialog.
		"""
		self.returnValue = False

		# Read user prefs config file - if it doesn't exist it will be created
		userPrefs.read()

		# Restore widgets from user prefs settings
		self.submitTo = userPrefs.query('rendersubmit', 'submitto', default=self.ui.submitTo_comboBox.currentText())
		self.ui.submitTo_comboBox.setCurrentIndex(self.ui.submitTo_comboBox.findText(self.submitTo))

		pool = userPrefs.query('rendersubmit', 'pool', datatype='str', default='')
		self.ui.pool_comboBox.addItem(pool)

		group = userPrefs.query('rendersubmit', 'group', datatype='str', default='')
		self.ui.group_comboBox.addItem(group)

		priority = userPrefs.query('rendersubmit', 'priority', datatype='int', default='')
		self.ui.priority_spinBox.setValue(priority)

		comment = userPrefs.query('rendersubmit', 'comment', datatype='str', default='')
		self.ui.comment_lineEdit.setText(comment)

		# Set job type from Icarus environment when possible
		if os.environ['IC_ENV'] == 'STANDALONE':
			self.jobType = userPrefs.query('rendersubmit', 'lastrenderjobtype', default=self.ui.type_comboBox.currentText())
			self.ui.type_comboBox.setCurrentIndex(self.ui.type_comboBox.findText(self.jobType))
			self.setJobType()
			self.setSceneList()

		elif os.environ['IC_ENV'] == 'MAYA':
			self.jobType = 'Maya'
			self.ui.type_comboBox.setCurrentIndex(self.ui.type_comboBox.findText(self.jobType))
			self.setJobType()

			import maya.cmds as mc
			sceneName = mc.file(query=True, sceneName=True)
			if sceneName:  # Check we're not working in an unsaved scene
				relPath = self.relativePath(osOps.absolutePath(sceneName))
				if relPath:
					self.ui.scene_comboBox.addItem(relPath)
			else:
				msg = "Scene must be saved before submitting render."
				mc.warning(msg)
				#mc.confirmDialog(title="Scene not saved", message=msg, icon="warning", button="Close")
				self.ui.scene_comboBox.addItem(msg)
				self.ui.submit_pushButton.setToolTip(msg)
				self.ui.submit_pushButton.setEnabled(False)

			self.getRenderers()

			self.ui.render_groupBox.setEnabled(False)
			self.ui.sceneBrowse_toolButton.hide()

		elif os.environ['IC_ENV'] == 'NUKE':
			self.jobType = 'Nuke'
			self.ui.type_comboBox.setCurrentIndex(self.ui.type_comboBox.findText(self.jobType))
			self.setJobType()

			import nuke
			scriptName = nuke.value("root.name")
			if scriptName:  # Check we're not working in an unsaved script
				relPath = self.relativePath(osOps.absolutePath(scriptName))
				if relPath:
					self.ui.scene_comboBox.addItem(relPath)
			else:
				msg = "Script must be saved before submitting render."
				nuke.warning(msg)
				#nuke.message(msg)
				self.ui.scene_comboBox.addItem(msg)
				self.ui.submit_pushButton.setToolTip(msg)
				self.ui.submit_pushButton.setEnabled(False)

			self.ui.render_groupBox.setEnabled(False)
			self.ui.sceneBrowse_toolButton.hide()

		self.numList = []
		if frameRange:
			self.ui.frameRange_lineEdit.setText(frameRange)
		else:
			self.getFrameList()
		self.calcFrameList()

		if flags:
			self.ui.flags_groupBox.setChecked(True)
			self.ui.flags_lineEdit.setText(flags)

		# self.ui.show()
		# self.ui.raise_()
		self.show()
		self.raise_()
		return self.returnValue


	def setQueueManagerFromComboBox(self):
		""" Set queue manager to submit job to - called when the job type
			combo box value is changed.
		"""
		self.submitTo = self.ui.submitTo_comboBox.currentText()
		userPrefs.edit('rendersubmit', 'submitto', self.submitTo)
		self.ui.submit_pushButton.setText("Submit to %s" %self.submitTo)


	def setJobTypeFromComboBox(self):
		""" Set job type - called when the job type combo box value is
			changed.
		"""
		self.jobType = self.ui.type_comboBox.currentText()
		userPrefs.edit('rendersubmit', 'lastrenderjobtype', self.jobType)
		self.setJobType()
		self.setSceneList()


	def setJobType(self):
		""" Setup some global variables and UI elements depending on the job
			type.
		"""
		if self.jobType == 'Maya':
			try:
				self.relativeScenesDir = osOps.absolutePath( '%s/%s' %(os.environ['MAYADIR'], 'scenes') )
			except KeyError:
				self.relativeScenesDir = ""
			self.ui.scene_label.setText("Scene:")
			self.ui.renderer_label.show()
			self.ui.renderer_comboBox.show()
		elif self.jobType == 'Nuke':
			try:
				self.relativeScenesDir = osOps.absolutePath( '%s/%s' %(os.environ['NUKEDIR'], 'scripts') )
			except KeyError:
				self.relativeScenesDir = ""
			self.ui.scene_label.setText("Script:")
			self.ui.renderer_label.hide()
			self.ui.renderer_comboBox.hide()

		self.relativeScenesToken = '...'  # Representative string to replace the path specified above


	def setSceneList(self):
		""" Clear scene menu and populate from recent file list. Only used in
			standalone mode.
		"""
		self.ui.scene_comboBox.clear()

		try:
			import recentFiles
			for filePath in recentFiles.getLs(self.jobType):
				fullPath = osOps.absolutePath( os.environ['SHOTPATH'] + filePath )
				relPath = self.relativePath(fullPath)
				if relPath:
					self.ui.scene_comboBox.addItem(relPath)
		except:
			pass


	def relativePath(self, absPath):
		""" Convert an absolute path to a relative path.
		"""
		if absPath.startswith(self.relativeScenesDir):
			return absPath.replace(self.relativeScenesDir, self.relativeScenesToken)
		else:
			return False


	def absolutePath(self, relPath):
		""" Convert a relative path to an absolute path.
		"""
		return relPath.replace(self.relativeScenesToken, self.relativeScenesDir)


	def sceneBrowse(self):
		""" Browse for a scene/script file.
		"""
		if self.jobType == 'Maya':
			fileDir = os.environ.get('MAYASCENESDIR', '.')  # Go to current dir if env var is not set
			fileFilter = 'Maya files (*.ma *.mb)'
			fileTerminology = 'scenes'
		elif self.jobType == 'Nuke':
			fileDir = os.environ.get('NUKESCRIPTSDIR', '.')  # Go to current dir if env var is not set
			fileFilter = 'Nuke files (*.nk)'
			fileTerminology = 'scripts'

		currentDir = os.path.dirname(self.absolutePath(self.ui.scene_comboBox.currentText()))
		if os.path.exists(currentDir):
			startingDir = currentDir
		else:
			startingDir = fileDir

		filePath = QtWidgets.QFileDialog.getOpenFileName(self, self.tr('Files'), startingDir, fileFilter)
		if filePath[0]:
			newEntry = self.relativePath( osOps.absolutePath(filePath[0]) )
			#newEntry = osOps.absolutePath(filePath[0])
			if newEntry:
				self.ui.scene_comboBox.removeItem(self.ui.scene_comboBox.findText(newEntry))  # If the entry already exists in the list, delete it
				self.ui.scene_comboBox.insertItem(0, newEntry)
				self.ui.scene_comboBox.setCurrentIndex(0)  # Always insert the new entry at the top of the list and select it
			else:
				verbose.print_("Warning: Only %s belonging to the current shot can be submitted." %fileTerminology, 2)


	# def storeOptions(self):
	# 	""" Store persistent settings in user prefs.
	# 	"""
	# 	self.storeValue('pool', self.ui.pool_comboBox.currentText())
	# 	self.storeValue('group', self.ui.group_comboBox.currentText())


	# @QtCore.Slot()
	def storeSpinBoxValue(self):
		""" Get the value from a Spin Box and store in XML data.
		"""
		attr = self.sender().property('xmlTag')
		value = self.sender().value()
		self.storeValue(attr, value)


	# @QtCore.Slot()
	def storeLineEditValue(self):
		""" Get the value from a Line Edit and store in XML data.
		"""
		attr = self.sender().property('xmlTag')
		value = self.sender().text()
		self.storeValue(attr, value)


	# @QtCore.Slot()
	def storeComboBoxValue(self):
		""" Get the value from a Combo Box and store in XML data.
		"""
		attr = self.sender().property('xmlTag')
		value = self.sender().currentText()
		self.storeValue(attr, value)


	def storeValue(self, attr, value=""):
		""" Store value in XML data.
		"""
		verbose.print_("%20s %s.%s=%s" %(type(value), 'rendersubmit', attr, value), 4)
		userPrefs.edit('rendersubmit', attr, value)


	def getFrameList(self):
		""" Get frame range from shot settings.
		"""
		try:
			self.ui.frameRange_lineEdit.setText("%d-%d" %(int(os.environ['STARTFRAME']), int(os.environ['ENDFRAME'])))
			self.ui.overrideFrameRange_groupBox.setChecked(True)
		except KeyError:
			self.ui.frameRange_lineEdit.setText("")
			self.ui.overrideFrameRange_groupBox.setChecked(False)


	def getDeadlinePools(self):
		""" Get Deadline pools & populate combo box.
		"""
		pools = subprocess.check_output([os.environ['DEADLINECMDVERSION'], '-pools'], creationflags=CREATE_NO_WINDOW)
		self.populateComboBox(self.ui.pool_comboBox, self.strToList(pools))


	def getDeadlineGroups(self):
		""" Get Deadline groups & populate combo box.
		"""
		groups = subprocess.check_output([os.environ['DEADLINECMDVERSION'], '-groups'], creationflags=CREATE_NO_WINDOW)
		self.populateComboBox(self.ui.group_comboBox, self.strToList(groups))


	def getRenderers(self):
		""" Get Maya renderers & populate combo box.
		"""
		renderers = self.getRenderer()
		rendererLs = [renderers]
		# verbose.print_(rendererLs)
		self.populateComboBox(self.ui.renderer_comboBox, rendererLs)


	def strToList(self, string):
		""" Convert string to list by splitting into lines.
			Encode bytes to string for Python 3.
		"""
		string = string.decode()
		ls = string.splitlines()
		verbose.print_(ls)
		return ls


	def populateComboBox(self, comboBox, contentsLs):
		""" Populate combo box.
		"""
		# Store current value
		current = comboBox.currentText()

		# Clear menu
		comboBox.clear()

		# Populate menu
		for item in contentsLs:
			if item:
				comboBox.addItem(item)

		# Set to current value
		index = comboBox.findText(current)
		if index == -1:
			comboBox.setCurrentIndex(0)
		else:
			comboBox.setCurrentIndex(index)


	def setFrameListPreset(self):
		""" Set frame list from preset
		"""
		pass


	def calcFrameList(self, quiet=True):
		""" Calculate list of frames to be rendered.
		"""
		self.numList = sequence.numList(self.ui.frameRange_lineEdit.text(), quiet=True)
		taskSize = self.ui.taskSize_spinBox.value()
		if self.numList == False:
			if not quiet:
				verbose.print_("Warning: Invalid entry for frame range.", 2)
			return False
		else:
			self.ui.frameRange_lineEdit.setText(sequence.numRange(self.numList))
			nFrames = len(self.numList)
			if taskSize < nFrames:
				self.ui.taskSize_slider.setMaximum(nFrames)
				self.ui.taskSize_spinBox.setMaximum(nFrames)
				self.ui.taskSize_spinBox.setValue(taskSize)
			else:
				self.ui.taskSize_slider.setMaximum(nFrames)
				self.ui.taskSize_spinBox.setMaximum(nFrames)
				self.ui.taskSize_spinBox.setValue(nFrames)

			# Generate task list for rendering
			self.taskList = []
			sequences = list(sequence.seqRange(self.numList, gen_range=True))
			for seq in sequences:
				chunks = list(sequence.chunks(seq, taskSize))
				for chunk in chunks:
					#self.taskList.append(list(sequence.seqRange(chunk))[0])
					self.taskList.append(sequence.numRange(chunk))

		return True
					

	def getMayaProject(self, scene):
		""" Get the Maya Project. If the environmnet variable is not set, try
			to guess the Maya project directory based on the scene name.
		"""
		try:  # Project is implicit if job is set
			mayaProject = os.environ['MAYADIR'].replace("\\", "/")
		except KeyError:
			mayaProject = scene.split('/scenes')[0]

		return mayaProject


	def getRenderer(self):
		""" Get the current Maya renderer
		"""
		try:
			renderer = mc.getAttr("defaultRenderGlobals.currentRenderer")
		except KeyError:
			renderer = ""

		return renderer


	def submit(self):
		""" Submit job.
		"""
		if self.submitTo == "RenderQueue":
			self.submitToRenderQueue()
		if self.submitTo == "Deadline":
			self.submitToDeadline()


	def submitToRenderQueue(self):
		""" Submit job to render queue.
		"""
		timeFormatStr = "%Y/%m/%d %H:%M:%S" # "%a, %d %b %Y %H:%M:%S"

		if not self.calcFrameList(quiet=False):
			return

		###################
		# Generic options #
		###################

		if self.ui.overrideFrameRange_groupBox.isChecked():
			frames = self.ui.frameRange_lineEdit.text()
			taskSize = self.ui.taskSize_spinBox.value()
			framesMsg = '%d %s to be rendered; %d %s to be submitted.\n' %(len(self.numList), verbose.pluralise("frame", len(self.numList)), len(self.taskList), verbose.pluralise("task", len(self.taskList)))
		else:
			frames = 'Unknown'
			taskSize = 'Unknown'
			self.numList = []
			self.taskList = [frames, ]
			framesMsg = 'The frame range was not specified so the job cannot be distributed into tasks. The job will be submitted as a single task and the frame range will be read from the scene at render time.\n'

		if self.ui.flags_groupBox.isChecked():
			flags = self.ui.flags_lineEdit.text()
		else:
			flags = ""

		priority = self.ui.priority_spinBox.value()
		comment = self.ui.comment_lineEdit.text()

		#############################
		# Renderer-specific options #
		#############################

		if self.jobType == 'Maya':
			renderCmdEnvVar = 'MAYARENDERVERSION'
			mayaScene = self.absolutePath(self.ui.scene_comboBox.currentText()).replace("\\", "/")  # Implicit if submitting from Maya UI
			mayaProject = self.getMayaProject(mayaScene)
			jobName = os.path.splitext(os.path.basename(mayaScene))[0]
		elif self.jobType == 'Nuke':
			renderCmdEnvVar = 'NUKEVERSION'
			nukeScript = self.absolutePath(self.ui.scene_comboBox.currentText()).replace("\\", "/")  # Implicit if submitting from Nuke UI
			jobName = os.path.splitext(os.path.basename(nukeScript))[0]

		try:
			renderCmd = os.environ[renderCmdEnvVar].replace("\\", "/")
		except KeyError:
			verbose.print_("ERROR: Path to %s render command executable not found. This can be set with the environment variable '%s'." %(self.jobType, renderCmdEnvVar), 2)

		# Package option variables into tuples
		genericOpts = jobName, self.jobType, frames, taskSize, priority
		if self.jobType == 'Maya':
			renderOpts = mayaScene, mayaProject, flags, renderCmd
		elif self.jobType == 'Nuke':
			renderOpts = nukeScript, flags, renderCmd

		# Confirmation dialog
		import pDialog

		dialogTitle = 'Submit Render - %s' %jobName
		dialogMsg = ''
		dialogMsg += 'Name:\t%s\nType:\t%s\nFrames:\t%s\nTask size:\t%s\nPriority:\t%s\n\n' %genericOpts
		# if self.jobType == 'Maya':
		# 	dialogMsg += 'Scene:\t%s\nProject:\t%s\nFlags:\t%s\nCommand:\t%s\n\n' %renderOpts
		# elif self.jobType == 'Nuke':
		# 	dialogMsg += 'Script:\t%s\nFlags:\t%s\nCommand:\t%s\n\n' %renderOpts
		dialogMsg += framesMsg
		dialogMsg += 'Do you want to continue?'

		dialog = pDialog.dialog()
		if dialog.display(dialogMsg, dialogTitle):
			self.rq.newJob(genericOpts, renderOpts, self.taskList, os.environ['IC_USERNAME'], time.strftime(timeFormatStr), comment)

			# Post-confirmation dialog
			dialogTitle = 'Submitted Render - %s' %jobName
			dialogMsg = ''
			dialogMsg += 'Name:\t%s\nType:\t%s\nFrames:\t%s\nTask size:\t%s\nPriority:\t%s\n\n' %genericOpts
			dialogMsg += 'Render job submitted succesfully.'
			dialog.display(dialogMsg, dialogTitle, conf=True)
		else:
			return


	def submitToDeadline(self):
		""" Submit job to Deadline.
		"""
		# timeFormatStr = "%Y/%m/%d %H:%M:%S" # "%a, %d %b %Y %H:%M:%S"
		pluginInfoFile = ""

		if not self.calcFrameList(quiet=False):
			return

		###################
		# Generic options #
		###################

		frames = self.ui.frameRange_lineEdit.text()
		taskSize = self.ui.taskSize_spinBox.value()
		framesMsg = '%d %s to be rendered; %d %s to be submitted.\n' %(len(self.numList), verbose.pluralise("frame", len(self.numList)), len(self.taskList), verbose.pluralise("task", len(self.taskList)))

		pool = self.ui.pool_comboBox.currentText()
		group = self.ui.group_comboBox.currentText()
		priority = self.ui.priority_spinBox.value()
		comment = self.ui.comment_lineEdit.text()

		#############################
		# Renderer-specific options #
		#############################

		if self.jobType == 'Maya':
			plugin = 'MayaBatch'
			version = os.environ['MAYA_VER']  #jobData.getAppVersion('Maya')
			renderer = self.ui.renderer_comboBox.currentText()
			scene = self.absolutePath(self.ui.scene_comboBox.currentText()).replace("\\", "/")
			mayaProject = self.getMayaProject(scene)
			jobName = os.path.splitext(os.path.basename(scene))[0]
		elif self.jobType == 'Nuke':
			plugin = 'Nuke'
			scene = self.absolutePath(self.ui.scene_comboBox.currentText()).replace("\\", "/")
			jobName = os.path.splitext(os.path.basename(scene))[0]

		# Package option variables into tuples
		genericOpts = jobName, self.jobType, frames, taskSize, priority
		# if self.jobType == 'Maya':
		# 	renderOpts = scene, mayaProject, flags, renderCmd
		# elif self.jobType == 'Nuke':
		# 	renderOpts = scene, flags, renderCmd

		# Confirmation dialog
		import pDialog

		dialogTitle = 'Submit Render to Deadline - %s' %jobName
		dialogMsg = ''
		dialogMsg += 'Name:\t%s\nType:\t%s\nFrames:\t%s\nTask size:\t%s\nPriority:\t%s\n\n' %genericOpts
		# if self.jobType == 'Maya':
		# 	dialogMsg += 'Scene:\t%s\nProject:\t%s\nFlags:\t%s\nCommand:\t%s\n\n' %renderOpts
		# elif self.jobType == 'Nuke':
		# 	dialogMsg += 'Script:\t%s\nFlags:\t%s\nCommand:\t%s\n\n' %renderOpts
		dialogMsg += framesMsg
		dialogMsg += 'Do you want to continue?'

		dialog = pDialog.dialog()
		if dialog.display(dialogMsg, dialogTitle):

			# Generate submission info files
			jobInfoFile = os.path.splitext(scene)[0] + "_deadlineJobInfo.txt"
			fh = open(jobInfoFile, 'w')
			fh.write("Plugin=%s\n" %plugin)
			fh.write("Name=%s\n" %jobName)
			fh.write("Comment=%s\n" %comment)
			fh.write("Frames=%s\n" %frames)
			fh.write("ChunkSize=%s\n" %taskSize)
			fh.write("Pool=%s\n" %pool)
			fh.write("Group=%s\n" %group)
			fh.write("Priority=%s\n" %priority)
			if priority == 0:
				fh.write("InitialStatus=Suspended\n")
			# fh.write("OutputDirectory0=%s\n" %mayaOps.getRenderImagePath())
			# fh.write("OutputFilename0=%s\n" %mayaOps.getRenderImageName())
			fh.close()

			pluginInfoFile = os.path.splitext(scene)[0] + "_deadlinePluginInfo.txt"
			fh = open(pluginInfoFile, 'w')
			fh.write("Version=%s\n" %version)
			fh.write("Build=64bit\n")
			fh.write("Renderer=%s\n" %renderer)
			fh.write("StrictErrorChecking=1\n")
			fh.write("ProjectPath=%s\n" %mayaProject)
			# fh.write("OutputFilePath=%s\n" %mayaOps.getOutputFilePath())
			# fh.write("OutputFilePrefix=%s\n" %mayaOps.getOutputFilePrefix())
			fh.write("SceneFile=%s\n" %scene)
			fh.close()

			# Execute deadlinecommand
			output = subprocess.check_output([os.environ['DEADLINECMDVERSION'], jobInfoFile, pluginInfoFile], creationflags=CREATE_NO_WINDOW)

			# Delete submission info files
			osOps.recurseRemove(jobInfoFile)
			osOps.recurseRemove(pluginInfoFile)

			# Post-confirmation dialog
			dialogTitle = 'Submitted Render to Deadline - %s' %jobName
			dialogMsg = ''
			dialogMsg += 'Name:\t%s\nType:\t%s\nFrames:\t%s\nTask size:\t%s\nPriority:\t%s\n\n' %genericOpts
			dialogMsg += output
			dialog.display(dialogMsg, dialogTitle, conf=True)
		else:
			return


	def showEvent(self, event):
		""" Event handler for when window is shown.
		"""
		self.setJobTypeFromComboBox()
		self.getFrameList()
		# self.display()


	def exit(self):
		""" Exit the dialog.
		"""
		# self.ui.hide()
		self.hide()

# ----------------------------------------------------------------------------
# End of main dialog class
# ----------------------------------------------------------------------------


# def run_(**kwargs):
# 	# for key, value in kwargs.iteritems():
# 	# 	print "%s = %s" % (key, value)
# 	renderSubmitUI = RenderSubmitUI(**kwargs)
# 	#renderSubmitUI.setAttribute( QtCore.Qt.WA_DeleteOnClose )
# 	print renderSubmitUI
# 	renderSubmitUI.show()
# 	#renderSubmitUI.raise_()
# 	#renderSubmitUI.exec_()


# ----------------------------------------------------------------------------
# DCC application helper functions - MOVE TO MODULE
# ----------------------------------------------------------------------------

def _maya_delete_ui():
	""" Delete existing UI in Maya.
	"""
	if mc.window(WINDOW_OBJECT, query=True, exists=True):
		mc.deleteUI(WINDOW_OBJECT)  # Delete window
	if mc.dockControl('MayaWindow|' + WINDOW_TITLE, query=True, exists=True):
		mc.deleteUI('MayaWindow|' + WINDOW_TITLE)  # Delete docked window


def _nuke_delete_ui():
	""" Delete existing UI in Nuke.
	"""
	for obj in QtWidgets.QApplication.allWidgets():
		if obj.objectName() == WINDOW_OBJECT:
			obj.deleteLater()


def _maya_main_window():
	""" Return Maya's main window.
	"""
	for obj in QtWidgets.QApplication.topLevelWidgets():
		if obj.objectName() == 'MayaWindow':
			return obj
	raise RuntimeError("Could not find MayaWindow instance")


def _nuke_main_window():
	""" Returns Nuke's main window.
	"""
	for obj in QtWidgets.QApplication.topLevelWidgets():
		if (obj.inherits('QMainWindow') and obj.metaObject().className() == 'Foundry::UI::DockMainWindow'):
			return obj
	raise RuntimeError("Could not find DockMainWindow instance")


# ----------------------------------------------------------------------------
# Run functions
# ----------------------------------------------------------------------------

def run_maya(**kwargs):
	""" Run in Maya.
	"""
	# if mc.window(WINDOW_OBJECT, query=True, exists=True):
	# 	mc.showWindow(WINDOW_OBJECT)
	# else:
	# 	_maya_delete_ui()  # Delete any already existing UI
	# 	renderSubmitUI = RenderSubmitUI(parent=_maya_main_window())

	# 	# Makes Maya perform magic which makes the window stay on top in OS X and
	# 	# Linux. As an added bonus, it'll make Maya remember the window position.
	# 	renderSubmitUI.setProperty("saveWindowPref", True)

	# 	renderSubmitUI.display(**kwargs)  # Show the UI

	_maya_delete_ui()  # Delete any already existing UI
	renderSubmitUI = RenderSubmitUI(parent=_maya_main_window())

	# Makes Maya perform magic which makes the window stay on top in OS X and
	# Linux. As an added bonus, it'll make Maya remember the window position.
	renderSubmitUI.setProperty("saveWindowPref", True)

	renderSubmitUI.display(**kwargs)  # Show the UI


def run_nuke(**kwargs):
	""" Run in Nuke.

		Note:
			If you want the UI to always stay on top, replace:
			'renderSubmitUI.ui.setWindowFlags(QtCore.Qt.Tool)'
			with:
			'renderSubmitUI.ui.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)'

			If you want the UI to be modal:
			'renderSubmitUI.ui.setWindowModality(QtCore.Qt.WindowModal)'
	"""
	_nuke_delete_ui()  # Delete any already existing UI
	renderSubmitUI = RenderSubmitUI(parent=_nuke_main_window())

	# renderSubmitUI.setWindowFlags(QtCore.Qt.Tool)

	renderSubmitUI.display(**kwargs)  # Show the UI


# Detect environment and run application
if os.environ['IC_ENV'] == 'MAYA':
	import maya.cmds as mc
	verbose.print_("GPS Render Submit for Maya", 4)
	# run_maya()
elif os.environ['IC_ENV'] == 'NUKE':
	import nuke
	import nukescripts
	verbose.print_("GPS Render Submit for Nuke", 4)
	# run_nuke()
# elif __name__ == '__main__':
# 	run_standalone()

