# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'job_management_ui.ui'
#
# Created: Tue Aug 16 17:44:52 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(512, 512)
        Dialog.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.renderQueueToolbar_frame = QtGui.QFrame(Dialog)
        self.renderQueueToolbar_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.renderQueueToolbar_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.renderQueueToolbar_frame.setObjectName("renderQueueToolbar_frame")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.renderQueueToolbar_frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.jobAdd_toolButton = QtGui.QToolButton(self.renderQueueToolbar_frame)
        self.jobAdd_toolButton.setMinimumSize(QtCore.QSize(64, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_add_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.jobAdd_toolButton.setIcon(icon)
        self.jobAdd_toolButton.setIconSize(QtCore.QSize(32, 32))
        self.jobAdd_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.jobAdd_toolButton.setObjectName("jobAdd_toolButton")
        self.horizontalLayout_10.addWidget(self.jobAdd_toolButton)
        self.jobDelete_toolButton = QtGui.QToolButton(self.renderQueueToolbar_frame)
        self.jobDelete_toolButton.setMinimumSize(QtCore.QSize(64, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_delete_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.jobDelete_toolButton.setIcon(icon1)
        self.jobDelete_toolButton.setIconSize(QtCore.QSize(32, 32))
        self.jobDelete_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.jobDelete_toolButton.setObjectName("jobDelete_toolButton")
        self.horizontalLayout_10.addWidget(self.jobDelete_toolButton)
        self.refresh_toolButton = QtGui.QToolButton(self.renderQueueToolbar_frame)
        self.refresh_toolButton.setMinimumSize(QtCore.QSize(64, 0))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_refresh_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.refresh_toolButton.setIcon(icon2)
        self.refresh_toolButton.setIconSize(QtCore.QSize(32, 32))
        self.refresh_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.refresh_toolButton.setObjectName("refresh_toolButton")
        self.horizontalLayout_10.addWidget(self.refresh_toolButton)
        self.jobEdit_toolButton = QtGui.QToolButton(self.renderQueueToolbar_frame)
        self.jobEdit_toolButton.setMinimumSize(QtCore.QSize(64, 0))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_editor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_editor_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.jobEdit_toolButton.setIcon(icon3)
        self.jobEdit_toolButton.setIconSize(QtCore.QSize(32, 32))
        self.jobEdit_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.jobEdit_toolButton.setObjectName("jobEdit_toolButton")
        self.horizontalLayout_10.addWidget(self.jobEdit_toolButton)
        self.jobEnable_toolButton = QtGui.QToolButton(self.renderQueueToolbar_frame)
        self.jobEnable_toolButton.setMinimumSize(QtCore.QSize(64, 0))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_tick_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.jobEnable_toolButton.setIcon(icon4)
        self.jobEnable_toolButton.setIconSize(QtCore.QSize(32, 32))
        self.jobEnable_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.jobEnable_toolButton.setObjectName("jobEnable_toolButton")
        self.horizontalLayout_10.addWidget(self.jobEnable_toolButton)
        self.jobDisable_toolButton = QtGui.QToolButton(self.renderQueueToolbar_frame)
        self.jobDisable_toolButton.setMinimumSize(QtCore.QSize(64, 0))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_cross_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.jobDisable_toolButton.setIcon(icon5)
        self.jobDisable_toolButton.setIconSize(QtCore.QSize(32, 32))
        self.jobDisable_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.jobDisable_toolButton.setObjectName("jobDisable_toolButton")
        self.horizontalLayout_10.addWidget(self.jobDisable_toolButton)
        self.editPaths_toolButton = QtGui.QToolButton(self.renderQueueToolbar_frame)
        self.editPaths_toolButton.setMinimumSize(QtCore.QSize(64, 0))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_folder_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.editPaths_toolButton.setIcon(icon6)
        self.editPaths_toolButton.setIconSize(QtCore.QSize(32, 32))
        self.editPaths_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.editPaths_toolButton.setObjectName("editPaths_toolButton")
        self.horizontalLayout_10.addWidget(self.editPaths_toolButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.verticalLayout.addWidget(self.renderQueueToolbar_frame)
        self.jobs_listWidget = QtGui.QListWidget(Dialog)
        self.jobs_listWidget.setAlternatingRowColors(True)
        self.jobs_listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.jobs_listWidget.setObjectName("jobs_listWidget")
        self.verticalLayout.addWidget(self.jobs_listWidget)
        self.main_buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.main_buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.main_buttonBox.setObjectName("main_buttonBox")
        self.verticalLayout.addWidget(self.main_buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Job Management", None, QtGui.QApplication.UnicodeUTF8))
        self.jobAdd_toolButton.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Add a new job</span></p><p>Add a job to the jobs database.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.jobAdd_toolButton.setText(QtGui.QApplication.translate("Dialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.jobDelete_toolButton.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Remove job(s)</span></p><p>Remove the selected job(s) from the jobs database.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.jobDelete_toolButton.setText(QtGui.QApplication.translate("Dialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_toolButton.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Refresh</span></p><p>Reload the jobs database and update the view. This will undo any unsaved changes you have made.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_toolButton.setText(QtGui.QApplication.translate("Dialog", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.jobEdit_toolButton.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Edit job</span></p><p>Modify the selected job settings.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.jobEdit_toolButton.setText(QtGui.QApplication.translate("Dialog", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.jobEnable_toolButton.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Enable job(s)</span></p><p>The selected job(s) will be marked as enabled. They will appear in the main UI.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.jobEnable_toolButton.setText(QtGui.QApplication.translate("Dialog", "Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.jobDisable_toolButton.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Disable job(s)</span></p><p>The selected job(s) will be marked as disabled. They will not appear in the main UI.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.jobDisable_toolButton.setText(QtGui.QApplication.translate("Dialog", "Disable", None, QtGui.QApplication.UnicodeUTF8))
        self.editPaths_toolButton.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Edit paths</span></p><p>Set up the root filesystem paths where jobs and other data will be stored. This enables portability between different operating systems.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.editPaths_toolButton.setText(QtGui.QApplication.translate("Dialog", "Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.jobs_listWidget.setSortingEnabled(True)

import rsc_rc
