# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_app_paths_ui.ui'
#
# Created: Tue May 12 14:03:31 2015
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(576, 384)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.appVer_groupBox = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appVer_groupBox.sizePolicy().hasHeightForWidth())
        self.appVer_groupBox.setSizePolicy(sizePolicy)
        self.appVer_groupBox.setObjectName("appVer_groupBox")
        self.formLayout_10 = QtGui.QFormLayout(self.appVer_groupBox)
        self.formLayout_10.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_10.setObjectName("formLayout_10")
        self.appName_label = QtGui.QLabel(self.appVer_groupBox)
        self.appName_label.setObjectName("appName_label")
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.appName_label)
        self.appName_horizontalLayout = QtGui.QHBoxLayout()
        self.appName_horizontalLayout.setObjectName("appName_horizontalLayout")
        self.appName_comboBox = QtGui.QComboBox(self.appVer_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appName_comboBox.sizePolicy().hasHeightForWidth())
        self.appName_comboBox.setSizePolicy(sizePolicy)
        self.appName_comboBox.setEditable(True)
        self.appName_comboBox.setProperty("mandatoryField", False)
        self.appName_comboBox.setObjectName("appName_comboBox")
        self.appName_horizontalLayout.addWidget(self.appName_comboBox)
        self.appNameDel_toolButton = QtGui.QToolButton(self.appVer_groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_delete_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.appNameDel_toolButton.setIcon(icon)
        self.appNameDel_toolButton.setIconSize(QtCore.QSize(15, 15))
        self.appNameDel_toolButton.setObjectName("appNameDel_toolButton")
        self.appName_horizontalLayout.addWidget(self.appNameDel_toolButton)
        self.formLayout_10.setLayout(0, QtGui.QFormLayout.FieldRole, self.appName_horizontalLayout)
        self.appVer_label = QtGui.QLabel(self.appVer_groupBox)
        self.appVer_label.setObjectName("appVer_label")
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.LabelRole, self.appVer_label)
        self.appVer_horizontalLayout = QtGui.QHBoxLayout()
        self.appVer_horizontalLayout.setObjectName("appVer_horizontalLayout")
        self.appVer_comboBox = QtGui.QComboBox(self.appVer_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appVer_comboBox.sizePolicy().hasHeightForWidth())
        self.appVer_comboBox.setSizePolicy(sizePolicy)
        self.appVer_comboBox.setEditable(True)
        self.appVer_comboBox.setProperty("mandatoryField", False)
        self.appVer_comboBox.setObjectName("appVer_comboBox")
        self.appVer_horizontalLayout.addWidget(self.appVer_comboBox)
        self.appVerDel_toolButton = QtGui.QToolButton(self.appVer_groupBox)
        self.appVerDel_toolButton.setIcon(icon)
        self.appVerDel_toolButton.setIconSize(QtCore.QSize(15, 15))
        self.appVerDel_toolButton.setObjectName("appVerDel_toolButton")
        self.appVer_horizontalLayout.addWidget(self.appVerDel_toolButton)
        self.formLayout_10.setLayout(1, QtGui.QFormLayout.FieldRole, self.appVer_horizontalLayout)
        self.verticalLayout.addWidget(self.appVer_groupBox)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.execPaths_groupBox = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.execPaths_groupBox.sizePolicy().hasHeightForWidth())
        self.execPaths_groupBox.setSizePolicy(sizePolicy)
        self.execPaths_groupBox.setObjectName("execPaths_groupBox")
        self.formLayout_9 = QtGui.QFormLayout(self.execPaths_groupBox)
        self.formLayout_9.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_9.setObjectName("formLayout_9")
        self.osxPath_label = QtGui.QLabel(self.execPaths_groupBox)
        self.osxPath_label.setObjectName("osxPath_label")
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.osxPath_label)
        self.osxPath_horizontalLayout = QtGui.QHBoxLayout()
        self.osxPath_horizontalLayout.setObjectName("osxPath_horizontalLayout")
        self.osxPath_lineEdit = QtGui.QLineEdit(self.execPaths_groupBox)
        self.osxPath_lineEdit.setObjectName("osxPath_lineEdit")
        self.osxPath_horizontalLayout.addWidget(self.osxPath_lineEdit)
        self.formLayout_9.setLayout(0, QtGui.QFormLayout.FieldRole, self.osxPath_horizontalLayout)
        self.linuxPath_label = QtGui.QLabel(self.execPaths_groupBox)
        self.linuxPath_label.setObjectName("linuxPath_label")
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.LabelRole, self.linuxPath_label)
        self.linuxPath_horizontalLayout = QtGui.QHBoxLayout()
        self.linuxPath_horizontalLayout.setObjectName("linuxPath_horizontalLayout")
        self.linuxPath_lineEdit = QtGui.QLineEdit(self.execPaths_groupBox)
        self.linuxPath_lineEdit.setObjectName("linuxPath_lineEdit")
        self.linuxPath_horizontalLayout.addWidget(self.linuxPath_lineEdit)
        self.formLayout_9.setLayout(1, QtGui.QFormLayout.FieldRole, self.linuxPath_horizontalLayout)
        self.winPath_label = QtGui.QLabel(self.execPaths_groupBox)
        self.winPath_label.setObjectName("winPath_label")
        self.formLayout_9.setWidget(2, QtGui.QFormLayout.LabelRole, self.winPath_label)
        self.winPath_horizontalLayout = QtGui.QHBoxLayout()
        self.winPath_horizontalLayout.setObjectName("winPath_horizontalLayout")
        self.winPath_lineEdit = QtGui.QLineEdit(self.execPaths_groupBox)
        self.winPath_lineEdit.setObjectName("winPath_lineEdit")
        self.winPath_horizontalLayout.addWidget(self.winPath_lineEdit)
        self.formLayout_9.setLayout(2, QtGui.QFormLayout.FieldRole, self.winPath_horizontalLayout)
        self.appPaths_horizontalLayout = QtGui.QHBoxLayout()
        self.appPaths_horizontalLayout.setObjectName("appPaths_horizontalLayout")
        self.guess_pushButton = QtGui.QPushButton(self.execPaths_groupBox)
        self.guess_pushButton.setObjectName("guess_pushButton")
        self.appPaths_horizontalLayout.addWidget(self.guess_pushButton)
        self.formLayout_9.setLayout(3, QtGui.QFormLayout.FieldRole, self.appPaths_horizontalLayout)
        self.verticalLayout.addWidget(self.execPaths_groupBox)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.appPaths_buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.appPaths_buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.appPaths_buttonBox.setObjectName("appPaths_buttonBox")
        self.verticalLayout.addWidget(self.appPaths_buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Set Application Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.appVer_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Applications and versions", None, QtGui.QApplication.UnicodeUTF8))
        self.appName_label.setText(QtGui.QApplication.translate("Dialog", "Application:", None, QtGui.QApplication.UnicodeUTF8))
        self.appName_comboBox.setToolTip(QtGui.QApplication.translate("Dialog", "Select an application, or add a new application by typing a new name and pressing Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.appNameDel_toolButton.setToolTip(QtGui.QApplication.translate("Dialog", "Remove this application", None, QtGui.QApplication.UnicodeUTF8))
        self.appNameDel_toolButton.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.appVer_label.setText(QtGui.QApplication.translate("Dialog", "Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.appVer_comboBox.setToolTip(QtGui.QApplication.translate("Dialog", "Select a version for this application, or add a new version by typing a new name and pressing Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.appVerDel_toolButton.setToolTip(QtGui.QApplication.translate("Dialog", "Remove this version of the application", None, QtGui.QApplication.UnicodeUTF8))
        self.appVerDel_toolButton.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.execPaths_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Executable paths", None, QtGui.QApplication.UnicodeUTF8))
        self.osxPath_label.setText(QtGui.QApplication.translate("Dialog", "Mac OS X:", None, QtGui.QApplication.UnicodeUTF8))
        self.linuxPath_label.setText(QtGui.QApplication.translate("Dialog", "Linux:", None, QtGui.QApplication.UnicodeUTF8))
        self.winPath_label.setText(QtGui.QApplication.translate("Dialog", "Windows:", None, QtGui.QApplication.UnicodeUTF8))
        self.guess_pushButton.setToolTip(QtGui.QApplication.translate("Dialog", "Try to guess the executable paths based on the template", None, QtGui.QApplication.UnicodeUTF8))
        self.guess_pushButton.setText(QtGui.QApplication.translate("Dialog", "Guess", None, QtGui.QApplication.UnicodeUTF8))

