# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_resolution_ui.ui'
#
# Created: Fri May 15 18:47:12 2015
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(400, 240)
        Frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.formLayout = QtGui.QFormLayout(Frame)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.resPreset_label = QtGui.QLabel(Frame)
        self.resPreset_label.setObjectName("resPreset_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.resPreset_label)
        self.resPreset_comboBox = QtGui.QComboBox(Frame)
        self.resPreset_comboBox.setObjectName("resPreset_comboBox")
        self.resPreset_comboBox.addItem("")
        self.resPreset_comboBox.addItem("")
        self.resPreset_comboBox.addItem("")
        self.resPreset_comboBox.addItem("")
        self.resPreset_comboBox.addItem("")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.resPreset_comboBox)
        self.res_label = QtGui.QLabel(Frame)
        self.res_label.setObjectName("res_label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.res_label)
        self.res_horizontalLayout = QtGui.QHBoxLayout()
        self.res_horizontalLayout.setObjectName("res_horizontalLayout")
        self.resX_spinBox = QtGui.QSpinBox(Frame)
        self.resX_spinBox.setMinimum(1)
        self.resX_spinBox.setMaximum(99999)
        self.resX_spinBox.setProperty("value", 1920)
        self.resX_spinBox.setObjectName("resX_spinBox")
        self.res_horizontalLayout.addWidget(self.resX_spinBox)
        self.resSep_label = QtGui.QLabel(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resSep_label.sizePolicy().hasHeightForWidth())
        self.resSep_label.setSizePolicy(sizePolicy)
        self.resSep_label.setObjectName("resSep_label")
        self.res_horizontalLayout.addWidget(self.resSep_label)
        self.resY_spinBox = QtGui.QSpinBox(Frame)
        self.resY_spinBox.setMinimum(1)
        self.resY_spinBox.setMaximum(99999)
        self.resY_spinBox.setProperty("value", 1080)
        self.resY_spinBox.setObjectName("resY_spinBox")
        self.res_horizontalLayout.addWidget(self.resY_spinBox)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.res_horizontalLayout)
        self.proxyMode_label = QtGui.QLabel(Frame)
        self.proxyMode_label.setObjectName("proxyMode_label")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.proxyMode_label)
        self.proxyMode_horizontalLayout = QtGui.QHBoxLayout()
        self.proxyMode_horizontalLayout.setObjectName("proxyMode_horizontalLayout")
        self.scale_radioButton = QtGui.QRadioButton(Frame)
        self.scale_radioButton.setChecked(True)
        self.scale_radioButton.setObjectName("scale_radioButton")
        self.proxyMode_horizontalLayout.addWidget(self.scale_radioButton)
        self.res_radioButton = QtGui.QRadioButton(Frame)
        self.res_radioButton.setObjectName("res_radioButton")
        self.proxyMode_horizontalLayout.addWidget(self.res_radioButton)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.proxyMode_horizontalLayout)
        self.proxyScale_label = QtGui.QLabel(Frame)
        self.proxyScale_label.setObjectName("proxyScale_label")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.proxyScale_label)
        self.proxyScale_horizontalLayout = QtGui.QHBoxLayout()
        self.proxyScale_horizontalLayout.setObjectName("proxyScale_horizontalLayout")
        self.proxyScale_doubleSpinBox = QtGui.QDoubleSpinBox(Frame)
        self.proxyScale_doubleSpinBox.setMaximum(1.0)
        self.proxyScale_doubleSpinBox.setSingleStep(0.01)
        self.proxyScale_doubleSpinBox.setProperty("value", 0.5)
        self.proxyScale_doubleSpinBox.setObjectName("proxyScale_doubleSpinBox")
        self.proxyScale_horizontalLayout.addWidget(self.proxyScale_doubleSpinBox)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.proxyScale_horizontalLayout)
        self.proxyRes_label = QtGui.QLabel(Frame)
        self.proxyRes_label.setObjectName("proxyRes_label")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.proxyRes_label)
        self.proxyRes_horizontalLayout = QtGui.QHBoxLayout()
        self.proxyRes_horizontalLayout.setObjectName("proxyRes_horizontalLayout")
        self.proxyResX_spinBox = QtGui.QSpinBox(Frame)
        self.proxyResX_spinBox.setMinimum(1)
        self.proxyResX_spinBox.setMaximum(99999)
        self.proxyResX_spinBox.setProperty("value", 960)
        self.proxyResX_spinBox.setObjectName("proxyResX_spinBox")
        self.proxyRes_horizontalLayout.addWidget(self.proxyResX_spinBox)
        self.proxyResSep_label = QtGui.QLabel(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proxyResSep_label.sizePolicy().hasHeightForWidth())
        self.proxyResSep_label.setSizePolicy(sizePolicy)
        self.proxyResSep_label.setObjectName("proxyResSep_label")
        self.proxyRes_horizontalLayout.addWidget(self.proxyResSep_label)
        self.proxyResY_spinBox = QtGui.QSpinBox(Frame)
        self.proxyResY_spinBox.setMinimum(1)
        self.proxyResY_spinBox.setMaximum(99999)
        self.proxyResY_spinBox.setProperty("value", 540)
        self.proxyResY_spinBox.setObjectName("proxyResY_spinBox")
        self.proxyRes_horizontalLayout.addWidget(self.proxyResY_spinBox)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.proxyRes_horizontalLayout)
        self.preserveAR_checkBox = QtGui.QCheckBox(Frame)
        self.preserveAR_checkBox.setChecked(True)
        self.preserveAR_checkBox.setObjectName("preserveAR_checkBox")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.preserveAR_checkBox)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)
        Frame.setTabOrder(self.resPreset_comboBox, self.resX_spinBox)
        Frame.setTabOrder(self.resX_spinBox, self.resY_spinBox)
        Frame.setTabOrder(self.resY_spinBox, self.scale_radioButton)
        Frame.setTabOrder(self.scale_radioButton, self.res_radioButton)
        Frame.setTabOrder(self.res_radioButton, self.proxyScale_doubleSpinBox)
        Frame.setTabOrder(self.proxyScale_doubleSpinBox, self.proxyResX_spinBox)
        Frame.setTabOrder(self.proxyResX_spinBox, self.proxyResY_spinBox)
        Frame.setTabOrder(self.proxyResY_spinBox, self.preserveAR_checkBox)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.resPreset_label.setText(QtGui.QApplication.translate("Frame", "Preset:", None, QtGui.QApplication.UnicodeUTF8))
        self.resPreset_comboBox.setItemText(0, QtGui.QApplication.translate("Frame", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.resPreset_comboBox.setItemText(1, QtGui.QApplication.translate("Frame", "HD 1080p", None, QtGui.QApplication.UnicodeUTF8))
        self.resPreset_comboBox.setItemText(2, QtGui.QApplication.translate("Frame", "HD 720p", None, QtGui.QApplication.UnicodeUTF8))
        self.resPreset_comboBox.setItemText(3, QtGui.QApplication.translate("Frame", "PAL 576p 16:9", None, QtGui.QApplication.UnicodeUTF8))
        self.resPreset_comboBox.setItemText(4, QtGui.QApplication.translate("Frame", "PAL 576p 4:3", None, QtGui.QApplication.UnicodeUTF8))
        self.res_label.setText(QtGui.QApplication.translate("Frame", "Full size resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.resSep_label.setText(QtGui.QApplication.translate("Frame", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.proxyMode_label.setText(QtGui.QApplication.translate("Frame", "Proxy mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_radioButton.setText(QtGui.QApplication.translate("Frame", "Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.res_radioButton.setText(QtGui.QApplication.translate("Frame", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.proxyScale_label.setText(QtGui.QApplication.translate("Frame", "Proxy scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.proxyRes_label.setText(QtGui.QApplication.translate("Frame", "Proxy resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.proxyResSep_label.setText(QtGui.QApplication.translate("Frame", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.preserveAR_checkBox.setText(QtGui.QApplication.translate("Frame", "Preserve aspect ratio", None, QtGui.QApplication.UnicodeUTF8))

