# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_camera_ui.ui'
#
# Created: Tue Jan 12 19:13:14 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_settings_frame(object):
    def setupUi(self, settings_frame):
        settings_frame.setObjectName("settings_frame")
        settings_frame.resize(400, 420)
        settings_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.formLayout = QtGui.QFormLayout(settings_frame)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.camPreset_label = QtGui.QLabel(settings_frame)
        self.camPreset_label.setObjectName("camPreset_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.camPreset_label)
        self.camPreset_comboBox = QtGui.QComboBox(settings_frame)
        self.camPreset_comboBox.setObjectName("camPreset_comboBox")
        self.camPreset_comboBox.addItem("")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.camPreset_comboBox)
        self.filmback_label = QtGui.QLabel(settings_frame)
        self.filmback_label.setObjectName("filmback_label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.filmback_label)
        self.filmback_horizontalLayout = QtGui.QHBoxLayout()
        self.filmback_horizontalLayout.setObjectName("filmback_horizontalLayout")
        self.filmbackWidth_doubleSpinBox = QtGui.QDoubleSpinBox(settings_frame)
        self.filmbackWidth_doubleSpinBox.setDecimals(1)
        self.filmbackWidth_doubleSpinBox.setMinimum(0.1)
        self.filmbackWidth_doubleSpinBox.setMaximum(1000.0)
        self.filmbackWidth_doubleSpinBox.setSingleStep(0.1)
        self.filmbackWidth_doubleSpinBox.setProperty("value", 23.8)
        self.filmbackWidth_doubleSpinBox.setObjectName("filmbackWidth_doubleSpinBox")
        self.filmback_horizontalLayout.addWidget(self.filmbackWidth_doubleSpinBox)
        self.filmbackSep_label = QtGui.QLabel(settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filmbackSep_label.sizePolicy().hasHeightForWidth())
        self.filmbackSep_label.setSizePolicy(sizePolicy)
        self.filmbackSep_label.setObjectName("filmbackSep_label")
        self.filmback_horizontalLayout.addWidget(self.filmbackSep_label)
        self.filmbackHeight_doubleSpinBox = QtGui.QDoubleSpinBox(settings_frame)
        self.filmbackHeight_doubleSpinBox.setDecimals(1)
        self.filmbackHeight_doubleSpinBox.setMinimum(0.1)
        self.filmbackHeight_doubleSpinBox.setMaximum(1000.0)
        self.filmbackHeight_doubleSpinBox.setSingleStep(0.1)
        self.filmbackHeight_doubleSpinBox.setProperty("value", 13.4)
        self.filmbackHeight_doubleSpinBox.setObjectName("filmbackHeight_doubleSpinBox")
        self.filmback_horizontalLayout.addWidget(self.filmbackHeight_doubleSpinBox)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.filmback_horizontalLayout)
        self.shutterAngle_label = QtGui.QLabel(settings_frame)
        self.shutterAngle_label.setObjectName("shutterAngle_label")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.shutterAngle_label)
        self.shutterAngle_doubleSpinBox = QtGui.QDoubleSpinBox(settings_frame)
        self.shutterAngle_doubleSpinBox.setEnabled(True)
        self.shutterAngle_doubleSpinBox.setDecimals(1)
        self.shutterAngle_doubleSpinBox.setMinimum(0.0)
        self.shutterAngle_doubleSpinBox.setMaximum(180.0)
        self.shutterAngle_doubleSpinBox.setSingleStep(1.0)
        self.shutterAngle_doubleSpinBox.setProperty("value", 180.0)
        self.shutterAngle_doubleSpinBox.setObjectName("shutterAngle_doubleSpinBox")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.shutterAngle_doubleSpinBox)
        self.lensPreset_label = QtGui.QLabel(settings_frame)
        self.lensPreset_label.setObjectName("lensPreset_label")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lensPreset_label)
        self.lensPreset_comboBox = QtGui.QComboBox(settings_frame)
        self.lensPreset_comboBox.setObjectName("lensPreset_comboBox")
        self.lensPreset_comboBox.addItem("")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lensPreset_comboBox)
        self.focalLength_label = QtGui.QLabel(settings_frame)
        self.focalLength_label.setObjectName("focalLength_label")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.focalLength_label)
        self.focalLength_doubleSpinBox = QtGui.QDoubleSpinBox(settings_frame)
        self.focalLength_doubleSpinBox.setEnabled(True)
        self.focalLength_doubleSpinBox.setDecimals(1)
        self.focalLength_doubleSpinBox.setMinimum(0.1)
        self.focalLength_doubleSpinBox.setMaximum(1000.0)
        self.focalLength_doubleSpinBox.setSingleStep(0.1)
        self.focalLength_doubleSpinBox.setProperty("value", 35.0)
        self.focalLength_doubleSpinBox.setObjectName("focalLength_doubleSpinBox")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.focalLength_doubleSpinBox)
        self.aperture_label = QtGui.QLabel(settings_frame)
        self.aperture_label.setObjectName("aperture_label")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.aperture_label)
        self.aperture_doubleSpinBox = QtGui.QDoubleSpinBox(settings_frame)
        self.aperture_doubleSpinBox.setEnabled(True)
        self.aperture_doubleSpinBox.setDecimals(1)
        self.aperture_doubleSpinBox.setMinimum(0.1)
        self.aperture_doubleSpinBox.setMaximum(100.0)
        self.aperture_doubleSpinBox.setSingleStep(0.1)
        self.aperture_doubleSpinBox.setProperty("value", 5.6)
        self.aperture_doubleSpinBox.setObjectName("aperture_doubleSpinBox")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.aperture_doubleSpinBox)
        self.clipRef_label = QtGui.QLabel(settings_frame)
        self.clipRef_label.setObjectName("clipRef_label")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.clipRef_label)
        self.clipRef_lineEdit = QtGui.QLineEdit(settings_frame)
        self.clipRef_lineEdit.setObjectName("clipRef_lineEdit")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.clipRef_lineEdit)
        self.camHeight_label = QtGui.QLabel(settings_frame)
        self.camHeight_label.setObjectName("camHeight_label")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.camHeight_label)
        self.camHeight_doubleSpinBox = QtGui.QDoubleSpinBox(settings_frame)
        self.camHeight_doubleSpinBox.setEnabled(True)
        self.camHeight_doubleSpinBox.setDecimals(2)
        self.camHeight_doubleSpinBox.setMinimum(0.0)
        self.camHeight_doubleSpinBox.setMaximum(1000.0)
        self.camHeight_doubleSpinBox.setSingleStep(0.1)
        self.camHeight_doubleSpinBox.setObjectName("camHeight_doubleSpinBox")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.camHeight_doubleSpinBox)
        self.camPitch_label = QtGui.QLabel(settings_frame)
        self.camPitch_label.setObjectName("camPitch_label")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.camPitch_label)
        self.camPitch_doubleSpinBox = QtGui.QDoubleSpinBox(settings_frame)
        self.camPitch_doubleSpinBox.setEnabled(True)
        self.camPitch_doubleSpinBox.setDecimals(1)
        self.camPitch_doubleSpinBox.setMinimum(-180.0)
        self.camPitch_doubleSpinBox.setMaximum(180.0)
        self.camPitch_doubleSpinBox.setSingleStep(1.0)
        self.camPitch_doubleSpinBox.setObjectName("camPitch_doubleSpinBox")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.camPitch_doubleSpinBox)
        self.focusDistance_label = QtGui.QLabel(settings_frame)
        self.focusDistance_label.setObjectName("focusDistance_label")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.focusDistance_label)
        self.focusDistance_doubleSpinBox = QtGui.QDoubleSpinBox(settings_frame)
        self.focusDistance_doubleSpinBox.setEnabled(True)
        self.focusDistance_doubleSpinBox.setDecimals(2)
        self.focusDistance_doubleSpinBox.setMinimum(0.0)
        self.focusDistance_doubleSpinBox.setMaximum(1000.0)
        self.focusDistance_doubleSpinBox.setSingleStep(0.1)
        self.focusDistance_doubleSpinBox.setObjectName("focusDistance_doubleSpinBox")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.focusDistance_doubleSpinBox)
        self.subjectDistance_label = QtGui.QLabel(settings_frame)
        self.subjectDistance_label.setObjectName("subjectDistance_label")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.subjectDistance_label)
        self.subjectDistance_doubleSpinBox = QtGui.QDoubleSpinBox(settings_frame)
        self.subjectDistance_doubleSpinBox.setEnabled(True)
        self.subjectDistance_doubleSpinBox.setDecimals(2)
        self.subjectDistance_doubleSpinBox.setMinimum(0.0)
        self.subjectDistance_doubleSpinBox.setMaximum(1000.0)
        self.subjectDistance_doubleSpinBox.setSingleStep(0.1)
        self.subjectDistance_doubleSpinBox.setObjectName("subjectDistance_doubleSpinBox")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.subjectDistance_doubleSpinBox)
        self.filter_label = QtGui.QLabel(settings_frame)
        self.filter_label.setObjectName("filter_label")
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.filter_label)
        self.filter_lineEdit = QtGui.QLineEdit(settings_frame)
        self.filter_lineEdit.setObjectName("filter_lineEdit")
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.filter_lineEdit)
        self.notes_label = QtGui.QLabel(settings_frame)
        self.notes_label.setObjectName("notes_label")
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.notes_label)
        self.plainTextEdit = QtGui.QPlainTextEdit(settings_frame)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.plainTextEdit)

        self.retranslateUi(settings_frame)
        QtCore.QMetaObject.connectSlotsByName(settings_frame)
        settings_frame.setTabOrder(self.filmbackWidth_doubleSpinBox, self.filmbackHeight_doubleSpinBox)

    def retranslateUi(self, settings_frame):
        settings_frame.setWindowTitle(QtGui.QApplication.translate("settings_frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.camPreset_label.setText(QtGui.QApplication.translate("settings_frame", "Camera:", None, QtGui.QApplication.UnicodeUTF8))
        self.camPreset_comboBox.setItemText(0, QtGui.QApplication.translate("settings_frame", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.filmback_label.setText(QtGui.QApplication.translate("settings_frame", "Film back / sensor size:", None, QtGui.QApplication.UnicodeUTF8))
        self.filmbackWidth_doubleSpinBox.setSuffix(QtGui.QApplication.translate("settings_frame", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.filmbackWidth_doubleSpinBox.setProperty("xmlTag", QtGui.QApplication.translate("settings_frame", "filmbackWidth", None, QtGui.QApplication.UnicodeUTF8))
        self.filmbackSep_label.setText(QtGui.QApplication.translate("settings_frame", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.filmbackHeight_doubleSpinBox.setSuffix(QtGui.QApplication.translate("settings_frame", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.filmbackHeight_doubleSpinBox.setProperty("xmlTag", QtGui.QApplication.translate("settings_frame", "filmbackHeight", None, QtGui.QApplication.UnicodeUTF8))
        self.shutterAngle_label.setText(QtGui.QApplication.translate("settings_frame", "Shutter angle:", None, QtGui.QApplication.UnicodeUTF8))
        self.shutterAngle_doubleSpinBox.setProperty("xmlTag", QtGui.QApplication.translate("settings_frame", "shutterAngle", None, QtGui.QApplication.UnicodeUTF8))
        self.lensPreset_label.setText(QtGui.QApplication.translate("settings_frame", "Lens:", None, QtGui.QApplication.UnicodeUTF8))
        self.lensPreset_comboBox.setItemText(0, QtGui.QApplication.translate("settings_frame", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.focalLength_label.setText(QtGui.QApplication.translate("settings_frame", "Focal length:", None, QtGui.QApplication.UnicodeUTF8))
        self.focalLength_doubleSpinBox.setSuffix(QtGui.QApplication.translate("settings_frame", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.focalLength_doubleSpinBox.setProperty("xmlTag", QtGui.QApplication.translate("settings_frame", "focalLength", None, QtGui.QApplication.UnicodeUTF8))
        self.aperture_label.setText(QtGui.QApplication.translate("settings_frame", "F-stop / aperture:", None, QtGui.QApplication.UnicodeUTF8))
        self.aperture_doubleSpinBox.setProperty("xmlTag", QtGui.QApplication.translate("settings_frame", "aperture", None, QtGui.QApplication.UnicodeUTF8))
        self.clipRef_label.setText(QtGui.QApplication.translate("settings_frame", "Clip / reel ref:", None, QtGui.QApplication.UnicodeUTF8))
        self.clipRef_lineEdit.setProperty("xmlTag", QtGui.QApplication.translate("settings_frame", "clipRef", None, QtGui.QApplication.UnicodeUTF8))
        self.camHeight_label.setText(QtGui.QApplication.translate("settings_frame", "Cam height:", None, QtGui.QApplication.UnicodeUTF8))
        self.camHeight_doubleSpinBox.setSuffix(QtGui.QApplication.translate("settings_frame", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.camHeight_doubleSpinBox.setProperty("xmlTag", QtGui.QApplication.translate("settings_frame", "camHeight", None, QtGui.QApplication.UnicodeUTF8))
        self.camPitch_label.setText(QtGui.QApplication.translate("settings_frame", "Cam pitch (angle):", None, QtGui.QApplication.UnicodeUTF8))
        self.camPitch_doubleSpinBox.setProperty("xmlTag", QtGui.QApplication.translate("settings_frame", "camPitch", None, QtGui.QApplication.UnicodeUTF8))
        self.focusDistance_label.setText(QtGui.QApplication.translate("settings_frame", "Focus distance:", None, QtGui.QApplication.UnicodeUTF8))
        self.focusDistance_doubleSpinBox.setSuffix(QtGui.QApplication.translate("settings_frame", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.focusDistance_doubleSpinBox.setProperty("xmlTag", QtGui.QApplication.translate("settings_frame", "focusDistance", None, QtGui.QApplication.UnicodeUTF8))
        self.subjectDistance_label.setText(QtGui.QApplication.translate("settings_frame", "Subject distance:", None, QtGui.QApplication.UnicodeUTF8))
        self.subjectDistance_doubleSpinBox.setSuffix(QtGui.QApplication.translate("settings_frame", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.subjectDistance_doubleSpinBox.setProperty("xmlTag", QtGui.QApplication.translate("settings_frame", "subjectDistance", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_label.setText(QtGui.QApplication.translate("settings_frame", "Filter(s):", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_lineEdit.setProperty("xmlTag", QtGui.QApplication.translate("settings_frame", "filter", None, QtGui.QApplication.UnicodeUTF8))
        self.notes_label.setText(QtGui.QApplication.translate("settings_frame", "Notes:", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit.setProperty("xmlTag", QtGui.QApplication.translate("settings_frame", "notes", None, QtGui.QApplication.UnicodeUTF8))

