# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shot_creator_ui.ui'
#
# Created: Thu Aug 18 16:16:41 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 400)
        Dialog.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.job_groupBox = QtGui.QGroupBox(Dialog)
        self.job_groupBox.setTitle("")
        self.job_groupBox.setObjectName("job_groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.job_groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.job_label = QtGui.QLabel(self.job_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.job_label.sizePolicy().hasHeightForWidth())
        self.job_label.setSizePolicy(sizePolicy)
        self.job_label.setObjectName("job_label")
        self.horizontalLayout.addWidget(self.job_label)
        self.job_comboBox = QtGui.QComboBox(self.job_groupBox)
        self.job_comboBox.setEditable(False)
        self.job_comboBox.setObjectName("job_comboBox")
        self.horizontalLayout.addWidget(self.job_comboBox)
        self.verticalLayout.addWidget(self.job_groupBox)
        self.shotNaming_groupBox = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shotNaming_groupBox.sizePolicy().hasHeightForWidth())
        self.shotNaming_groupBox.setSizePolicy(sizePolicy)
        self.shotNaming_groupBox.setObjectName("shotNaming_groupBox")
        self.formLayout_15 = QtGui.QFormLayout(self.shotNaming_groupBox)
        self.formLayout_15.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_15.setObjectName("formLayout_15")
        self.prefix_label = QtGui.QLabel(self.shotNaming_groupBox)
        self.prefix_label.setObjectName("prefix_label")
        self.formLayout_15.setWidget(1, QtGui.QFormLayout.LabelRole, self.prefix_label)
        self.prefix_comboBox = QtGui.QComboBox(self.shotNaming_groupBox)
        self.prefix_comboBox.setObjectName("prefix_comboBox")
        self.prefix_comboBox.addItem("")
        self.prefix_comboBox.addItem("")
        self.formLayout_15.setWidget(1, QtGui.QFormLayout.FieldRole, self.prefix_comboBox)
        self.start_label = QtGui.QLabel(self.shotNaming_groupBox)
        self.start_label.setObjectName("start_label")
        self.formLayout_15.setWidget(3, QtGui.QFormLayout.LabelRole, self.start_label)
        self.start_spinBox = QtGui.QSpinBox(self.shotNaming_groupBox)
        self.start_spinBox.setMaximum(999)
        self.start_spinBox.setProperty("value", 10)
        self.start_spinBox.setObjectName("start_spinBox")
        self.formLayout_15.setWidget(3, QtGui.QFormLayout.FieldRole, self.start_spinBox)
        self.suffix_label = QtGui.QLabel(self.shotNaming_groupBox)
        self.suffix_label.setObjectName("suffix_label")
        self.formLayout_15.setWidget(7, QtGui.QFormLayout.LabelRole, self.suffix_label)
        self.suffix_lineEdit = QtGui.QLineEdit(self.shotNaming_groupBox)
        self.suffix_lineEdit.setText("")
        self.suffix_lineEdit.setObjectName("suffix_lineEdit")
        self.formLayout_15.setWidget(7, QtGui.QFormLayout.FieldRole, self.suffix_lineEdit)
        self.createSeq_checkBox = QtGui.QCheckBox(self.shotNaming_groupBox)
        self.createSeq_checkBox.setChecked(True)
        self.createSeq_checkBox.setObjectName("createSeq_checkBox")
        self.formLayout_15.setWidget(2, QtGui.QFormLayout.FieldRole, self.createSeq_checkBox)
        self.shotCount_spinBox = QtGui.QSpinBox(self.shotNaming_groupBox)
        self.shotCount_spinBox.setMinimum(1)
        self.shotCount_spinBox.setMaximum(999)
        self.shotCount_spinBox.setProperty("value", 1)
        self.shotCount_spinBox.setObjectName("shotCount_spinBox")
        self.formLayout_15.setWidget(4, QtGui.QFormLayout.FieldRole, self.shotCount_spinBox)
        self.shotCount_label = QtGui.QLabel(self.shotNaming_groupBox)
        self.shotCount_label.setObjectName("shotCount_label")
        self.formLayout_15.setWidget(4, QtGui.QFormLayout.LabelRole, self.shotCount_label)
        self.increment_spinBox = QtGui.QSpinBox(self.shotNaming_groupBox)
        self.increment_spinBox.setMinimum(1)
        self.increment_spinBox.setMaximum(100)
        self.increment_spinBox.setProperty("value", 10)
        self.increment_spinBox.setObjectName("increment_spinBox")
        self.formLayout_15.setWidget(5, QtGui.QFormLayout.FieldRole, self.increment_spinBox)
        self.increment_label = QtGui.QLabel(self.shotNaming_groupBox)
        self.increment_label.setObjectName("increment_label")
        self.formLayout_15.setWidget(5, QtGui.QFormLayout.LabelRole, self.increment_label)
        self.verticalLayout.addWidget(self.shotNaming_groupBox)
        self.shotPreview_groupBox = QtGui.QGroupBox(Dialog)
        self.shotPreview_groupBox.setObjectName("shotPreview_groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.shotPreview_groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.shotPreview_plainTextEdit = QtGui.QPlainTextEdit(self.shotPreview_groupBox)
        self.shotPreview_plainTextEdit.setReadOnly(True)
        self.shotPreview_plainTextEdit.setObjectName("shotPreview_plainTextEdit")
        self.verticalLayout_2.addWidget(self.shotPreview_plainTextEdit)
        self.verticalLayout.addWidget(self.shotPreview_groupBox)
        self.shotCreator_buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.shotCreator_buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.shotCreator_buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Close)
        self.shotCreator_buttonBox.setObjectName("shotCreator_buttonBox")
        self.verticalLayout.addWidget(self.shotCreator_buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.shotCreator_buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.shotCreator_buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QObject.connect(self.createSeq_checkBox, QtCore.SIGNAL("toggled(bool)"), self.shotCount_spinBox.setEnabled)
        QtCore.QObject.connect(self.createSeq_checkBox, QtCore.SIGNAL("toggled(bool)"), self.shotCount_label.setEnabled)
        QtCore.QObject.connect(self.createSeq_checkBox, QtCore.SIGNAL("toggled(bool)"), self.increment_spinBox.setEnabled)
        QtCore.QObject.connect(self.createSeq_checkBox, QtCore.SIGNAL("toggled(bool)"), self.increment_label.setEnabled)
        QtCore.QObject.connect(self.createSeq_checkBox, QtCore.SIGNAL("toggled(bool)"), self.start_spinBox.setEnabled)
        QtCore.QObject.connect(self.createSeq_checkBox, QtCore.SIGNAL("toggled(bool)"), self.start_label.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.prefix_comboBox, self.createSeq_checkBox)
        Dialog.setTabOrder(self.createSeq_checkBox, self.start_spinBox)
        Dialog.setTabOrder(self.start_spinBox, self.suffix_lineEdit)
        Dialog.setTabOrder(self.suffix_lineEdit, self.shotPreview_plainTextEdit)
        Dialog.setTabOrder(self.shotPreview_plainTextEdit, self.shotCreator_buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Shot Creator", None, QtGui.QApplication.UnicodeUTF8))
        self.job_label.setText(QtGui.QApplication.translate("Dialog", "Job:", None, QtGui.QApplication.UnicodeUTF8))
        self.shotNaming_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Shot naming", None, QtGui.QApplication.UnicodeUTF8))
        self.prefix_label.setText(QtGui.QApplication.translate("Dialog", "Prefix:", None, QtGui.QApplication.UnicodeUTF8))
        self.prefix_comboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "SH", None, QtGui.QApplication.UnicodeUTF8))
        self.prefix_comboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "PC", None, QtGui.QApplication.UnicodeUTF8))
        self.start_label.setText(QtGui.QApplication.translate("Dialog", "Numbering start:", None, QtGui.QApplication.UnicodeUTF8))
        self.suffix_label.setText(QtGui.QApplication.translate("Dialog", "Suffix:", None, QtGui.QApplication.UnicodeUTF8))
        self.createSeq_checkBox.setText(QtGui.QApplication.translate("Dialog", "Create sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.shotCount_label.setText(QtGui.QApplication.translate("Dialog", "Number of shots:", None, QtGui.QApplication.UnicodeUTF8))
        self.increment_label.setText(QtGui.QApplication.translate("Dialog", "Increment:", None, QtGui.QApplication.UnicodeUTF8))
        self.shotPreview_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Preview", None, QtGui.QApplication.UnicodeUTF8))

import rsc_rc
