#!/usr/bin/python

# [Icarus] shot_creator__main__.py
#
# Mike Bonnington <mike.bonnington@gps-ldn.com>
# (c) 2016-2017 Gramercy Park Studios
#
# A UI for creating shots.


import os
import sys

# Initialise Icarus environment
# if __name__ == "__main__":
# 	sys.path.append("J:/dev/icarus/core/run")  # Temporary
# 	import env__init__
# 	env__init__.setEnv()

from Qt import QtCompat, QtCore, QtGui, QtWidgets
# import rsc_rc  # Import resource file as generated by pyside-rcc

# Import custom modules
import jobs
import osOps
import settingsData
import verbose


# ----------------------------------------------------------------------------
# Configuration
# ----------------------------------------------------------------------------

# Set window title and object names
WINDOW_TITLE = "Shot Creator"
WINDOW_OBJECT = "shotCreatorUI"

# Set the UI and the stylesheet
UI_FILE = "shot_creator_ui.ui"
STYLESHEET = "style.qss"  # Set to None to use the parent app's stylesheet


# ----------------------------------------------------------------------------
# Main dialog class
# ----------------------------------------------------------------------------

class shotCreatorDialog(QtWidgets.QDialog):
	""" Main dialog class.
	"""
	def __init__(self, parent=None):
		super(shotCreatorDialog, self).__init__(parent)

		# Set object name and window title
		self.setObjectName(WINDOW_OBJECT)
		self.setWindowTitle(WINDOW_TITLE)

		# Load UI & stylesheet
		self.ui = QtCompat.load_ui(fname=os.path.join(os.environ['IC_FORMSDIR'], UI_FILE))
		if STYLESHEET is not None:
			qss=os.path.join(os.environ['IC_FORMSDIR'], STYLESHEET)
			with open(qss, "r") as fh:
				self.ui.setStyleSheet(fh.read())

		# Set window flags
		self.setWindowFlags(QtCore.Qt.Dialog)

		# Connect signals & slots
		self.ui.job_comboBox.currentIndexChanged.connect(self.populateShots)
		self.ui.prefix_comboBox.currentIndexChanged.connect(self.updateShotsPreview)
		self.ui.createSeq_checkBox.stateChanged.connect(self.updateShotsPreview)
		self.ui.start_spinBox.valueChanged.connect(self.updateShotsPreview)
		self.ui.shotCount_spinBox.valueChanged.connect(self.updateShotsPreview)
		self.ui.increment_spinBox.valueChanged.connect(self.updateShotsPreview)
		self.ui.suffix_lineEdit.textChanged.connect(self.updateShotsPreview)

		self.ui.shotCreator_buttonBox.button(QtWidgets.QDialogButtonBox.Apply).clicked.connect(self.createShots)

		# Set input validators
		alphanumeric_validator = QtGui.QRegExpValidator( QtCore.QRegExp(r'[\w]+'), self.ui.suffix_lineEdit)
		self.ui.suffix_lineEdit.setValidator(alphanumeric_validator)

		# Instantiate jobs class and load data
		self.j = jobs.jobs()
		self.sd = settingsData.settingsData()


	def display(self, job=None):
		""" Display the dialog.
		"""
		# self.returnValue = False
		self.job = job

		self.populateJobs(reloadDatabase=False)
		self.populateShots()
		self.updateShotsPreview()

		self.ui.exec_()


	def populateJobs(self, reloadDatabase=True):
		""" Populate the jobs combo box.
		"""
		if reloadDatabase:
			self.j.loadXML(quiet=True)  # Reload XML data

		# Stop the widget from emitting signals
		self.ui.job_comboBox.blockSignals(True)

		# Clear combo box
		self.ui.job_comboBox.clear()

		jobLs = self.j.getActiveJobs()
		if jobLs:
			jobLs = sorted(jobLs, reverse=True)

			for job in jobLs:
				self.ui.job_comboBox.insertItem(0, job)

			# Attempt to set the combo box to the current job
			if self.job in jobLs:
				self.ui.job_comboBox.setCurrentIndex(self.ui.job_comboBox.findText(self.job))
				#self.ui.job_comboBox.setEnabled(False)

			# Set the combo box to the first item
			else:
				self.ui.job_comboBox.setCurrentIndex(0)

		# Re-enable signals
		self.ui.job_comboBox.blockSignals(False)


	def populateShots(self):
		""" Update the text field showing the existing shots.
		"""
		shotLs = self.j.listShots(self.ui.job_comboBox.currentText())
		previewStr = ""
		if shotLs:
			for shotName in shotLs:
				previewStr += shotName + "\n"
		self.ui.shots_plainTextEdit.setPlainText(previewStr)


	def updateShotsPreview(self):
		""" Update the preview field showing the shot directories to be
			created.
		"""
		self.shotLs = []
		previewStr = ""
		index = self.ui.start_spinBox.value()
		if self.ui.createSeq_checkBox.checkState() == QtCore.Qt.Checked:
			count = self.ui.shotCount_spinBox.value()
			step = self.ui.increment_spinBox.value()
			for shot in range(count):
				shotName = self.ui.prefix_comboBox.currentText() + str(index).zfill(3) + self.ui.suffix_lineEdit.text()
				self.shotLs.append(shotName)
				previewStr += shotName + "\n"
				index += step

		else:
			if self.ui.suffix_lineEdit.text():
				shotName = self.ui.prefix_comboBox.currentText() + self.ui.suffix_lineEdit.text()
			else:
				shotName = self.ui.prefix_comboBox.currentText() + str(index).zfill(3)
			self.shotLs.append(shotName)
			previewStr = shotName

		self.ui.shotPreview_plainTextEdit.setPlainText(previewStr)


	def createShots(self):
		""" Create the shot(s).

		"""
		success = 0
		existing = 0
		failure = 0
		createdShots = ""
		existingShots = ""
		failedShots = ""
		dialogMsg = ""

		jobPath = self.j.getPath(self.ui.job_comboBox.currentText(), translate=True)
		for shot in self.shotLs:
			path = osOps.absolutePath("%s/$SHOTSROOTRELATIVEDIR/%s/$DATAFILESRELATIVEDIR" %(jobPath, shot))
			osOps.createDir(path)
			shotData = os.path.join(path, "shotData.xml")
			# sd.createXML()
			# sd.saveXML()
			if self.sd.loadXML(shotData):
				existing += 1
				existingShots += shot + " "
			elif self.sd.saveXML():
				success += 1
				createdShots += shot + " "
			else:
				failure += 1
				failedShots += shot + " "

		if success:
			message = "%d %s created successfully: " %(success, verbose.pluralise('shot', success))
			dialogMsg += "%s\n%s\n\n" %(message, createdShots)
			verbose.message(message + createdShots)

		if existing:
			message = "The following %d shot(s) were not created as they already exist: " %existing
			dialogMsg += "%s\n%s\n\n" %(message, existingShots)
			verbose.warning(message + existingShots)

		if failure:
			message = "The following %d shot(s) could not be created - please check write permissions and try again: " %failure
			dialogMsg += "%s\n%s\n\n" %(message, failedShots)
			verbose.error(message + failedShots)

		# Confirmation dialog
		import pDialog
		dialogTitle = "Shot Creator Results"
		dialog = pDialog.dialog()
		dialog.display(dialogMsg, dialogTitle, conf=True)

		self.populateShots()


	# def exit(self):
	# 	""" Exit the dialog.
	# 	"""
	# 	self.ui.hide()
	# 	self.returnValue = False

# ----------------------------------------------------------------------------
# End of main dialog class
# ----------------------------------------------------------------------------


# ----------------------------------------------------------------------------
# Run as standalone app
# ----------------------------------------------------------------------------

# if __name__ == "__main__":
# 	app = QtWidgets.QApplication(sys.argv)

# 	import rsc_rc

# 	# # Apply UI style sheet
# 	# if STYLESHEET is not None:
# 	# 	qss=os.path.join(os.environ['IC_FORMSDIR'], STYLESHEET)
# 	# 	with open(qss, "r") as fh:
# 	# 		app.setStyleSheet(fh.read())

# 	myApp = shotCreatorDialog()
# 	myApp.display()
# 	sys.exit(app.exec_())

