# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpsPreviewUI.ui'
#
# Created: Wed Dec 10 11:06:44 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 340)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_3.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.jobShot_label = QtGui.QLabel(Dialog)
        self.jobShot_label.setText("")
        self.jobShot_label.setObjectName("jobShot_label")
        self.verticalLayout_3.addWidget(self.jobShot_label)
        self.h_line = QtGui.QFrame(Dialog)
        self.h_line.setFrameShape(QtGui.QFrame.HLine)
        self.h_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_line.setObjectName("h_line")
        self.verticalLayout_3.addWidget(self.h_line)
        self.frame_4 = QtGui.QFrame(Dialog)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.file_label = QtGui.QLabel(self.frame_4)
        self.file_label.setObjectName("file_label")
        self.horizontalLayout_4.addWidget(self.file_label)
        self.file_lineEdit = QtGui.QLineEdit(self.frame_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 125, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 125, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 38, 38))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.file_lineEdit.setPalette(palette)
        self.file_lineEdit.setProperty("mandatoryField", True)
        self.file_lineEdit.setObjectName("file_lineEdit")
        self.horizontalLayout_4.addWidget(self.file_lineEdit)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_3 = QtGui.QFrame(Dialog)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.resolution_groupBox = QtGui.QGroupBox(self.frame_3)
        self.resolution_groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.resolution_groupBox.setFlat(False)
        self.resolution_groupBox.setCheckable(False)
        self.resolution_groupBox.setObjectName("resolution_groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.resolution_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.resolution_comboBox = QtGui.QComboBox(self.resolution_groupBox)
        self.resolution_comboBox.setObjectName("resolution_comboBox")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.verticalLayout.addWidget(self.resolution_comboBox)
        self.frame = QtGui.QFrame(self.resolution_groupBox)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.x_lineEdit = QtGui.QLineEdit(self.frame)
        self.x_lineEdit.setEnabled(False)
        self.x_lineEdit.setText("")
        self.x_lineEdit.setObjectName("x_lineEdit")
        self.horizontalLayout.addWidget(self.x_lineEdit)
        self.x_label = QtGui.QLabel(self.frame)
        self.x_label.setObjectName("x_label")
        self.horizontalLayout.addWidget(self.x_label)
        self.y_lineEdit = QtGui.QLineEdit(self.frame)
        self.y_lineEdit.setEnabled(False)
        self.y_lineEdit.setText("")
        self.y_lineEdit.setObjectName("y_lineEdit")
        self.horizontalLayout.addWidget(self.y_lineEdit)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_3.addWidget(self.resolution_groupBox)
        self.range_groupBox = QtGui.QGroupBox(self.frame_3)
        self.range_groupBox.setObjectName("range_groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.range_groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.range_comboBox = QtGui.QComboBox(self.range_groupBox)
        self.range_comboBox.setObjectName("range_comboBox")
        self.range_comboBox.addItem("")
        self.range_comboBox.addItem("")
        self.range_comboBox.addItem("")
        self.range_comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.range_comboBox)
        self.frame_2 = QtGui.QFrame(self.range_groupBox)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_lineEdit = QtGui.QLineEdit(self.frame_2)
        self.start_lineEdit.setEnabled(False)
        self.start_lineEdit.setText("")
        self.start_lineEdit.setObjectName("start_lineEdit")
        self.horizontalLayout_2.addWidget(self.start_lineEdit)
        self.range_label = QtGui.QLabel(self.frame_2)
        self.range_label.setObjectName("range_label")
        self.horizontalLayout_2.addWidget(self.range_label)
        self.end_lineEdit = QtGui.QLineEdit(self.frame_2)
        self.end_lineEdit.setEnabled(False)
        self.end_lineEdit.setText("")
        self.end_lineEdit.setObjectName("end_lineEdit")
        self.horizontalLayout_2.addWidget(self.end_lineEdit)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout_3.addWidget(self.range_groupBox)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.offscreen_checkBox = QtGui.QCheckBox(self.groupBox)
        self.offscreen_checkBox.setChecked(True)
        self.offscreen_checkBox.setObjectName("offscreen_checkBox")
        self.gridLayout.addWidget(self.offscreen_checkBox, 0, 0, 1, 1)
        self.guides_checkBox = QtGui.QCheckBox(self.groupBox)
        self.guides_checkBox.setChecked(True)
        self.guides_checkBox.setObjectName("guides_checkBox")
        self.gridLayout.addWidget(self.guides_checkBox, 0, 1, 1, 1)
        self.launchViewer_checkBox = QtGui.QCheckBox(self.groupBox)
        self.launchViewer_checkBox.setChecked(True)
        self.launchViewer_checkBox.setObjectName("launchViewer_checkBox")
        self.gridLayout.addWidget(self.launchViewer_checkBox, 0, 2, 1, 1)
        self.noSelection_checkBox = QtGui.QCheckBox(self.groupBox)
        self.noSelection_checkBox.setChecked(True)
        self.noSelection_checkBox.setObjectName("noSelection_checkBox")
        self.gridLayout.addWidget(self.noSelection_checkBox, 1, 0, 1, 1)
        self.slate_checkBox = QtGui.QCheckBox(self.groupBox)
        self.slate_checkBox.setChecked(True)
        self.slate_checkBox.setObjectName("slate_checkBox")
        self.gridLayout.addWidget(self.slate_checkBox, 1, 1, 1, 1)
        self.createQuicktime_checkBox = QtGui.QCheckBox(self.groupBox)
        self.createQuicktime_checkBox.setObjectName("createQuicktime_checkBox")
        self.gridLayout.addWidget(self.createQuicktime_checkBox, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.h_line1 = QtGui.QFrame(Dialog)
        self.h_line1.setFrameShape(QtGui.QFrame.HLine)
        self.h_line1.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_line1.setObjectName("h_line1")
        self.verticalLayout_3.addWidget(self.h_line1)
        self.preview_pushButton = QtGui.QPushButton(Dialog)
        self.preview_pushButton.setObjectName("preview_pushButton")
        self.verticalLayout_3.addWidget(self.preview_pushButton)

        self.retranslateUi(Dialog)
        self.resolution_comboBox.setCurrentIndex(3)
        self.range_comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "GPS - Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.file_label.setText(QtGui.QApplication.translate("Dialog", "File:", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "150%", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "125%", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(2, QtGui.QApplication.translate("Dialog", "110%", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(3, QtGui.QApplication.translate("Dialog", "shot default", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(4, QtGui.QApplication.translate("Dialog", "75%", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(5, QtGui.QApplication.translate("Dialog", "50%", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(6, QtGui.QApplication.translate("Dialog", "25%", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(7, QtGui.QApplication.translate("Dialog", "10%", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(8, QtGui.QApplication.translate("Dialog", "custom", None, QtGui.QApplication.UnicodeUTF8))
        self.x_label.setText(QtGui.QApplication.translate("Dialog", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.range_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Frame Range", None, QtGui.QApplication.UnicodeUTF8))
        self.range_comboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "shot default", None, QtGui.QApplication.UnicodeUTF8))
        self.range_comboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "timeline", None, QtGui.QApplication.UnicodeUTF8))
        self.range_comboBox.setItemText(2, QtGui.QApplication.translate("Dialog", "custom", None, QtGui.QApplication.UnicodeUTF8))
        self.range_comboBox.setItemText(3, QtGui.QApplication.translate("Dialog", "current frame", None, QtGui.QApplication.UnicodeUTF8))
        self.range_label.setText(QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.offscreen_checkBox.setText(QtGui.QApplication.translate("Dialog", "Offscreen", None, QtGui.QApplication.UnicodeUTF8))
        self.guides_checkBox.setText(QtGui.QApplication.translate("Dialog", "Guides", None, QtGui.QApplication.UnicodeUTF8))
        self.launchViewer_checkBox.setText(QtGui.QApplication.translate("Dialog", "Launch Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.noSelection_checkBox.setText(QtGui.QApplication.translate("Dialog", "No Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.slate_checkBox.setText(QtGui.QApplication.translate("Dialog", "Slate", None, QtGui.QApplication.UnicodeUTF8))
        self.createQuicktime_checkBox.setText(QtGui.QApplication.translate("Dialog", "Create QuickTime", None, QtGui.QApplication.UnicodeUTF8))
        self.preview_pushButton.setText(QtGui.QApplication.translate("Dialog", "Preview", None, QtGui.QApplication.UnicodeUTF8))

