# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpsPreviewUI.ui'
#
# Created: Thu Dec 18 13:58:54 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 360)
        self.verticalLayout_4 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_4.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.main_frame = QtGui.QFrame(Dialog)
        self.main_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.main_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.jobShot_label = QtGui.QLabel(self.main_frame)
        self.jobShot_label.setText("")
        self.jobShot_label.setObjectName("jobShot_label")
        self.verticalLayout_3.addWidget(self.jobShot_label)
        self.upper_h_line = QtGui.QFrame(self.main_frame)
        self.upper_h_line.setFrameShape(QtGui.QFrame.HLine)
        self.upper_h_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.upper_h_line.setObjectName("upper_h_line")
        self.verticalLayout_3.addWidget(self.upper_h_line)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.file_horizontalLayout = QtGui.QHBoxLayout()
        self.file_horizontalLayout.setObjectName("file_horizontalLayout")
        self.file_label = QtGui.QLabel(self.main_frame)
        self.file_label.setObjectName("file_label")
        self.file_horizontalLayout.addWidget(self.file_label)
        self.file_lineEdit = QtGui.QLineEdit(self.main_frame)
        self.file_lineEdit.setProperty("mandatoryField", True)
        self.file_lineEdit.setObjectName("file_lineEdit")
        self.file_horizontalLayout.addWidget(self.file_lineEdit)
        self.verticalLayout_3.addLayout(self.file_horizontalLayout)
        self.res_range_horizontalLayout = QtGui.QHBoxLayout()
        self.res_range_horizontalLayout.setObjectName("res_range_horizontalLayout")
        self.resolution_groupBox = QtGui.QGroupBox(self.main_frame)
        self.resolution_groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.resolution_groupBox.setFlat(False)
        self.resolution_groupBox.setCheckable(False)
        self.resolution_groupBox.setObjectName("resolution_groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.resolution_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.resolution_comboBox = QtGui.QComboBox(self.resolution_groupBox)
        self.resolution_comboBox.setObjectName("resolution_comboBox")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.verticalLayout.addWidget(self.resolution_comboBox)
        self.res_horizontalLayout = QtGui.QHBoxLayout()
        self.res_horizontalLayout.setObjectName("res_horizontalLayout")
        self.x_lineEdit = QtGui.QLineEdit(self.resolution_groupBox)
        self.x_lineEdit.setEnabled(False)
        self.x_lineEdit.setText("")
        self.x_lineEdit.setObjectName("x_lineEdit")
        self.res_horizontalLayout.addWidget(self.x_lineEdit)
        self.x_label = QtGui.QLabel(self.resolution_groupBox)
        self.x_label.setObjectName("x_label")
        self.res_horizontalLayout.addWidget(self.x_label)
        self.y_lineEdit = QtGui.QLineEdit(self.resolution_groupBox)
        self.y_lineEdit.setEnabled(False)
        self.y_lineEdit.setText("")
        self.y_lineEdit.setObjectName("y_lineEdit")
        self.res_horizontalLayout.addWidget(self.y_lineEdit)
        self.verticalLayout.addLayout(self.res_horizontalLayout)
        self.res_range_horizontalLayout.addWidget(self.resolution_groupBox)
        self.range_groupBox = QtGui.QGroupBox(self.main_frame)
        self.range_groupBox.setObjectName("range_groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.range_groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.range_comboBox = QtGui.QComboBox(self.range_groupBox)
        self.range_comboBox.setObjectName("range_comboBox")
        self.range_comboBox.addItem("")
        self.range_comboBox.addItem("")
        self.range_comboBox.addItem("")
        self.range_comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.range_comboBox)
        self.range_horizontalLayout = QtGui.QHBoxLayout()
        self.range_horizontalLayout.setObjectName("range_horizontalLayout")
        self.start_lineEdit = QtGui.QLineEdit(self.range_groupBox)
        self.start_lineEdit.setEnabled(False)
        self.start_lineEdit.setText("")
        self.start_lineEdit.setObjectName("start_lineEdit")
        self.range_horizontalLayout.addWidget(self.start_lineEdit)
        self.range_label = QtGui.QLabel(self.range_groupBox)
        self.range_label.setObjectName("range_label")
        self.range_horizontalLayout.addWidget(self.range_label)
        self.end_lineEdit = QtGui.QLineEdit(self.range_groupBox)
        self.end_lineEdit.setEnabled(False)
        self.end_lineEdit.setText("")
        self.end_lineEdit.setObjectName("end_lineEdit")
        self.range_horizontalLayout.addWidget(self.end_lineEdit)
        self.verticalLayout_2.addLayout(self.range_horizontalLayout)
        self.res_range_horizontalLayout.addWidget(self.range_groupBox)
        self.verticalLayout_3.addLayout(self.res_range_horizontalLayout)
        self.options_groupBox = QtGui.QGroupBox(self.main_frame)
        self.options_groupBox.setObjectName("options_groupBox")
        self.gridLayout = QtGui.QGridLayout(self.options_groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.offscreen_checkBox = QtGui.QCheckBox(self.options_groupBox)
        self.offscreen_checkBox.setChecked(True)
        self.offscreen_checkBox.setObjectName("offscreen_checkBox")
        self.gridLayout.addWidget(self.offscreen_checkBox, 0, 0, 1, 1)
        self.guides_checkBox = QtGui.QCheckBox(self.options_groupBox)
        self.guides_checkBox.setChecked(True)
        self.guides_checkBox.setObjectName("guides_checkBox")
        self.gridLayout.addWidget(self.guides_checkBox, 0, 1, 1, 1)
        self.launchViewer_checkBox = QtGui.QCheckBox(self.options_groupBox)
        self.launchViewer_checkBox.setChecked(True)
        self.launchViewer_checkBox.setObjectName("launchViewer_checkBox")
        self.gridLayout.addWidget(self.launchViewer_checkBox, 0, 2, 1, 1)
        self.noSelection_checkBox = QtGui.QCheckBox(self.options_groupBox)
        self.noSelection_checkBox.setChecked(True)
        self.noSelection_checkBox.setObjectName("noSelection_checkBox")
        self.gridLayout.addWidget(self.noSelection_checkBox, 1, 0, 1, 1)
        self.slate_checkBox = QtGui.QCheckBox(self.options_groupBox)
        self.slate_checkBox.setChecked(True)
        self.slate_checkBox.setObjectName("slate_checkBox")
        self.gridLayout.addWidget(self.slate_checkBox, 1, 1, 1, 1)
        self.createQuicktime_checkBox = QtGui.QCheckBox(self.options_groupBox)
        self.createQuicktime_checkBox.setObjectName("createQuicktime_checkBox")
        self.gridLayout.addWidget(self.createQuicktime_checkBox, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.options_groupBox)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.lower_h_line = QtGui.QFrame(self.main_frame)
        self.lower_h_line.setFrameShape(QtGui.QFrame.HLine)
        self.lower_h_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.lower_h_line.setObjectName("lower_h_line")
        self.verticalLayout_3.addWidget(self.lower_h_line)
        self.preview_pushButton = QtGui.QPushButton(self.main_frame)
        self.preview_pushButton.setObjectName("preview_pushButton")
        self.verticalLayout_3.addWidget(self.preview_pushButton)
        self.verticalLayout_4.addWidget(self.main_frame)

        self.retranslateUi(Dialog)
        self.resolution_comboBox.setCurrentIndex(3)
        self.range_comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "GPS - Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.file_label.setText(QtGui.QApplication.translate("Dialog", "File:", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "150%", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "125%", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(2, QtGui.QApplication.translate("Dialog", "110%", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(3, QtGui.QApplication.translate("Dialog", "shot default", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(4, QtGui.QApplication.translate("Dialog", "75%", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(5, QtGui.QApplication.translate("Dialog", "50%", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(6, QtGui.QApplication.translate("Dialog", "25%", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(7, QtGui.QApplication.translate("Dialog", "10%", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(8, QtGui.QApplication.translate("Dialog", "custom", None, QtGui.QApplication.UnicodeUTF8))
        self.x_label.setText(QtGui.QApplication.translate("Dialog", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.range_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Frame Range", None, QtGui.QApplication.UnicodeUTF8))
        self.range_comboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "shot default", None, QtGui.QApplication.UnicodeUTF8))
        self.range_comboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "timeline", None, QtGui.QApplication.UnicodeUTF8))
        self.range_comboBox.setItemText(2, QtGui.QApplication.translate("Dialog", "custom", None, QtGui.QApplication.UnicodeUTF8))
        self.range_comboBox.setItemText(3, QtGui.QApplication.translate("Dialog", "current frame", None, QtGui.QApplication.UnicodeUTF8))
        self.range_label.setText(QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.options_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.offscreen_checkBox.setText(QtGui.QApplication.translate("Dialog", "Offscreen", None, QtGui.QApplication.UnicodeUTF8))
        self.guides_checkBox.setText(QtGui.QApplication.translate("Dialog", "Guides", None, QtGui.QApplication.UnicodeUTF8))
        self.launchViewer_checkBox.setText(QtGui.QApplication.translate("Dialog", "Launch Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.noSelection_checkBox.setText(QtGui.QApplication.translate("Dialog", "No Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.slate_checkBox.setText(QtGui.QApplication.translate("Dialog", "Slate", None, QtGui.QApplication.UnicodeUTF8))
        self.createQuicktime_checkBox.setText(QtGui.QApplication.translate("Dialog", "Create QuickTime", None, QtGui.QApplication.UnicodeUTF8))
        self.preview_pushButton.setText(QtGui.QApplication.translate("Dialog", "Preview", None, QtGui.QApplication.UnicodeUTF8))

