# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rename_ui.ui'
#
# Created: Wed Mar 16 12:32:57 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 320)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rename_tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.rename_tabWidget.setObjectName("rename_tabWidget")
        self.findReplace_tab = QtGui.QWidget()
        self.findReplace_tab.setObjectName("findReplace_tab")
        self.formLayout = QtGui.QFormLayout(self.findReplace_tab)
        self.formLayout.setObjectName("formLayout")
        self.find_label = QtGui.QLabel(self.findReplace_tab)
        self.find_label.setObjectName("find_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.find_label)
        self.find_lineEdit = QtGui.QLineEdit(self.findReplace_tab)
        self.find_lineEdit.setObjectName("find_lineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.find_lineEdit)
        self.replace_lineEdit = QtGui.QLineEdit(self.findReplace_tab)
        self.replace_lineEdit.setObjectName("replace_lineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.replace_lineEdit)
        self.replace_label = QtGui.QLabel(self.findReplace_tab)
        self.replace_label.setObjectName("replace_label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.replace_label)
        self.ignoreCase_checkBox = QtGui.QCheckBox(self.findReplace_tab)
        self.ignoreCase_checkBox.setObjectName("ignoreCase_checkBox")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.ignoreCase_checkBox)
        self.rename_tabWidget.addTab(self.findReplace_tab, "")
        self.renumber_tab = QtGui.QWidget()
        self.renumber_tab.setObjectName("renumber_tab")
        self.formLayout_2 = QtGui.QFormLayout(self.renumber_tab)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.startFrom_label = QtGui.QLabel(self.renumber_tab)
        self.startFrom_label.setEnabled(False)
        self.startFrom_label.setObjectName("startFrom_label")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.startFrom_label)
        self.step_label = QtGui.QLabel(self.renumber_tab)
        self.step_label.setEnabled(False)
        self.step_label.setObjectName("step_label")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.step_label)
        self.padding_label = QtGui.QLabel(self.renumber_tab)
        self.padding_label.setEnabled(False)
        self.padding_label.setObjectName("padding_label")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.padding_label)
        self.startFrom_spinBox = QtGui.QSpinBox(self.renumber_tab)
        self.startFrom_spinBox.setEnabled(False)
        self.startFrom_spinBox.setMaximum(999999999)
        self.startFrom_spinBox.setProperty("value", 1)
        self.startFrom_spinBox.setObjectName("startFrom_spinBox")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.startFrom_spinBox)
        self.step_spinBox = QtGui.QSpinBox(self.renumber_tab)
        self.step_spinBox.setEnabled(False)
        self.step_spinBox.setMinimum(1)
        self.step_spinBox.setMaximum(999999999)
        self.step_spinBox.setProperty("value", 1)
        self.step_spinBox.setObjectName("step_spinBox")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.step_spinBox)
        self.padding_spinBox = QtGui.QSpinBox(self.renumber_tab)
        self.padding_spinBox.setEnabled(False)
        self.padding_spinBox.setMinimum(1)
        self.padding_spinBox.setMaximum(16)
        self.padding_spinBox.setProperty("value", 4)
        self.padding_spinBox.setObjectName("padding_spinBox")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.padding_spinBox)
        self.preserveNumbering_checkBox = QtGui.QCheckBox(self.renumber_tab)
        self.preserveNumbering_checkBox.setChecked(True)
        self.preserveNumbering_checkBox.setObjectName("preserveNumbering_checkBox")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.preserveNumbering_checkBox)
        self.autoPadding_checkBox = QtGui.QCheckBox(self.renumber_tab)
        self.autoPadding_checkBox.setChecked(True)
        self.autoPadding_checkBox.setObjectName("autoPadding_checkBox")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.autoPadding_checkBox)
        self.rename_tabWidget.addTab(self.renumber_tab, "")
        self.verticalLayout.addWidget(self.rename_tabWidget)
        self.renderPbl_treeWidget = QtGui.QTreeWidget(self.centralwidget)
        self.renderPbl_treeWidget.setAlternatingRowColors(True)
        self.renderPbl_treeWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.renderPbl_treeWidget.setUniformRowHeights(False)
        self.renderPbl_treeWidget.setAnimated(True)
        self.renderPbl_treeWidget.setHeaderHidden(False)
        self.renderPbl_treeWidget.setExpandsOnDoubleClick(False)
        self.renderPbl_treeWidget.setObjectName("renderPbl_treeWidget")
        self.verticalLayout.addWidget(self.renderPbl_treeWidget)
        self.renameToolbar_frame = QtGui.QFrame(self.centralwidget)
        self.renameToolbar_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.renameToolbar_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.renameToolbar_frame.setObjectName("renameToolbar_frame")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.renameToolbar_frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.preview_pushButton = QtGui.QPushButton(self.renameToolbar_frame)
        self.preview_pushButton.setDefault(False)
        self.preview_pushButton.setFlat(False)
        self.preview_pushButton.setObjectName("preview_pushButton")
        self.horizontalLayout_10.addWidget(self.preview_pushButton)
        self.rename_pushButton = QtGui.QPushButton(self.renameToolbar_frame)
        self.rename_pushButton.setDefault(False)
        self.rename_pushButton.setFlat(False)
        self.rename_pushButton.setObjectName("rename_pushButton")
        self.horizontalLayout_10.addWidget(self.rename_pushButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.close_pushButton = QtGui.QPushButton(self.renameToolbar_frame)
        self.close_pushButton.setObjectName("close_pushButton")
        self.horizontalLayout_10.addWidget(self.close_pushButton)
        self.verticalLayout.addWidget(self.renameToolbar_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.rename_tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.preserveNumbering_checkBox, QtCore.SIGNAL("toggled(bool)"), self.startFrom_label.setDisabled)
        QtCore.QObject.connect(self.preserveNumbering_checkBox, QtCore.SIGNAL("toggled(bool)"), self.startFrom_spinBox.setDisabled)
        QtCore.QObject.connect(self.preserveNumbering_checkBox, QtCore.SIGNAL("toggled(bool)"), self.step_label.setDisabled)
        QtCore.QObject.connect(self.preserveNumbering_checkBox, QtCore.SIGNAL("toggled(bool)"), self.step_spinBox.setDisabled)
        QtCore.QObject.connect(self.autoPadding_checkBox, QtCore.SIGNAL("toggled(bool)"), self.padding_label.setDisabled)
        QtCore.QObject.connect(self.autoPadding_checkBox, QtCore.SIGNAL("toggled(bool)"), self.padding_spinBox.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.rename_tabWidget, self.find_lineEdit)
        MainWindow.setTabOrder(self.find_lineEdit, self.replace_lineEdit)
        MainWindow.setTabOrder(self.replace_lineEdit, self.ignoreCase_checkBox)
        MainWindow.setTabOrder(self.ignoreCase_checkBox, self.preserveNumbering_checkBox)
        MainWindow.setTabOrder(self.preserveNumbering_checkBox, self.startFrom_spinBox)
        MainWindow.setTabOrder(self.startFrom_spinBox, self.step_spinBox)
        MainWindow.setTabOrder(self.step_spinBox, self.autoPadding_checkBox)
        MainWindow.setTabOrder(self.autoPadding_checkBox, self.padding_spinBox)
        MainWindow.setTabOrder(self.padding_spinBox, self.renderPbl_treeWidget)
        MainWindow.setTabOrder(self.renderPbl_treeWidget, self.preview_pushButton)
        MainWindow.setTabOrder(self.preview_pushButton, self.rename_pushButton)
        MainWindow.setTabOrder(self.rename_pushButton, self.close_pushButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Batch Rename", None, QtGui.QApplication.UnicodeUTF8))
        self.find_label.setText(QtGui.QApplication.translate("MainWindow", "Find:", None, QtGui.QApplication.UnicodeUTF8))
        self.replace_label.setText(QtGui.QApplication.translate("MainWindow", "Replace:", None, QtGui.QApplication.UnicodeUTF8))
        self.ignoreCase_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Ignore case", None, QtGui.QApplication.UnicodeUTF8))
        self.rename_tabWidget.setTabText(self.rename_tabWidget.indexOf(self.findReplace_tab), QtGui.QApplication.translate("MainWindow", "Find and Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.startFrom_label.setText(QtGui.QApplication.translate("MainWindow", "Start from:", None, QtGui.QApplication.UnicodeUTF8))
        self.step_label.setText(QtGui.QApplication.translate("MainWindow", "Step:", None, QtGui.QApplication.UnicodeUTF8))
        self.padding_label.setText(QtGui.QApplication.translate("MainWindow", "Padding:", None, QtGui.QApplication.UnicodeUTF8))
        self.preserveNumbering_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Preserve current numbering", None, QtGui.QApplication.UnicodeUTF8))
        self.autoPadding_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Auto padding", None, QtGui.QApplication.UnicodeUTF8))
        self.rename_tabWidget.setTabText(self.rename_tabWidget.indexOf(self.renumber_tab), QtGui.QApplication.translate("MainWindow", "Renumber", None, QtGui.QApplication.UnicodeUTF8))
        self.renderPbl_treeWidget.setSortingEnabled(False)
        self.renderPbl_treeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Layer / Pass", None, QtGui.QApplication.UnicodeUTF8))
        self.renderPbl_treeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Frames", None, QtGui.QApplication.UnicodeUTF8))
        self.renderPbl_treeWidget.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.renderPbl_treeWidget.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.preview_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.rename_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Rename", None, QtGui.QApplication.UnicodeUTF8))
        self.close_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))

