# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rename_ui.ui'
#
# Created: Thu Mar 17 10:30:04 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 480)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rename_tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rename_tabWidget.sizePolicy().hasHeightForWidth())
        self.rename_tabWidget.setSizePolicy(sizePolicy)
        self.rename_tabWidget.setObjectName("rename_tabWidget")
        self.findReplace_tab = QtGui.QWidget()
        self.findReplace_tab.setObjectName("findReplace_tab")
        self.formLayout = QtGui.QFormLayout(self.findReplace_tab)
        self.formLayout.setObjectName("formLayout")
        self.find_label = QtGui.QLabel(self.findReplace_tab)
        self.find_label.setObjectName("find_label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.find_label)
        self.replace_label = QtGui.QLabel(self.findReplace_tab)
        self.replace_label.setObjectName("replace_label")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.replace_label)
        self.ignoreCase_checkBox = QtGui.QCheckBox(self.findReplace_tab)
        self.ignoreCase_checkBox.setObjectName("ignoreCase_checkBox")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.ignoreCase_checkBox)
        self.find_horizontalLayout = QtGui.QHBoxLayout()
        self.find_horizontalLayout.setObjectName("find_horizontalLayout")
        self.find_lineEdit = QtGui.QLineEdit(self.findReplace_tab)
        self.find_lineEdit.setObjectName("find_lineEdit")
        self.find_horizontalLayout.addWidget(self.find_lineEdit)
        self.regex_checkBox = QtGui.QCheckBox(self.findReplace_tab)
        self.regex_checkBox.setObjectName("regex_checkBox")
        self.find_horizontalLayout.addWidget(self.regex_checkBox)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.find_horizontalLayout)
        self.replace_horizontalLayout = QtGui.QHBoxLayout()
        self.replace_horizontalLayout.setObjectName("replace_horizontalLayout")
        self.replace_lineEdit = QtGui.QLineEdit(self.findReplace_tab)
        self.replace_lineEdit.setObjectName("replace_lineEdit")
        self.replace_horizontalLayout.addWidget(self.replace_lineEdit)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.replace_horizontalLayout)
        self.rename_tabWidget.addTab(self.findReplace_tab, "")
        self.renumber_tab = QtGui.QWidget()
        self.renumber_tab.setObjectName("renumber_tab")
        self.formLayout_2 = QtGui.QFormLayout(self.renumber_tab)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.start_label = QtGui.QLabel(self.renumber_tab)
        self.start_label.setEnabled(False)
        self.start_label.setObjectName("start_label")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.start_label)
        self.step_label = QtGui.QLabel(self.renumber_tab)
        self.step_label.setEnabled(False)
        self.step_label.setObjectName("step_label")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.step_label)
        self.padding_label = QtGui.QLabel(self.renumber_tab)
        self.padding_label.setEnabled(False)
        self.padding_label.setObjectName("padding_label")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.padding_label)
        self.start_spinBox = QtGui.QSpinBox(self.renumber_tab)
        self.start_spinBox.setEnabled(False)
        self.start_spinBox.setMaximum(999999999)
        self.start_spinBox.setProperty("value", 1)
        self.start_spinBox.setObjectName("start_spinBox")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.start_spinBox)
        self.step_spinBox = QtGui.QSpinBox(self.renumber_tab)
        self.step_spinBox.setEnabled(False)
        self.step_spinBox.setMinimum(1)
        self.step_spinBox.setMaximum(999999999)
        self.step_spinBox.setProperty("value", 1)
        self.step_spinBox.setObjectName("step_spinBox")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.step_spinBox)
        self.padding_spinBox = QtGui.QSpinBox(self.renumber_tab)
        self.padding_spinBox.setEnabled(False)
        self.padding_spinBox.setMinimum(1)
        self.padding_spinBox.setMaximum(16)
        self.padding_spinBox.setProperty("value", 4)
        self.padding_spinBox.setObjectName("padding_spinBox")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.padding_spinBox)
        self.preserveNumbering_checkBox = QtGui.QCheckBox(self.renumber_tab)
        self.preserveNumbering_checkBox.setChecked(True)
        self.preserveNumbering_checkBox.setObjectName("preserveNumbering_checkBox")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.preserveNumbering_checkBox)
        self.autoPadding_checkBox = QtGui.QCheckBox(self.renumber_tab)
        self.autoPadding_checkBox.setChecked(True)
        self.autoPadding_checkBox.setObjectName("autoPadding_checkBox")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.autoPadding_checkBox)
        self.rename_tabWidget.addTab(self.renumber_tab, "")
        self.verticalLayout.addWidget(self.rename_tabWidget)
        self.dir_horizontalLayout = QtGui.QHBoxLayout()
        self.dir_horizontalLayout.setObjectName("dir_horizontalLayout")
        self.dir_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.dir_lineEdit.setProperty("mandatoryField", False)
        self.dir_lineEdit.setObjectName("dir_lineEdit")
        self.dir_horizontalLayout.addWidget(self.dir_lineEdit)
        self.dirBrowse_toolButton = QtGui.QToolButton(self.centralwidget)
        self.dirBrowse_toolButton.setObjectName("dirBrowse_toolButton")
        self.dir_horizontalLayout.addWidget(self.dirBrowse_toolButton)
        self.verticalLayout.addLayout(self.dir_horizontalLayout)
        self.selection_treeWidget = QtGui.QTreeWidget(self.centralwidget)
        self.selection_treeWidget.setAlternatingRowColors(True)
        self.selection_treeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.selection_treeWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.selection_treeWidget.setUniformRowHeights(False)
        self.selection_treeWidget.setItemsExpandable(False)
        self.selection_treeWidget.setAnimated(True)
        self.selection_treeWidget.setHeaderHidden(False)
        self.selection_treeWidget.setExpandsOnDoubleClick(False)
        self.selection_treeWidget.setObjectName("selection_treeWidget")
        self.selection_treeWidget.header().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.selection_treeWidget)
        self.renameToolbar_frame = QtGui.QFrame(self.centralwidget)
        self.renameToolbar_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.renameToolbar_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.renameToolbar_frame.setObjectName("renameToolbar_frame")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.renameToolbar_frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.add_pushButton = QtGui.QPushButton(self.renameToolbar_frame)
        self.add_pushButton.setDefault(False)
        self.add_pushButton.setFlat(False)
        self.add_pushButton.setObjectName("add_pushButton")
        self.horizontalLayout_10.addWidget(self.add_pushButton)
        self.remove_pushButton = QtGui.QPushButton(self.renameToolbar_frame)
        self.remove_pushButton.setDefault(False)
        self.remove_pushButton.setFlat(False)
        self.remove_pushButton.setObjectName("remove_pushButton")
        self.horizontalLayout_10.addWidget(self.remove_pushButton)
        self.preview_pushButton = QtGui.QPushButton(self.renameToolbar_frame)
        self.preview_pushButton.setDefault(False)
        self.preview_pushButton.setFlat(False)
        self.preview_pushButton.setObjectName("preview_pushButton")
        self.horizontalLayout_10.addWidget(self.preview_pushButton)
        self.rename_pushButton = QtGui.QPushButton(self.renameToolbar_frame)
        self.rename_pushButton.setDefault(False)
        self.rename_pushButton.setFlat(False)
        self.rename_pushButton.setObjectName("rename_pushButton")
        self.horizontalLayout_10.addWidget(self.rename_pushButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.close_pushButton = QtGui.QPushButton(self.renameToolbar_frame)
        self.close_pushButton.setObjectName("close_pushButton")
        self.horizontalLayout_10.addWidget(self.close_pushButton)
        self.verticalLayout.addWidget(self.renameToolbar_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.rename_tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.preserveNumbering_checkBox, QtCore.SIGNAL("toggled(bool)"), self.start_label.setDisabled)
        QtCore.QObject.connect(self.preserveNumbering_checkBox, QtCore.SIGNAL("toggled(bool)"), self.start_spinBox.setDisabled)
        QtCore.QObject.connect(self.preserveNumbering_checkBox, QtCore.SIGNAL("toggled(bool)"), self.step_label.setDisabled)
        QtCore.QObject.connect(self.preserveNumbering_checkBox, QtCore.SIGNAL("toggled(bool)"), self.step_spinBox.setDisabled)
        QtCore.QObject.connect(self.autoPadding_checkBox, QtCore.SIGNAL("toggled(bool)"), self.padding_label.setDisabled)
        QtCore.QObject.connect(self.autoPadding_checkBox, QtCore.SIGNAL("toggled(bool)"), self.padding_spinBox.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.rename_tabWidget, self.preserveNumbering_checkBox)
        MainWindow.setTabOrder(self.preserveNumbering_checkBox, self.start_spinBox)
        MainWindow.setTabOrder(self.start_spinBox, self.step_spinBox)
        MainWindow.setTabOrder(self.step_spinBox, self.autoPadding_checkBox)
        MainWindow.setTabOrder(self.autoPadding_checkBox, self.padding_spinBox)
        MainWindow.setTabOrder(self.padding_spinBox, self.selection_treeWidget)
        MainWindow.setTabOrder(self.selection_treeWidget, self.preview_pushButton)
        MainWindow.setTabOrder(self.preview_pushButton, self.rename_pushButton)
        MainWindow.setTabOrder(self.rename_pushButton, self.close_pushButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Batch Rename", None, QtGui.QApplication.UnicodeUTF8))
        self.find_label.setText(QtGui.QApplication.translate("MainWindow", "Find:", None, QtGui.QApplication.UnicodeUTF8))
        self.replace_label.setText(QtGui.QApplication.translate("MainWindow", "Replace:", None, QtGui.QApplication.UnicodeUTF8))
        self.ignoreCase_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Ignore case", None, QtGui.QApplication.UnicodeUTF8))
        self.regex_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Regular expression", None, QtGui.QApplication.UnicodeUTF8))
        self.rename_tabWidget.setTabText(self.rename_tabWidget.indexOf(self.findReplace_tab), QtGui.QApplication.translate("MainWindow", "Find and Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.start_label.setText(QtGui.QApplication.translate("MainWindow", "Start from:", None, QtGui.QApplication.UnicodeUTF8))
        self.step_label.setText(QtGui.QApplication.translate("MainWindow", "Step:", None, QtGui.QApplication.UnicodeUTF8))
        self.padding_label.setText(QtGui.QApplication.translate("MainWindow", "Padding:", None, QtGui.QApplication.UnicodeUTF8))
        self.preserveNumbering_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Preserve current numbering", None, QtGui.QApplication.UnicodeUTF8))
        self.autoPadding_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Auto padding", None, QtGui.QApplication.UnicodeUTF8))
        self.rename_tabWidget.setTabText(self.rename_tabWidget.indexOf(self.renumber_tab), QtGui.QApplication.translate("MainWindow", "Renumber", None, QtGui.QApplication.UnicodeUTF8))
        self.dirBrowse_toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.selection_treeWidget.setSortingEnabled(False)
        self.selection_treeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Count", None, QtGui.QApplication.UnicodeUTF8))
        self.selection_treeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Before", None, QtGui.QApplication.UnicodeUTF8))
        self.selection_treeWidget.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "After", None, QtGui.QApplication.UnicodeUTF8))
        self.add_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.preview_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.rename_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Rename", None, QtGui.QApplication.UnicodeUTF8))
        self.close_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))

