# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'icadminUI.ui'
#
# Created: Fri Mar 13 15:33:13 2015
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(768, 576)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtGui.QWidget(MainWindow)
        font = QtGui.QFont()
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.jobs_tab = QtGui.QWidget()
        self.jobs_tab.setEnabled(True)
        self.jobs_tab.setObjectName("jobs_tab")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.jobs_tab)
        self.horizontalLayout_8.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.jobList_frame = QtGui.QFrame(self.jobs_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jobList_frame.sizePolicy().hasHeightForWidth())
        self.jobList_frame.setSizePolicy(sizePolicy)
        self.jobList_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.jobList_frame.setObjectName("jobList_frame")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.jobList_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.jobs_listWidget = QtGui.QListWidget(self.jobList_frame)
        self.jobs_listWidget.setAlternatingRowColors(True)
        self.jobs_listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.jobs_listWidget.setObjectName("jobs_listWidget")
        item = QtGui.QListWidgetItem(self.jobs_listWidget)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate)
        item.setCheckState(QtCore.Qt.PartiallyChecked)
        self.verticalLayout_5.addWidget(self.jobs_listWidget)
        self.jobButtons_horizontalLayout = QtGui.QHBoxLayout()
        self.jobButtons_horizontalLayout.setObjectName("jobButtons_horizontalLayout")
        self.jobAdd_toolButton = QtGui.QToolButton(self.jobList_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jobAdd_toolButton.sizePolicy().hasHeightForWidth())
        self.jobAdd_toolButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_add_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.jobAdd_toolButton.setIcon(icon)
        self.jobAdd_toolButton.setIconSize(QtCore.QSize(32, 32))
        self.jobAdd_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.jobAdd_toolButton.setObjectName("jobAdd_toolButton")
        self.jobButtons_horizontalLayout.addWidget(self.jobAdd_toolButton)
        self.jobDelete_toolButton = QtGui.QToolButton(self.jobList_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jobDelete_toolButton.sizePolicy().hasHeightForWidth())
        self.jobDelete_toolButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_delete_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.jobDelete_toolButton.setIcon(icon1)
        self.jobDelete_toolButton.setIconSize(QtCore.QSize(32, 32))
        self.jobDelete_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.jobDelete_toolButton.setObjectName("jobDelete_toolButton")
        self.jobButtons_horizontalLayout.addWidget(self.jobDelete_toolButton)
        self.verticalLayout_5.addLayout(self.jobButtons_horizontalLayout)
        self.horizontalLayout_8.addWidget(self.jobList_frame)
        self.jobProperties_scrollArea = QtGui.QScrollArea(self.jobs_tab)
        self.jobProperties_scrollArea.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jobProperties_scrollArea.sizePolicy().hasHeightForWidth())
        self.jobProperties_scrollArea.setSizePolicy(sizePolicy)
        self.jobProperties_scrollArea.setStyleSheet("")
        self.jobProperties_scrollArea.setWidgetResizable(True)
        self.jobProperties_scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.jobProperties_scrollArea.setProperty("noBackground", True)
        self.jobProperties_scrollArea.setObjectName("jobProperties_scrollArea")
        self.jobProperties_scrollAreaWidgetContents = QtGui.QWidget()
        self.jobProperties_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -133, 447, 719))
        self.jobProperties_scrollAreaWidgetContents.setObjectName("jobProperties_scrollAreaWidgetContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.jobProperties_scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.jobSettings_groupBox = QtGui.QGroupBox(self.jobProperties_scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jobSettings_groupBox.sizePolicy().hasHeightForWidth())
        self.jobSettings_groupBox.setSizePolicy(sizePolicy)
        self.jobSettings_groupBox.setObjectName("jobSettings_groupBox")
        self.formLayout_5 = QtGui.QFormLayout(self.jobSettings_groupBox)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.jobActive_checkBox = QtGui.QCheckBox(self.jobSettings_groupBox)
        self.jobActive_checkBox.setChecked(True)
        self.jobActive_checkBox.setObjectName("jobActive_checkBox")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.jobActive_checkBox)
        self.jobNumber_label = QtGui.QLabel(self.jobSettings_groupBox)
        self.jobNumber_label.setObjectName("jobNumber_label")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.jobNumber_label)
        self.jobPath_label = QtGui.QLabel(self.jobSettings_groupBox)
        self.jobPath_label.setObjectName("jobPath_label")
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.jobPath_label)
        self.jobPath_horizontalLayout = QtGui.QHBoxLayout()
        self.jobPath_horizontalLayout.setObjectName("jobPath_horizontalLayout")
        self.jobPath_lineEdit = QtGui.QLineEdit(self.jobSettings_groupBox)
        self.jobPath_lineEdit.setObjectName("jobPath_lineEdit")
        self.jobPath_horizontalLayout.addWidget(self.jobPath_lineEdit)
        self.jobPathBrowse_toolButton = QtGui.QToolButton(self.jobSettings_groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_folder_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.jobPathBrowse_toolButton.setIcon(icon2)
        self.jobPathBrowse_toolButton.setIconSize(QtCore.QSize(15, 15))
        self.jobPathBrowse_toolButton.setObjectName("jobPathBrowse_toolButton")
        self.jobPath_horizontalLayout.addWidget(self.jobPathBrowse_toolButton)
        self.formLayout_5.setLayout(3, QtGui.QFormLayout.FieldRole, self.jobPath_horizontalLayout)
        self.jobName_label = QtGui.QLabel(self.jobSettings_groupBox)
        self.jobName_label.setObjectName("jobName_label")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.jobName_label)
        self.jobName_lineEdit = QtGui.QLineEdit(self.jobSettings_groupBox)
        self.jobName_lineEdit.setObjectName("jobName_lineEdit")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.jobName_lineEdit)
        self.jobNumber_lineEdit = QtGui.QLineEdit(self.jobSettings_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jobNumber_lineEdit.sizePolicy().hasHeightForWidth())
        self.jobNumber_lineEdit.setSizePolicy(sizePolicy)
        self.jobNumber_lineEdit.setMaxLength(6)
        self.jobNumber_lineEdit.setObjectName("jobNumber_lineEdit")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.jobNumber_lineEdit)
        self.verticalLayout_4.addWidget(self.jobSettings_groupBox)
        self.time_groupBox = QtGui.QGroupBox(self.jobProperties_scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_groupBox.sizePolicy().hasHeightForWidth())
        self.time_groupBox.setSizePolicy(sizePolicy)
        self.time_groupBox.setObjectName("time_groupBox")
        self.formLayout_4 = QtGui.QFormLayout(self.time_groupBox)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.fps_label = QtGui.QLabel(self.time_groupBox)
        self.fps_label.setObjectName("fps_label")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.fps_label)
        self.fps_spinBox = QtGui.QSpinBox(self.time_groupBox)
        self.fps_spinBox.setMinimum(1)
        self.fps_spinBox.setMaximum(5000)
        self.fps_spinBox.setProperty("value", 25)
        self.fps_spinBox.setObjectName("fps_spinBox")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.fps_spinBox)
        self.range_label = QtGui.QLabel(self.time_groupBox)
        self.range_label.setEnabled(False)
        self.range_label.setObjectName("range_label")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.range_label)
        self.range_horizontalLayout = QtGui.QHBoxLayout()
        self.range_horizontalLayout.setObjectName("range_horizontalLayout")
        self.in_spinBox = QtGui.QSpinBox(self.time_groupBox)
        self.in_spinBox.setEnabled(False)
        self.in_spinBox.setMinimum(1)
        self.in_spinBox.setMaximum(9999)
        self.in_spinBox.setProperty("value", 1001)
        self.in_spinBox.setObjectName("in_spinBox")
        self.range_horizontalLayout.addWidget(self.in_spinBox)
        self.rangeSep_label = QtGui.QLabel(self.time_groupBox)
        self.rangeSep_label.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangeSep_label.sizePolicy().hasHeightForWidth())
        self.rangeSep_label.setSizePolicy(sizePolicy)
        self.rangeSep_label.setObjectName("rangeSep_label")
        self.range_horizontalLayout.addWidget(self.rangeSep_label)
        self.out_spinBox = QtGui.QSpinBox(self.time_groupBox)
        self.out_spinBox.setEnabled(False)
        self.out_spinBox.setMinimum(1)
        self.out_spinBox.setMaximum(9999)
        self.out_spinBox.setProperty("value", 1100)
        self.out_spinBox.setObjectName("out_spinBox")
        self.range_horizontalLayout.addWidget(self.out_spinBox)
        self.formLayout_4.setLayout(1, QtGui.QFormLayout.FieldRole, self.range_horizontalLayout)
        self.handles_label = QtGui.QLabel(self.time_groupBox)
        self.handles_label.setObjectName("handles_label")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.handles_label)
        self.handles_spinBox = QtGui.QSpinBox(self.time_groupBox)
        self.handles_spinBox.setMaximum(9999)
        self.handles_spinBox.setProperty("value", 10)
        self.handles_spinBox.setObjectName("handles_spinBox")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.handles_spinBox)
        self.verticalLayout_4.addWidget(self.time_groupBox)
        self.res_groupBox = QtGui.QGroupBox(self.jobProperties_scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.res_groupBox.sizePolicy().hasHeightForWidth())
        self.res_groupBox.setSizePolicy(sizePolicy)
        self.res_groupBox.setObjectName("res_groupBox")
        self.formLayout_6 = QtGui.QFormLayout(self.res_groupBox)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_6.setObjectName("formLayout_6")
        self.resPreset_label = QtGui.QLabel(self.res_groupBox)
        self.resPreset_label.setObjectName("resPreset_label")
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.resPreset_label)
        self.res_label = QtGui.QLabel(self.res_groupBox)
        self.res_label.setObjectName("res_label")
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.res_label)
        self.res_horizontalLayout = QtGui.QHBoxLayout()
        self.res_horizontalLayout.setObjectName("res_horizontalLayout")
        self.resX_spinBox = QtGui.QSpinBox(self.res_groupBox)
        self.resX_spinBox.setMinimum(1)
        self.resX_spinBox.setMaximum(99999)
        self.resX_spinBox.setProperty("value", 1920)
        self.resX_spinBox.setObjectName("resX_spinBox")
        self.res_horizontalLayout.addWidget(self.resX_spinBox)
        self.resSep_label = QtGui.QLabel(self.res_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resSep_label.sizePolicy().hasHeightForWidth())
        self.resSep_label.setSizePolicy(sizePolicy)
        self.resSep_label.setObjectName("resSep_label")
        self.res_horizontalLayout.addWidget(self.resSep_label)
        self.resY_spinBox = QtGui.QSpinBox(self.res_groupBox)
        self.resY_spinBox.setMinimum(1)
        self.resY_spinBox.setMaximum(99999)
        self.resY_spinBox.setProperty("value", 1080)
        self.resY_spinBox.setObjectName("resY_spinBox")
        self.res_horizontalLayout.addWidget(self.resY_spinBox)
        self.formLayout_6.setLayout(2, QtGui.QFormLayout.FieldRole, self.res_horizontalLayout)
        self.label = QtGui.QLabel(self.res_groupBox)
        self.label.setObjectName("label")
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.LabelRole, self.label)
        self.resPreset_comboBox = QtGui.QComboBox(self.res_groupBox)
        self.resPreset_comboBox.setObjectName("resPreset_comboBox")
        self.resPreset_comboBox.addItem("")
        self.resPreset_comboBox.addItem("")
        self.resPreset_comboBox.addItem("")
        self.resPreset_comboBox.addItem("")
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.resPreset_comboBox)
        self.label_2 = QtGui.QLabel(self.res_groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_2 = QtGui.QRadioButton(self.res_groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.radioButton = QtGui.QRadioButton(self.res_groupBox)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.formLayout_6.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.res_horizontalLayout_3 = QtGui.QHBoxLayout()
        self.res_horizontalLayout_3.setObjectName("res_horizontalLayout_3")
        self.resX_spinBox_3 = QtGui.QSpinBox(self.res_groupBox)
        self.resX_spinBox_3.setMinimum(1)
        self.resX_spinBox_3.setMaximum(99999)
        self.resX_spinBox_3.setProperty("value", 1920)
        self.resX_spinBox_3.setObjectName("resX_spinBox_3")
        self.res_horizontalLayout_3.addWidget(self.resX_spinBox_3)
        self.resSep_label_3 = QtGui.QLabel(self.res_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resSep_label_3.sizePolicy().hasHeightForWidth())
        self.resSep_label_3.setSizePolicy(sizePolicy)
        self.resSep_label_3.setObjectName("resSep_label_3")
        self.res_horizontalLayout_3.addWidget(self.resSep_label_3)
        self.resY_spinBox_3 = QtGui.QSpinBox(self.res_groupBox)
        self.resY_spinBox_3.setMinimum(1)
        self.resY_spinBox_3.setMaximum(99999)
        self.resY_spinBox_3.setProperty("value", 1080)
        self.resY_spinBox_3.setObjectName("resY_spinBox_3")
        self.res_horizontalLayout_3.addWidget(self.resY_spinBox_3)
        self.formLayout_6.setLayout(5, QtGui.QFormLayout.FieldRole, self.res_horizontalLayout_3)
        self.label_3 = QtGui.QLabel(self.res_groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.res_groupBox)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setProperty("value", 0.5)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox)
        self.horizontalSlider = QtGui.QSlider(self.res_groupBox)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setSliderPosition(50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_3.addWidget(self.horizontalSlider)
        self.formLayout_6.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.preserveAR_checkBox = QtGui.QCheckBox(self.res_groupBox)
        self.preserveAR_checkBox.setChecked(True)
        self.preserveAR_checkBox.setObjectName("preserveAR_checkBox")
        self.formLayout_6.setWidget(6, QtGui.QFormLayout.FieldRole, self.preserveAR_checkBox)
        self.verticalLayout_4.addWidget(self.res_groupBox)
        self.appPaths_groupBox = QtGui.QGroupBox(self.jobProperties_scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appPaths_groupBox.sizePolicy().hasHeightForWidth())
        self.appPaths_groupBox.setSizePolicy(sizePolicy)
        self.appPaths_groupBox.setObjectName("appPaths_groupBox")
        self.formLayout_3 = QtGui.QFormLayout(self.appPaths_groupBox)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.app_label = QtGui.QLabel(self.appPaths_groupBox)
        self.app_label.setObjectName("app_label")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.app_label)
        self.app_comboBox = QtGui.QComboBox(self.appPaths_groupBox)
        self.app_comboBox.setObjectName("app_comboBox")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.app_comboBox)
        self.os_label = QtGui.QLabel(self.appPaths_groupBox)
        self.os_label.setObjectName("os_label")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.os_label)
        self.os_comboBox = QtGui.QComboBox(self.appPaths_groupBox)
        self.os_comboBox.setObjectName("os_comboBox")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.os_comboBox)
        self.verticalLayout_4.addWidget(self.appPaths_groupBox)
        self.other_groupBox = QtGui.QGroupBox(self.jobProperties_scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.other_groupBox.sizePolicy().hasHeightForWidth())
        self.other_groupBox.setSizePolicy(sizePolicy)
        self.other_groupBox.setObjectName("other_groupBox")
        self.formLayout_7 = QtGui.QFormLayout(self.other_groupBox)
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_7.setObjectName("formLayout_7")
        self.board_label = QtGui.QLabel(self.other_groupBox)
        self.board_label.setObjectName("board_label")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.board_label)
        self.board_lineEdit = QtGui.QLineEdit(self.other_groupBox)
        self.board_lineEdit.setObjectName("board_lineEdit")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.board_lineEdit)
        self.verticalLayout_4.addWidget(self.other_groupBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.jobProperties_scrollArea.setWidget(self.jobProperties_scrollAreaWidgetContents)
        self.horizontalLayout_8.addWidget(self.jobProperties_scrollArea)
        self.tabWidget.addTab(self.jobs_tab, "")
        self.shots_tab = QtGui.QWidget()
        self.shots_tab.setObjectName("shots_tab")
        self.horizontalLayout = QtGui.QHBoxLayout(self.shots_tab)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.shotList_frame = QtGui.QFrame(self.shots_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shotList_frame.sizePolicy().hasHeightForWidth())
        self.shotList_frame.setSizePolicy(sizePolicy)
        self.shotList_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.shotList_frame.setObjectName("shotList_frame")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.shotList_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.jobSelect_comboBox = QtGui.QComboBox(self.shotList_frame)
        self.jobSelect_comboBox.setObjectName("jobSelect_comboBox")
        self.verticalLayout_6.addWidget(self.jobSelect_comboBox)
        self.shots_listWidget = QtGui.QListWidget(self.shotList_frame)
        self.shots_listWidget.setAlternatingRowColors(True)
        self.shots_listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.shots_listWidget.setObjectName("shots_listWidget")
        self.verticalLayout_6.addWidget(self.shots_listWidget)
        self.shotButtons_horizontalLayout = QtGui.QHBoxLayout()
        self.shotButtons_horizontalLayout.setObjectName("shotButtons_horizontalLayout")
        self.shotAdd_toolButton = QtGui.QToolButton(self.shotList_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shotAdd_toolButton.sizePolicy().hasHeightForWidth())
        self.shotAdd_toolButton.setSizePolicy(sizePolicy)
        self.shotAdd_toolButton.setIcon(icon)
        self.shotAdd_toolButton.setIconSize(QtCore.QSize(32, 32))
        self.shotAdd_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.shotAdd_toolButton.setObjectName("shotAdd_toolButton")
        self.shotButtons_horizontalLayout.addWidget(self.shotAdd_toolButton)
        self.shotDelete_toolButton = QtGui.QToolButton(self.shotList_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shotDelete_toolButton.sizePolicy().hasHeightForWidth())
        self.shotDelete_toolButton.setSizePolicy(sizePolicy)
        self.shotDelete_toolButton.setIcon(icon1)
        self.shotDelete_toolButton.setIconSize(QtCore.QSize(32, 32))
        self.shotDelete_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.shotDelete_toolButton.setObjectName("shotDelete_toolButton")
        self.shotButtons_horizontalLayout.addWidget(self.shotDelete_toolButton)
        self.verticalLayout_6.addLayout(self.shotButtons_horizontalLayout)
        self.horizontalLayout.addWidget(self.shotList_frame)
        self.shotProperties_scrollArea = QtGui.QScrollArea(self.shots_tab)
        self.shotProperties_scrollArea.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shotProperties_scrollArea.sizePolicy().hasHeightForWidth())
        self.shotProperties_scrollArea.setSizePolicy(sizePolicy)
        self.shotProperties_scrollArea.setStyleSheet("")
        self.shotProperties_scrollArea.setWidgetResizable(True)
        self.shotProperties_scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.shotProperties_scrollArea.setProperty("noBackground", True)
        self.shotProperties_scrollArea.setObjectName("shotProperties_scrollArea")
        self.jobProperties_scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.jobProperties_scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 456, 485))
        self.jobProperties_scrollAreaWidgetContents_2.setObjectName("jobProperties_scrollAreaWidgetContents_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.jobProperties_scrollAreaWidgetContents_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.shotSettings_groupBox_2 = QtGui.QGroupBox(self.jobProperties_scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shotSettings_groupBox_2.sizePolicy().hasHeightForWidth())
        self.shotSettings_groupBox_2.setSizePolicy(sizePolicy)
        self.shotSettings_groupBox_2.setObjectName("shotSettings_groupBox_2")
        self.formLayout_12 = QtGui.QFormLayout(self.shotSettings_groupBox_2)
        self.formLayout_12.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_12.setObjectName("formLayout_12")
        self.shotName_label_2 = QtGui.QLabel(self.shotSettings_groupBox_2)
        self.shotName_label_2.setObjectName("shotName_label_2")
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.LabelRole, self.shotName_label_2)
        self.shotName_lineEdit_2 = QtGui.QLineEdit(self.shotSettings_groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shotName_lineEdit_2.sizePolicy().hasHeightForWidth())
        self.shotName_lineEdit_2.setSizePolicy(sizePolicy)
        self.shotName_lineEdit_2.setObjectName("shotName_lineEdit_2")
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.FieldRole, self.shotName_lineEdit_2)
        self.verticalLayout_7.addWidget(self.shotSettings_groupBox_2)
        self.time_groupBox_2 = QtGui.QGroupBox(self.jobProperties_scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_groupBox_2.sizePolicy().hasHeightForWidth())
        self.time_groupBox_2.setSizePolicy(sizePolicy)
        self.time_groupBox_2.setObjectName("time_groupBox_2")
        self.formLayout_13 = QtGui.QFormLayout(self.time_groupBox_2)
        self.formLayout_13.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_13.setObjectName("formLayout_13")
        self.fps_label_2 = QtGui.QLabel(self.time_groupBox_2)
        self.fps_label_2.setObjectName("fps_label_2")
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.LabelRole, self.fps_label_2)
        self.fps_spinBox_2 = QtGui.QSpinBox(self.time_groupBox_2)
        self.fps_spinBox_2.setMinimum(1)
        self.fps_spinBox_2.setMaximum(5000)
        self.fps_spinBox_2.setProperty("value", 25)
        self.fps_spinBox_2.setObjectName("fps_spinBox_2")
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.FieldRole, self.fps_spinBox_2)
        self.range_label_2 = QtGui.QLabel(self.time_groupBox_2)
        self.range_label_2.setObjectName("range_label_2")
        self.formLayout_13.setWidget(1, QtGui.QFormLayout.LabelRole, self.range_label_2)
        self.range_horizontalLayout_2 = QtGui.QHBoxLayout()
        self.range_horizontalLayout_2.setObjectName("range_horizontalLayout_2")
        self.in_spinBox_2 = QtGui.QSpinBox(self.time_groupBox_2)
        self.in_spinBox_2.setMinimum(1)
        self.in_spinBox_2.setMaximum(9999)
        self.in_spinBox_2.setProperty("value", 1001)
        self.in_spinBox_2.setObjectName("in_spinBox_2")
        self.range_horizontalLayout_2.addWidget(self.in_spinBox_2)
        self.rangeSep_label_2 = QtGui.QLabel(self.time_groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangeSep_label_2.sizePolicy().hasHeightForWidth())
        self.rangeSep_label_2.setSizePolicy(sizePolicy)
        self.rangeSep_label_2.setObjectName("rangeSep_label_2")
        self.range_horizontalLayout_2.addWidget(self.rangeSep_label_2)
        self.out_spinBox_2 = QtGui.QSpinBox(self.time_groupBox_2)
        self.out_spinBox_2.setMinimum(1)
        self.out_spinBox_2.setMaximum(9999)
        self.out_spinBox_2.setProperty("value", 1100)
        self.out_spinBox_2.setObjectName("out_spinBox_2")
        self.range_horizontalLayout_2.addWidget(self.out_spinBox_2)
        self.formLayout_13.setLayout(1, QtGui.QFormLayout.FieldRole, self.range_horizontalLayout_2)
        self.handles_label_2 = QtGui.QLabel(self.time_groupBox_2)
        self.handles_label_2.setObjectName("handles_label_2")
        self.formLayout_13.setWidget(2, QtGui.QFormLayout.LabelRole, self.handles_label_2)
        self.handles_spinBox_2 = QtGui.QSpinBox(self.time_groupBox_2)
        self.handles_spinBox_2.setMaximum(9999)
        self.handles_spinBox_2.setProperty("value", 10)
        self.handles_spinBox_2.setObjectName("handles_spinBox_2")
        self.formLayout_13.setWidget(2, QtGui.QFormLayout.FieldRole, self.handles_spinBox_2)
        self.verticalLayout_7.addWidget(self.time_groupBox_2)
        self.res_groupBox_2 = QtGui.QGroupBox(self.jobProperties_scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.res_groupBox_2.sizePolicy().hasHeightForWidth())
        self.res_groupBox_2.setSizePolicy(sizePolicy)
        self.res_groupBox_2.setObjectName("res_groupBox_2")
        self.formLayout_14 = QtGui.QFormLayout(self.res_groupBox_2)
        self.formLayout_14.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_14.setObjectName("formLayout_14")
        self.resPreset_label_2 = QtGui.QLabel(self.res_groupBox_2)
        self.resPreset_label_2.setObjectName("resPreset_label_2")
        self.formLayout_14.setWidget(1, QtGui.QFormLayout.LabelRole, self.resPreset_label_2)
        self.resPreset_comboBox_2 = QtGui.QComboBox(self.res_groupBox_2)
        self.resPreset_comboBox_2.setObjectName("resPreset_comboBox_2")
        self.resPreset_comboBox_2.addItem("")
        self.resPreset_comboBox_2.addItem("")
        self.resPreset_comboBox_2.addItem("")
        self.resPreset_comboBox_2.addItem("")
        self.formLayout_14.setWidget(1, QtGui.QFormLayout.FieldRole, self.resPreset_comboBox_2)
        self.res_label_2 = QtGui.QLabel(self.res_groupBox_2)
        self.res_label_2.setObjectName("res_label_2")
        self.formLayout_14.setWidget(2, QtGui.QFormLayout.LabelRole, self.res_label_2)
        self.res_horizontalLayout_2 = QtGui.QHBoxLayout()
        self.res_horizontalLayout_2.setObjectName("res_horizontalLayout_2")
        self.resX_spinBox_2 = QtGui.QSpinBox(self.res_groupBox_2)
        self.resX_spinBox_2.setMinimum(1)
        self.resX_spinBox_2.setMaximum(99999)
        self.resX_spinBox_2.setProperty("value", 1920)
        self.resX_spinBox_2.setObjectName("resX_spinBox_2")
        self.res_horizontalLayout_2.addWidget(self.resX_spinBox_2)
        self.resSep_label_2 = QtGui.QLabel(self.res_groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resSep_label_2.sizePolicy().hasHeightForWidth())
        self.resSep_label_2.setSizePolicy(sizePolicy)
        self.resSep_label_2.setObjectName("resSep_label_2")
        self.res_horizontalLayout_2.addWidget(self.resSep_label_2)
        self.resY_spinBox_2 = QtGui.QSpinBox(self.res_groupBox_2)
        self.resY_spinBox_2.setMinimum(1)
        self.resY_spinBox_2.setMaximum(99999)
        self.resY_spinBox_2.setProperty("value", 1080)
        self.resY_spinBox_2.setObjectName("resY_spinBox_2")
        self.res_horizontalLayout_2.addWidget(self.resY_spinBox_2)
        self.formLayout_14.setLayout(2, QtGui.QFormLayout.FieldRole, self.res_horizontalLayout_2)
        self.preserveAR_checkBox_2 = QtGui.QCheckBox(self.res_groupBox_2)
        self.preserveAR_checkBox_2.setChecked(True)
        self.preserveAR_checkBox_2.setObjectName("preserveAR_checkBox_2")
        self.formLayout_14.setWidget(3, QtGui.QFormLayout.FieldRole, self.preserveAR_checkBox_2)
        self.verticalLayout_7.addWidget(self.res_groupBox_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.shotProperties_scrollArea.setWidget(self.jobProperties_scrollAreaWidgetContents_2)
        self.horizontalLayout.addWidget(self.shotProperties_scrollArea)
        self.tabWidget.addTab(self.shots_tab, "")
        self.appPaths_tab = QtGui.QWidget()
        self.appPaths_tab.setObjectName("appPaths_tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.appPaths_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.appVer_groupBox = QtGui.QGroupBox(self.appPaths_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appVer_groupBox.sizePolicy().hasHeightForWidth())
        self.appVer_groupBox.setSizePolicy(sizePolicy)
        self.appVer_groupBox.setObjectName("appVer_groupBox")
        self.formLayout_10 = QtGui.QFormLayout(self.appVer_groupBox)
        self.formLayout_10.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_10.setObjectName("formLayout_10")
        self.appName_label = QtGui.QLabel(self.appVer_groupBox)
        self.appName_label.setObjectName("appName_label")
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.appName_label)
        self.appName_horizontalLayout = QtGui.QHBoxLayout()
        self.appName_horizontalLayout.setObjectName("appName_horizontalLayout")
        self.appName_comboBox = QtGui.QComboBox(self.appVer_groupBox)
        self.appName_comboBox.setEditable(True)
        self.appName_comboBox.setProperty("mandatoryField", False)
        self.appName_comboBox.setObjectName("appName_comboBox")
        self.appName_horizontalLayout.addWidget(self.appName_comboBox)
        self.appNameDel_toolButton = QtGui.QToolButton(self.appVer_groupBox)
        self.appNameDel_toolButton.setIcon(icon1)
        self.appNameDel_toolButton.setIconSize(QtCore.QSize(15, 15))
        self.appNameDel_toolButton.setObjectName("appNameDel_toolButton")
        self.appName_horizontalLayout.addWidget(self.appNameDel_toolButton)
        self.formLayout_10.setLayout(0, QtGui.QFormLayout.FieldRole, self.appName_horizontalLayout)
        self.appVer_label = QtGui.QLabel(self.appVer_groupBox)
        self.appVer_label.setObjectName("appVer_label")
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.LabelRole, self.appVer_label)
        self.appVer_horizontalLayout = QtGui.QHBoxLayout()
        self.appVer_horizontalLayout.setObjectName("appVer_horizontalLayout")
        self.appVer_comboBox = QtGui.QComboBox(self.appVer_groupBox)
        self.appVer_comboBox.setEditable(True)
        self.appVer_comboBox.setProperty("mandatoryField", False)
        self.appVer_comboBox.setObjectName("appVer_comboBox")
        self.appVer_horizontalLayout.addWidget(self.appVer_comboBox)
        self.appVerDel_toolButton = QtGui.QToolButton(self.appVer_groupBox)
        self.appVerDel_toolButton.setIcon(icon1)
        self.appVerDel_toolButton.setIconSize(QtCore.QSize(15, 15))
        self.appVerDel_toolButton.setObjectName("appVerDel_toolButton")
        self.appVer_horizontalLayout.addWidget(self.appVerDel_toolButton)
        self.formLayout_10.setLayout(1, QtGui.QFormLayout.FieldRole, self.appVer_horizontalLayout)
        self.verticalLayout.addWidget(self.appVer_groupBox)
        self.execPaths_groupBox = QtGui.QGroupBox(self.appPaths_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.execPaths_groupBox.sizePolicy().hasHeightForWidth())
        self.execPaths_groupBox.setSizePolicy(sizePolicy)
        self.execPaths_groupBox.setObjectName("execPaths_groupBox")
        self.formLayout_9 = QtGui.QFormLayout(self.execPaths_groupBox)
        self.formLayout_9.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_9.setObjectName("formLayout_9")
        self.osx_label = QtGui.QLabel(self.execPaths_groupBox)
        self.osx_label.setObjectName("osx_label")
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.osx_label)
        self.osxPath_horizontalLayout = QtGui.QHBoxLayout()
        self.osxPath_horizontalLayout.setObjectName("osxPath_horizontalLayout")
        self.osxPath_lineEdit = QtGui.QLineEdit(self.execPaths_groupBox)
        self.osxPath_lineEdit.setObjectName("osxPath_lineEdit")
        self.osxPath_horizontalLayout.addWidget(self.osxPath_lineEdit)
        self.formLayout_9.setLayout(0, QtGui.QFormLayout.FieldRole, self.osxPath_horizontalLayout)
        self.linux_label = QtGui.QLabel(self.execPaths_groupBox)
        self.linux_label.setObjectName("linux_label")
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.LabelRole, self.linux_label)
        self.linuxPath_horizontalLayout = QtGui.QHBoxLayout()
        self.linuxPath_horizontalLayout.setObjectName("linuxPath_horizontalLayout")
        self.linuxPath_lineEdit = QtGui.QLineEdit(self.execPaths_groupBox)
        self.linuxPath_lineEdit.setObjectName("linuxPath_lineEdit")
        self.linuxPath_horizontalLayout.addWidget(self.linuxPath_lineEdit)
        self.formLayout_9.setLayout(1, QtGui.QFormLayout.FieldRole, self.linuxPath_horizontalLayout)
        self.win_label = QtGui.QLabel(self.execPaths_groupBox)
        self.win_label.setObjectName("win_label")
        self.formLayout_9.setWidget(2, QtGui.QFormLayout.LabelRole, self.win_label)
        self.winPath_horizontalLayout = QtGui.QHBoxLayout()
        self.winPath_horizontalLayout.setObjectName("winPath_horizontalLayout")
        self.winPath_lineEdit = QtGui.QLineEdit(self.execPaths_groupBox)
        self.winPath_lineEdit.setObjectName("winPath_lineEdit")
        self.winPath_horizontalLayout.addWidget(self.winPath_lineEdit)
        self.formLayout_9.setLayout(2, QtGui.QFormLayout.FieldRole, self.winPath_horizontalLayout)
        self.appPaths_horizontalLayout = QtGui.QHBoxLayout()
        self.appPaths_horizontalLayout.setObjectName("appPaths_horizontalLayout")
        self.guess_pushButton = QtGui.QPushButton(self.execPaths_groupBox)
        self.guess_pushButton.setObjectName("guess_pushButton")
        self.appPaths_horizontalLayout.addWidget(self.guess_pushButton)
        self.formLayout_9.setLayout(3, QtGui.QFormLayout.FieldRole, self.appPaths_horizontalLayout)
        self.verticalLayout.addWidget(self.execPaths_groupBox)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.appPaths_buttonBox = QtGui.QDialogButtonBox(self.appPaths_tab)
        self.appPaths_buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Reset|QtGui.QDialogButtonBox.Save)
        self.appPaths_buttonBox.setObjectName("appPaths_buttonBox")
        self.verticalLayout.addWidget(self.appPaths_buttonBox)
        self.tabWidget.addTab(self.appPaths_tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.main_buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.main_buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.main_buttonBox.setObjectName("main_buttonBox")
        self.verticalLayout_2.addWidget(self.main_buttonBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Icarus Admin Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.jobs_listWidget.setSortingEnabled(True)
        __sortingEnabled = self.jobs_listWidget.isSortingEnabled()
        self.jobs_listWidget.setSortingEnabled(False)
        self.jobs_listWidget.item(0).setText(QtGui.QApplication.translate("MainWindow", "[defaults]", None, QtGui.QApplication.UnicodeUTF8))
        self.jobs_listWidget.setSortingEnabled(__sortingEnabled)
        self.jobAdd_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Add Job", None, QtGui.QApplication.UnicodeUTF8))
        self.jobDelete_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.jobSettings_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Basic settings", None, QtGui.QApplication.UnicodeUTF8))
        self.jobActive_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Active", None, QtGui.QApplication.UnicodeUTF8))
        self.jobNumber_label.setText(QtGui.QApplication.translate("MainWindow", "Job number:", None, QtGui.QApplication.UnicodeUTF8))
        self.jobPath_label.setText(QtGui.QApplication.translate("MainWindow", "Job path:", None, QtGui.QApplication.UnicodeUTF8))
        self.jobPathBrowse_toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.jobName_label.setText(QtGui.QApplication.translate("MainWindow", "Job name:", None, QtGui.QApplication.UnicodeUTF8))
        self.time_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.fps_label.setText(QtGui.QApplication.translate("MainWindow", "Frames per second:", None, QtGui.QApplication.UnicodeUTF8))
        self.range_label.setText(QtGui.QApplication.translate("MainWindow", "Frame range:", None, QtGui.QApplication.UnicodeUTF8))
        self.rangeSep_label.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.handles_label.setText(QtGui.QApplication.translate("MainWindow", "Handles:", None, QtGui.QApplication.UnicodeUTF8))
        self.res_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.resPreset_label.setText(QtGui.QApplication.translate("MainWindow", "Preset:", None, QtGui.QApplication.UnicodeUTF8))
        self.res_label.setText(QtGui.QApplication.translate("MainWindow", "Full size resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.resSep_label.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Proxy resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.resPreset_comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "HD 1080p", None, QtGui.QApplication.UnicodeUTF8))
        self.resPreset_comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "HD 720p", None, QtGui.QApplication.UnicodeUTF8))
        self.resPreset_comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "PAL 576p 16:9", None, QtGui.QApplication.UnicodeUTF8))
        self.resPreset_comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "PAL 576p 4:3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Proxy mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.resSep_label_3.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Proxy scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.preserveAR_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Preserve aspect ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.appPaths_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Preferred application versions", None, QtGui.QApplication.UnicodeUTF8))
        self.app_label.setText(QtGui.QApplication.translate("MainWindow", "Application:", None, QtGui.QApplication.UnicodeUTF8))
        self.os_label.setText(QtGui.QApplication.translate("MainWindow", "Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.other_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Other settings", None, QtGui.QApplication.UnicodeUTF8))
        self.board_label.setText(QtGui.QApplication.translate("MainWindow", "Production board URL:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.jobs_tab), QtGui.QApplication.translate("MainWindow", "Jobs", None, QtGui.QApplication.UnicodeUTF8))
        self.shotAdd_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Add Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.shotDelete_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.shotSettings_groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Shot settings", None, QtGui.QApplication.UnicodeUTF8))
        self.shotName_label_2.setText(QtGui.QApplication.translate("MainWindow", "Shot name:", None, QtGui.QApplication.UnicodeUTF8))
        self.time_groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Time settings", None, QtGui.QApplication.UnicodeUTF8))
        self.fps_label_2.setText(QtGui.QApplication.translate("MainWindow", "Frames per second:", None, QtGui.QApplication.UnicodeUTF8))
        self.range_label_2.setText(QtGui.QApplication.translate("MainWindow", "Frame range:", None, QtGui.QApplication.UnicodeUTF8))
        self.rangeSep_label_2.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.handles_label_2.setText(QtGui.QApplication.translate("MainWindow", "Handles:", None, QtGui.QApplication.UnicodeUTF8))
        self.res_groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.resPreset_label_2.setText(QtGui.QApplication.translate("MainWindow", "Preset:", None, QtGui.QApplication.UnicodeUTF8))
        self.resPreset_comboBox_2.setItemText(0, QtGui.QApplication.translate("MainWindow", "HD 1080p", None, QtGui.QApplication.UnicodeUTF8))
        self.resPreset_comboBox_2.setItemText(1, QtGui.QApplication.translate("MainWindow", "HD 720p", None, QtGui.QApplication.UnicodeUTF8))
        self.resPreset_comboBox_2.setItemText(2, QtGui.QApplication.translate("MainWindow", "PAL 576p 16:9", None, QtGui.QApplication.UnicodeUTF8))
        self.resPreset_comboBox_2.setItemText(3, QtGui.QApplication.translate("MainWindow", "PAL 576p 4:3", None, QtGui.QApplication.UnicodeUTF8))
        self.res_label_2.setText(QtGui.QApplication.translate("MainWindow", "Resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.resSep_label_2.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.preserveAR_checkBox_2.setText(QtGui.QApplication.translate("MainWindow", "Preserve aspect ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.shots_tab), QtGui.QApplication.translate("MainWindow", "Shots", None, QtGui.QApplication.UnicodeUTF8))
        self.appVer_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Applications and versions", None, QtGui.QApplication.UnicodeUTF8))
        self.appName_label.setText(QtGui.QApplication.translate("MainWindow", "Application:", None, QtGui.QApplication.UnicodeUTF8))
        self.appName_comboBox.setToolTip(QtGui.QApplication.translate("MainWindow", "Select an application, or add a new application by typing a new name and pressing Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.appNameDel_toolButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove this application", None, QtGui.QApplication.UnicodeUTF8))
        self.appNameDel_toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.appVer_label.setText(QtGui.QApplication.translate("MainWindow", "Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.appVer_comboBox.setToolTip(QtGui.QApplication.translate("MainWindow", "Select a version for this application, or add a new version by typing a new name and pressing Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.appVerDel_toolButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove this version of the application", None, QtGui.QApplication.UnicodeUTF8))
        self.appVerDel_toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.execPaths_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Executable paths", None, QtGui.QApplication.UnicodeUTF8))
        self.osx_label.setText(QtGui.QApplication.translate("MainWindow", "Mac OS X:", None, QtGui.QApplication.UnicodeUTF8))
        self.linux_label.setText(QtGui.QApplication.translate("MainWindow", "Linux:", None, QtGui.QApplication.UnicodeUTF8))
        self.win_label.setText(QtGui.QApplication.translate("MainWindow", "Windows:", None, QtGui.QApplication.UnicodeUTF8))
        self.guess_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Try to guess the executable paths based on the template", None, QtGui.QApplication.UnicodeUTF8))
        self.guess_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Guess", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.appPaths_tab), QtGui.QApplication.translate("MainWindow", "App paths", None, QtGui.QApplication.UnicodeUTF8))

import rsc_rc
