# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'icadminUI.ui'
#
# Created: Wed Jan  7 17:39:19 2015
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtGui.QWidget(MainWindow)
        font = QtGui.QFont()
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.jobs_tab = QtGui.QWidget()
        self.jobs_tab.setEnabled(True)
        self.jobs_tab.setObjectName("jobs_tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.jobs_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.jobs_treeWidget = QtGui.QTreeWidget(self.jobs_tab)
        self.jobs_treeWidget.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.jobs_treeWidget.setAlternatingRowColors(True)
        self.jobs_treeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.jobs_treeWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.jobs_treeWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.jobs_treeWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.jobs_treeWidget.setUniformRowHeights(True)
        self.jobs_treeWidget.setItemsExpandable(False)
        self.jobs_treeWidget.setAllColumnsShowFocus(True)
        self.jobs_treeWidget.setExpandsOnDoubleClick(False)
        self.jobs_treeWidget.setObjectName("jobs_treeWidget")
        item_0 = QtGui.QTreeWidgetItem(self.jobs_treeWidget)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtGui.QTreeWidgetItem(self.jobs_treeWidget)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.jobs_treeWidget.header().setDefaultSectionSize(256)
        self.jobs_treeWidget.header().setSortIndicatorShown(True)
        self.jobs_treeWidget.header().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.jobs_treeWidget)
        self.jobActions_groupBox = QtGui.QGroupBox(self.jobs_tab)
        self.jobActions_groupBox.setCheckable(True)
        self.jobActions_groupBox.setObjectName("jobActions_groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.jobActions_groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.jobAdd_toolButton = QtGui.QToolButton(self.jobActions_groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_add_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.jobAdd_toolButton.setIcon(icon)
        self.jobAdd_toolButton.setIconSize(QtCore.QSize(32, 32))
        self.jobAdd_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.jobAdd_toolButton.setObjectName("jobAdd_toolButton")
        self.horizontalLayout.addWidget(self.jobAdd_toolButton)
        self.jobDelete_toolButton = QtGui.QToolButton(self.jobActions_groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_delete_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.jobDelete_toolButton.setIcon(icon1)
        self.jobDelete_toolButton.setIconSize(QtCore.QSize(32, 32))
        self.jobDelete_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.jobDelete_toolButton.setObjectName("jobDelete_toolButton")
        self.horizontalLayout.addWidget(self.jobDelete_toolButton)
        self.jobPath_toolButton = QtGui.QToolButton(self.jobActions_groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_folder_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.jobPath_toolButton.setIcon(icon2)
        self.jobPath_toolButton.setIconSize(QtCore.QSize(32, 32))
        self.jobPath_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.jobPath_toolButton.setObjectName("jobPath_toolButton")
        self.horizontalLayout.addWidget(self.jobPath_toolButton)
        self.toolButton = QtGui.QToolButton(self.jobActions_groupBox)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.jobActivate_toolButton = QtGui.QToolButton(self.jobActions_groupBox)
        self.jobActivate_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.jobActivate_toolButton.setObjectName("jobActivate_toolButton")
        self.horizontalLayout.addWidget(self.jobActivate_toolButton)
        self.jobDeactivate_toolButton = QtGui.QToolButton(self.jobActions_groupBox)
        self.jobDeactivate_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.jobDeactivate_toolButton.setObjectName("jobDeactivate_toolButton")
        self.horizontalLayout.addWidget(self.jobDeactivate_toolButton)
        self.verticalLayout.addWidget(self.jobActions_groupBox)
        self.tabWidget.addTab(self.jobs_tab, "")
        self.shots_tab = QtGui.QWidget()
        self.shots_tab.setObjectName("shots_tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.shots_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget = QtGui.QListWidget(self.shots_tab)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.shots_tab)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtGui.QLineEdit(self.shots_tab)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.tabWidget.addTab(self.shots_tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Discard|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Edit Jobs", None, QtGui.QApplication.UnicodeUTF8))
        self.jobs_treeWidget.setSortingEnabled(True)
        self.jobs_treeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.jobs_treeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.jobs_treeWidget.isSortingEnabled()
        self.jobs_treeWidget.setSortingEnabled(False)
        self.jobs_treeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "Example Job B", None, QtGui.QApplication.UnicodeUTF8))
        self.jobs_treeWidget.topLevelItem(0).setText(1, QtGui.QApplication.translate("MainWindow", "/path/to/job/b", None, QtGui.QApplication.UnicodeUTF8))
        self.jobs_treeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "Example Job A", None, QtGui.QApplication.UnicodeUTF8))
        self.jobs_treeWidget.topLevelItem(1).setText(1, QtGui.QApplication.translate("MainWindow", "/path/to/job/a", None, QtGui.QApplication.UnicodeUTF8))
        self.jobs_treeWidget.setSortingEnabled(__sortingEnabled)
        self.jobActions_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Job Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.jobAdd_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.jobDelete_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.jobPath_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Set Path", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "Rename", None, QtGui.QApplication.UnicodeUTF8))
        self.jobActivate_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Activate", None, QtGui.QApplication.UnicodeUTF8))
        self.jobDeactivate_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Deactivate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.jobs_tab), QtGui.QApplication.translate("MainWindow", "Jobs", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Shot name:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.shots_tab), QtGui.QApplication.translate("MainWindow", "Shots", None, QtGui.QApplication.UnicodeUTF8))

import rsc_rc
