# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'icadminUI.ui'
#
# Created: Thu Dec 18 18:01:50 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtGui.QWidget(MainWindow)
        font = QtGui.QFont()
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.jobs_tab = QtGui.QWidget()
        self.jobs_tab.setEnabled(True)
        self.jobs_tab.setObjectName("jobs_tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.jobs_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.jobs_treeWidget = QtGui.QTreeWidget(self.jobs_tab)
        self.jobs_treeWidget.setObjectName("jobs_treeWidget")
        self.jobs_treeWidget.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.jobs_treeWidget)
        self.jobs_listWidget = QtGui.QListWidget(self.jobs_tab)
        self.jobs_listWidget.setAcceptDrops(True)
        self.jobs_listWidget.setDragEnabled(True)
        self.jobs_listWidget.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.jobs_listWidget.setAlternatingRowColors(True)
        self.jobs_listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.jobs_listWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.jobs_listWidget.setModelColumn(0)
        self.jobs_listWidget.setObjectName("jobs_listWidget")
        self.verticalLayout.addWidget(self.jobs_listWidget)
        self.path_horizontalLayout = QtGui.QHBoxLayout()
        self.path_horizontalLayout.setObjectName("path_horizontalLayout")
        self.path_label = QtGui.QLabel(self.jobs_tab)
        self.path_label.setObjectName("path_label")
        self.path_horizontalLayout.addWidget(self.path_label)
        self.path_lineEdit = QtGui.QLineEdit(self.jobs_tab)
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.path_horizontalLayout.addWidget(self.path_lineEdit)
        self.pathBrowse_pushButton = QtGui.QPushButton(self.jobs_tab)
        self.pathBrowse_pushButton.setObjectName("pathBrowse_pushButton")
        self.path_horizontalLayout.addWidget(self.pathBrowse_pushButton)
        self.verticalLayout.addLayout(self.path_horizontalLayout)
        self.jobActions_horizontalLayout = QtGui.QHBoxLayout()
        self.jobActions_horizontalLayout.setObjectName("jobActions_horizontalLayout")
        self.jobAdd_pushButton = QtGui.QPushButton(self.jobs_tab)
        self.jobAdd_pushButton.setObjectName("jobAdd_pushButton")
        self.jobActions_horizontalLayout.addWidget(self.jobAdd_pushButton)
        self.jobRemove_pushButton = QtGui.QPushButton(self.jobs_tab)
        self.jobRemove_pushButton.setObjectName("jobRemove_pushButton")
        self.jobActions_horizontalLayout.addWidget(self.jobRemove_pushButton)
        self.jobEnable_pushButton = QtGui.QPushButton(self.jobs_tab)
        self.jobEnable_pushButton.setObjectName("jobEnable_pushButton")
        self.jobActions_horizontalLayout.addWidget(self.jobEnable_pushButton)
        self.verticalLayout.addLayout(self.jobActions_horizontalLayout)
        self.tabWidget.addTab(self.jobs_tab, "")
        self.shots_tab = QtGui.QWidget()
        self.shots_tab.setObjectName("shots_tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.shots_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget = QtGui.QListWidget(self.shots_tab)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.shots_tab)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtGui.QLineEdit(self.shots_tab)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.tabWidget.addTab(self.shots_tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Edit Jobs", None, QtGui.QApplication.UnicodeUTF8))
        self.path_label.setText(QtGui.QApplication.translate("MainWindow", "Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.pathBrowse_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.jobAdd_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.jobRemove_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.jobEnable_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.jobs_tab), QtGui.QApplication.translate("MainWindow", "Jobs", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Shot name:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.shots_tab), QtGui.QApplication.translate("MainWindow", "Shots", None, QtGui.QApplication.UnicodeUTF8))

import rsc_rc
