# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'style.ui'
#
# Created: Thu Dec 18 13:10:33 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(677, 841)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(True)
        self.groupBox.setChecked(True)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_1 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_1.setObjectName("pushButton_1")
        self.verticalLayout_6.addWidget(self.pushButton_1)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_6.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setChecked(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_6.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_6.addWidget(self.pushButton_4)
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setChecked(True)
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_6.addWidget(self.pushButton_6)
        self.pushButton = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 48))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_6.addWidget(self.pushButton_5)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_3 = QtGui.QFrame(self.groupBox_4)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.toolButton_2 = QtGui.QToolButton(self.frame_3)
        self.toolButton_2.setMinimumSize(QtCore.QSize(48, 48))
        self.toolButton_2.setMaximumSize(QtCore.QSize(48, 48))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_2.setArrowType(QtCore.Qt.UpArrow)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_6.addWidget(self.toolButton_2)
        self.toolButton_3 = QtGui.QToolButton(self.frame_3)
        self.toolButton_3.setMinimumSize(QtCore.QSize(48, 48))
        self.toolButton_3.setMaximumSize(QtCore.QSize(48, 48))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_3.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_6.addWidget(self.toolButton_3)
        self.line_2 = QtGui.QFrame(self.frame_3)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_6.addWidget(self.line_2)
        self.toolButton_4 = QtGui.QToolButton(self.frame_3)
        self.toolButton_4.setMinimumSize(QtCore.QSize(48, 48))
        self.toolButton_4.setMaximumSize(QtCore.QSize(48, 48))
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_4.setArrowType(QtCore.Qt.LeftArrow)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout_6.addWidget(self.toolButton_4)
        self.toolButton_5 = QtGui.QToolButton(self.frame_3)
        self.toolButton_5.setMinimumSize(QtCore.QSize(48, 48))
        self.toolButton_5.setMaximumSize(QtCore.QSize(48, 48))
        self.toolButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_5.setArrowType(QtCore.Qt.RightArrow)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout_6.addWidget(self.toolButton_5)
        self.verticalLayout_11.addWidget(self.frame_3)
        self.frame_4 = QtGui.QFrame(self.groupBox_4)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtGui.QGridLayout(self.frame_4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton_6 = QtGui.QToolButton(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_6.sizePolicy().hasHeightForWidth())
        self.toolButton_6.setSizePolicy(sizePolicy)
        self.toolButton_6.setCheckable(True)
        self.toolButton_6.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_6.setArrowType(QtCore.Qt.UpArrow)
        self.toolButton_6.setObjectName("toolButton_6")
        self.gridLayout.addWidget(self.toolButton_6, 0, 0, 1, 1)
        self.toolButton_7 = QtGui.QToolButton(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_7.sizePolicy().hasHeightForWidth())
        self.toolButton_7.setSizePolicy(sizePolicy)
        self.toolButton_7.setCheckable(True)
        self.toolButton_7.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_7.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton_7.setObjectName("toolButton_7")
        self.gridLayout.addWidget(self.toolButton_7, 0, 1, 1, 1)
        self.toolButton_8 = QtGui.QToolButton(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_8.sizePolicy().hasHeightForWidth())
        self.toolButton_8.setSizePolicy(sizePolicy)
        self.toolButton_8.setCheckable(True)
        self.toolButton_8.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_8.setArrowType(QtCore.Qt.LeftArrow)
        self.toolButton_8.setObjectName("toolButton_8")
        self.gridLayout.addWidget(self.toolButton_8, 1, 0, 1, 1)
        self.toolButton_9 = QtGui.QToolButton(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_9.sizePolicy().hasHeightForWidth())
        self.toolButton_9.setSizePolicy(sizePolicy)
        self.toolButton_9.setCheckable(True)
        self.toolButton_9.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_9.setArrowType(QtCore.Qt.RightArrow)
        self.toolButton_9.setObjectName("toolButton_9")
        self.gridLayout.addWidget(self.toolButton_9, 1, 1, 1, 1)
        self.verticalLayout_11.addWidget(self.frame_4)
        self.line = QtGui.QFrame(self.groupBox_4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_11.addWidget(self.line)
        self.toolButton_1 = QtGui.QToolButton(self.groupBox_4)
        self.toolButton_1.setCheckable(False)
        self.toolButton_1.setChecked(False)
        self.toolButton_1.setAutoRepeat(False)
        self.toolButton_1.setAutoExclusive(False)
        self.toolButton_1.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.toolButton_1.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton_1.setAutoRaise(False)
        self.toolButton_1.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_1.setObjectName("toolButton_1")
        self.verticalLayout_11.addWidget(self.toolButton_1)
        self.toolButton = QtGui.QToolButton(self.groupBox_4)
        self.toolButton.setCheckable(False)
        self.toolButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout_11.addWidget(self.toolButton)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_radioButtons = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_radioButtons.setToolTip("")
        self.groupBox_radioButtons.setFlat(False)
        self.groupBox_radioButtons.setCheckable(True)
        self.groupBox_radioButtons.setObjectName("groupBox_radioButtons")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_radioButtons)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_1 = QtGui.QRadioButton(self.groupBox_radioButtons)
        self.radioButton_1.setChecked(False)
        self.radioButton_1.setObjectName("radioButton_1")
        self.verticalLayout_3.addWidget(self.radioButton_1)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox_radioButtons)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_3.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox_radioButtons)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_3.addWidget(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox_radioButtons)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_3.addWidget(self.radioButton_4)
        self.radioButton_5 = QtGui.QRadioButton(self.groupBox_radioButtons)
        self.radioButton_5.setEnabled(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_3.addWidget(self.radioButton_5)
        self.radioButton_6 = QtGui.QRadioButton(self.groupBox_radioButtons)
        self.radioButton_6.setEnabled(False)
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_3.addWidget(self.radioButton_6)
        self.horizontalLayout.addWidget(self.groupBox_radioButtons)
        self.groupBox_checkBoxes = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_checkBoxes.setFlat(False)
        self.groupBox_checkBoxes.setCheckable(True)
        self.groupBox_checkBoxes.setObjectName("groupBox_checkBoxes")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_checkBoxes)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox_1 = QtGui.QCheckBox(self.groupBox_checkBoxes)
        self.checkBox_1.setObjectName("checkBox_1")
        self.verticalLayout_5.addWidget(self.checkBox_1)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_checkBoxes)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_5.addWidget(self.checkBox_2)
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_checkBoxes)
        self.checkBox_3.setTristate(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_5.addWidget(self.checkBox_3)
        self.checkBox_4 = QtGui.QCheckBox(self.groupBox_checkBoxes)
        self.checkBox_4.setEnabled(False)
        self.checkBox_4.setStyleSheet("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_5.addWidget(self.checkBox_4)
        self.checkBox_5 = QtGui.QCheckBox(self.groupBox_checkBoxes)
        self.checkBox_5.setEnabled(False)
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_5.addWidget(self.checkBox_5)
        self.checkBox_6 = QtGui.QCheckBox(self.groupBox_checkBoxes)
        self.checkBox_6.setEnabled(False)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_5.addWidget(self.checkBox_6)
        self.horizontalLayout.addWidget(self.groupBox_checkBoxes)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.commandLinkButton = QtGui.QCommandLinkButton(self.tab)
        self.commandLinkButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.verticalLayout_4.addWidget(self.commandLinkButton)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_5.setCheckable(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtGui.QComboBox(self.groupBox_5)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_5)
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.fontComboBox = QtGui.QFontComboBox(self.groupBox_5)
        self.fontComboBox.setObjectName("fontComboBox")
        self.horizontalLayout_2.addWidget(self.fontComboBox)
        self.verticalLayout_8.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_6.setCheckable(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_3.addWidget(self.doubleSpinBox, 1, 1, 1, 1)
        self.dateEdit = QtGui.QDateEdit(self.groupBox_6)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_3.addWidget(self.dateEdit, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_6)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.timeEdit = QtGui.QTimeEdit(self.groupBox_6)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_3.addWidget(self.timeEdit, 0, 3, 1, 1)
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.groupBox_6)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_3.addWidget(self.dateTimeEdit, 2, 3, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.groupBox_6)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_3.addWidget(self.spinBox, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_6)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_6)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_6)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_6)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 2, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_7.setCheckable(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame = QtGui.QFrame(self.groupBox_7)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtGui.QGridLayout(self.frame)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit = QtGui.QLineEdit(self.frame)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.frame)
        self.lineEdit_5.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_5.addWidget(self.lineEdit_5, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.frame)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 4, 0, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.frame)
        self.lineEdit_3.setFrame(True)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setProperty("mandatoryField", False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_5.addWidget(self.lineEdit_3, 3, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.frame)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.frame)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 3, 0, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.frame)
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setProperty("mandatoryField", False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_5.addWidget(self.lineEdit_4, 4, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 2, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.frame)
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setProperty("mandatoryField", True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_5.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.groupBox_7)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.frame_2)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_4.addWidget(self.textEdit, 1, 0, 1, 1)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.frame_2)
        self.plainTextEdit.setReadOnly(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_4.addWidget(self.plainTextEdit, 1, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_2)
        self.verticalLayout_8.addWidget(self.groupBox_7)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_10 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_10.setCheckable(True)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listWidget_2 = QtGui.QListWidget(self.groupBox_10)
        self.listWidget_2.setAlternatingRowColors(False)
        self.listWidget_2.setObjectName("listWidget_2")
        QtGui.QListWidgetItem(self.listWidget_2)
        QtGui.QListWidgetItem(self.listWidget_2)
        QtGui.QListWidgetItem(self.listWidget_2)
        QtGui.QListWidgetItem(self.listWidget_2)
        QtGui.QListWidgetItem(self.listWidget_2)
        QtGui.QListWidgetItem(self.listWidget_2)
        QtGui.QListWidgetItem(self.listWidget_2)
        QtGui.QListWidgetItem(self.listWidget_2)
        QtGui.QListWidgetItem(self.listWidget_2)
        QtGui.QListWidgetItem(self.listWidget_2)
        QtGui.QListWidgetItem(self.listWidget_2)
        QtGui.QListWidgetItem(self.listWidget_2)
        QtGui.QListWidgetItem(self.listWidget_2)
        QtGui.QListWidgetItem(self.listWidget_2)
        self.horizontalLayout_4.addWidget(self.listWidget_2)
        self.listWidget = QtGui.QListWidget(self.groupBox_10)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setObjectName("listWidget")
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        self.horizontalLayout_4.addWidget(self.listWidget)
        self.verticalLayout_2.addWidget(self.groupBox_10)
        self.groupBox_11 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_11.setCheckable(True)
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.treeWidget_2 = QtGui.QTreeWidget(self.groupBox_11)
        self.treeWidget_2.setAlternatingRowColors(False)
        self.treeWidget_2.setAnimated(True)
        self.treeWidget_2.setHeaderHidden(False)
        self.treeWidget_2.setObjectName("treeWidget_2")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_2)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_2)
        self.horizontalLayout_5.addWidget(self.treeWidget_2)
        self.treeWidget = QtGui.QTreeWidget(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "Name")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        self.horizontalLayout_5.addWidget(self.treeWidget)
        self.verticalLayout_2.addWidget(self.groupBox_11)
        self.groupBox_9 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_9.setCheckable(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tableWidget = QtGui.QTableWidget(self.groupBox_9)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(8)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 5, item)
        self.verticalLayout_9.addWidget(self.tableWidget)
        self.verticalLayout_2.addWidget(self.groupBox_9)
        self.groupBox_12 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_12.setCheckable(True)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.columnView = QtGui.QColumnView(self.groupBox_12)
        self.columnView.setObjectName("columnView")
        self.verticalLayout_10.addWidget(self.columnView)
        self.verticalLayout_2.addWidget(self.groupBox_12)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_14 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_14.setCheckable(True)
        self.groupBox_14.setObjectName("groupBox_14")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.textBrowser = QtGui.QTextBrowser(self.groupBox_14)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_8.addWidget(self.textBrowser)
        self.graphicsView = QtGui.QGraphicsView(self.groupBox_14)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_8.addWidget(self.graphicsView)
        self.verticalLayout_13.addWidget(self.groupBox_14)
        self.groupBox_15 = QtGui.QGroupBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_15.sizePolicy().hasHeightForWidth())
        self.groupBox_15.setSizePolicy(sizePolicy)
        self.groupBox_15.setCheckable(True)
        self.groupBox_15.setObjectName("groupBox_15")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.calendarWidget = QtGui.QCalendarWidget(self.groupBox_15)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout_9.addWidget(self.calendarWidget)
        self.lcdNumber = QtGui.QLCDNumber(self.groupBox_15)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_9.addWidget(self.lcdNumber)
        self.verticalLayout_13.addWidget(self.groupBox_15)
        self.groupBox_16 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_16.setCheckable(True)
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.progressBar_2 = QtGui.QProgressBar(self.groupBox_16)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.verticalLayout_12.addWidget(self.progressBar_2)
        self.progressBar = QtGui.QProgressBar(self.groupBox_16)
        self.progressBar.setProperty("value", 50)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_12.addWidget(self.progressBar)
        self.progressBar_3 = QtGui.QProgressBar(self.groupBox_16)
        self.progressBar_3.setProperty("value", 72)
        self.progressBar_3.setTextVisible(False)
        self.progressBar_3.setInvertedAppearance(False)
        self.progressBar_3.setObjectName("progressBar_3")
        self.verticalLayout_12.addWidget(self.progressBar_3)
        self.verticalLayout_13.addWidget(self.groupBox_16)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_8 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_8.setGeometry(QtCore.QRect(16, 16, 625, 561))
        self.groupBox_8.setCheckable(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalScrollBar_3 = QtGui.QScrollBar(self.groupBox_8)
        self.horizontalScrollBar_3.setGeometry(QtCore.QRect(16, 64, 513, 32))
        self.horizontalScrollBar_3.setMaximum(10)
        self.horizontalScrollBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_3.setObjectName("horizontalScrollBar_3")
        self.horizontalScrollBar_2 = QtGui.QScrollBar(self.groupBox_8)
        self.horizontalScrollBar_2.setGeometry(QtCore.QRect(16, 32, 513, 16))
        self.horizontalScrollBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_2.setObjectName("horizontalScrollBar_2")
        self.verticalScrollBar_3 = QtGui.QScrollBar(self.groupBox_8)
        self.verticalScrollBar_3.setGeometry(QtCore.QRect(544, 32, 32, 513))
        self.verticalScrollBar_3.setMaximum(10)
        self.verticalScrollBar_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_3.setObjectName("verticalScrollBar_3")
        self.verticalScrollBar_2 = QtGui.QScrollBar(self.groupBox_8)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(592, 32, 16, 513))
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.textBrowser_2 = QtGui.QTextBrowser(self.groupBox_8)
        self.textBrowser_2.setGeometry(QtCore.QRect(16, 128, 481, 401))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalScrollBar = QtGui.QScrollBar(self.groupBox_8)
        self.verticalScrollBar.setGeometry(QtCore.QRect(496, 128, 16, 401))
        self.verticalScrollBar.setMaximum(400)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalScrollBar = QtGui.QScrollBar(self.groupBox_8)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(16, 528, 481, 16))
        self.horizontalScrollBar.setMaximum(400)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.groupBox_13 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_13.setCheckable(True)
        self.groupBox_13.setObjectName("groupBox_13")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_13)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_7.addWidget(self.lineEdit_6)
        self.spinBox_2 = QtGui.QSpinBox(self.groupBox_13)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_7.addWidget(self.spinBox_2)
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_13)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_3)
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_13)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_7.addWidget(self.pushButton_7)
        self.verticalLayout.addWidget(self.groupBox_13)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 677, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTest = QtGui.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.actionMenu = QtGui.QAction(MainWindow)
        self.actionMenu.setObjectName("actionMenu")
        self.actionItems = QtGui.QAction(MainWindow)
        self.actionItems.setObjectName("actionItems")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionMore = QtGui.QAction(MainWindow)
        self.actionMore.setObjectName("actionMore")
        self.actionTest_2 = QtGui.QAction(MainWindow)
        self.actionTest_2.setObjectName("actionTest_2")
        self.actionMenu_2 = QtGui.QAction(MainWindow)
        self.actionMenu_2.setObjectName("actionMenu_2")
        self.menuFile.addAction(self.actionTest)
        self.menuFile.addAction(self.actionMenu)
        self.menuFile.addAction(self.actionItems)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionMore)
        self.menuEdit.addAction(self.actionTest_2)
        self.menuEdit.addAction(self.actionMenu_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Push Buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_1.setText(QtGui.QApplication.translate("MainWindow", "Push Button 1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Push Button 2 (with menu)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Push Button 3 (toggle)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "Push Button 4 (flat)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MainWindow", "Push Button 5 (flat, toggle)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Push Button 6 (min width)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "Push Button 7 (custom height)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Tool Buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_3.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_4.setText(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_5.setText(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_6.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_7.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_8.setText(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_9.setText(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_1.setText(QtGui.QApplication.translate("MainWindow", "Menu Button Popup", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "Instant Popup", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Group Box (checkable)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_radioButtons.setTitle(QtGui.QApplication.translate("MainWindow", "Radio Buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_1.setText(QtGui.QApplication.translate("MainWindow", "Radio Button 1", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "Radio Button 2", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("MainWindow", "Radio Button 3", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("MainWindow", "Radio Button 4", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_5.setText(QtGui.QApplication.translate("MainWindow", "Radio Button 5 (disabled)", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_6.setText(QtGui.QApplication.translate("MainWindow", "Radio Button 6 (disabled)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_checkBoxes.setTitle(QtGui.QApplication.translate("MainWindow", "Check Boxes", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_1.setText(QtGui.QApplication.translate("MainWindow", "Check Box 1", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("MainWindow", "Check Box 2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("MainWindow", "Check Box 3 (tri-state)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("MainWindow", "Check Box 4 (disabled)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("MainWindow", "Check Box 5 (disabled)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("MainWindow", "Check Box 6 (tri-state, disabled)", None, QtGui.QApplication.UnicodeUTF8))
        self.commandLinkButton.setText(QtGui.QApplication.translate("MainWindow", "CommandLinkButton", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Combo Boxes", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Combo Box", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "New Item 1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "New Item 2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "New Item 3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "New Item 4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "New Item 5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("MainWindow", "Combo Box (editable)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(1, QtGui.QApplication.translate("MainWindow", "Item 1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(2, QtGui.QApplication.translate("MainWindow", "Item 2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(3, QtGui.QApplication.translate("MainWindow", "Item 3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(4, QtGui.QApplication.translate("MainWindow", "Item 4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(5, QtGui.QApplication.translate("MainWindow", "Item 5", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Spin Boxes, etc.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Spin Box:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Double Spin Box:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Time Edit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Date Edit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Time/Date Edit:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Text Input", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("MainWindow", "Type here...", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_5.setText(QtGui.QApplication.translate("MainWindow", "Type here....", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Line Edit (no frame):", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_3.setText(QtGui.QApplication.translate("MainWindow", "Can\'t type here...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Line Edit (password):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Line Edit (read only):", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_4.setText(QtGui.QApplication.translate("MainWindow", "Can\'t type here...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Line Edit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Line Edit (mandatory):", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setText(QtGui.QApplication.translate("MainWindow", "Type here...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Plain Text Edit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Rich Text Edit:", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans\'; font-size:20pt; font-weight:600; color:#2f9ca5;\">Lorem ipsum dolor sit amet</span><span style=\" font-family:\'Arial,Helvetica,sans\'; font-size:20pt; color:#2f9ca5;\">,</span><span style=\" font-family:\'Arial,Helvetica,sans\'; font-size:24pt; color:#2f9ca5;\"> </span><span style=\" font-family:\'Arial,Helvetica,sans\'; font-size:14pt; color:#2f9ca5;\">consectetur </span><span style=\" font-family:\'Arial,Helvetica,sans\'; font-size:14pt; font-style:italic; color:#2f9ca5;\">adipiscing</span><span style=\" font-family:\'Arial,Helvetica,sans\'; font-size:14pt; color:#2f9ca5;\"> elit. Mauris placerat </span><span style=\" font-family:\'Arial,Helvetica,sans\'; font-size:14pt; text-decoration: underline; color:#2f9ca5;\">pharetra</span><span style=\" font-family:\'Arial,Helvetica,sans\'; font-size:14pt; color:#2f9ca5;\"> turpis, in pharetra purus ultrices quis. Vivamus eget sem vel dolor scelerisque cursus eget eget ipsum. In hac habitasse platea dictumst. Aliquam </span><span style=\" font-family:\'Arial,Helvetica,sans\'; font-size:14pt; font-style:italic; color:#2f9ca5;\">elementum</span><span style=\" font-family:\'Arial,Helvetica,sans\'; font-size:14pt; color:#2f9ca5;\"> odio sed lacus laoreet blandit. Nulla lobortis, neque at vulputate lacinia, enim libero feugiat mauris, at efficitur quam nulla sit amet tortor. Donec egestas magna eget lectus lobortis, at dapibus lorem laoreet. Ut ullamcorper augue sit amet auctor semper. In hac habitasse platea dictumst. Morbi faucibus nibh eu justo laoreet, a tempor enim egestas. Mauris non mi </span><span style=\" font-family:\'Arial,Helvetica,sans\'; font-size:14pt; text-decoration: underline; color:#2f9ca5;\">maximus</span><span style=\" font-family:\'Arial,Helvetica,sans\'; font-size:14pt; color:#2f9ca5;\">, porta neque ut, bibendum risus. Nam eu nibh aliquam, cursus sapien nec, scelerisque nisl. Nam ac egestas turpis, ac gravida elit.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit.setPlainText(QtGui.QApplication.translate("MainWindow", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris placerat pharetra turpis, in pharetra purus ultrices quis. Vivamus eget sem vel dolor scelerisque cursus eget eget ipsum. In hac habitasse platea dictumst. Aliquam elementum odio sed lacus laoreet blandit. Nulla lobortis, neque at vulputate lacinia, enim libero feugiat mauris, at efficitur quam nulla sit amet tortor. Donec egestas magna eget lectus lobortis, at dapibus lorem laoreet. Ut ullamcorper augue sit amet auctor semper. In hac habitasse platea dictumst. Morbi faucibus nibh eu justo laoreet, a tempor enim egestas. Mauris non mi maximus, porta neque ut, bibendum risus. Nam eu nibh aliquam, cursus sapien nec, scelerisque nisl. Nam ac egestas turpis, ac gravida elit.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Input Widgets", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("MainWindow", "List Widgets", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        self.listWidget_2.item(0).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_2.item(1).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_2.item(2).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_2.item(3).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_2.item(4).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_2.item(5).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_2.item(6).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_2.item(7).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_2.item(8).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_2.item(9).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_2.item(10).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_2.item(11).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_2.item(12).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_2.item(13).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.item(0).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(1).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(2).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(3).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(4).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(5).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(6).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(7).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(8).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(9).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(10).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(11).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(12).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(13).setText(QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_11.setTitle(QtGui.QApplication.translate("MainWindow", "Tree Widgets", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.setSortingEnabled(True)
        self.treeWidget_2.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Frames", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "utility", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(0).setText(1, QtGui.QApplication.translate("MainWindow", "1001-1150", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(0).setText(2, QtGui.QApplication.translate("MainWindow", "C:\\Users\\Mike\\Documents\\Scripts\\python\\PySide\\images", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(0).setText(3, QtGui.QApplication.translate("MainWindow", "layer", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "main", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(1).setText(1, QtGui.QApplication.translate("MainWindow", "1001-1150", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(1).setText(2, QtGui.QApplication.translate("MainWindow", "C:\\Users\\Mike\\Documents\\Scripts\\python\\PySide\\images", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(1).setText(3, QtGui.QApplication.translate("MainWindow", "main", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "sss", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(1).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "specular", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(1).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "self_illumination", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(1).child(3).setText(0, QtGui.QApplication.translate("MainWindow", "refract", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(1).child(4).setText(0, QtGui.QApplication.translate("MainWindow", "reflect", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(1).child(5).setText(0, QtGui.QApplication.translate("MainWindow", "master", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(1).child(6).setText(0, QtGui.QApplication.translate("MainWindow", "lighting", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(1).child(7).setText(0, QtGui.QApplication.translate("MainWindow", "gi", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(1).child(8).setText(0, QtGui.QApplication.translate("MainWindow", "diffuse", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(2).setText(0, QtGui.QApplication.translate("MainWindow", "id", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(2).setText(1, QtGui.QApplication.translate("MainWindow", "1001-1150", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(2).setText(2, QtGui.QApplication.translate("MainWindow", "C:\\Users\\Mike\\Documents\\Scripts\\python\\PySide\\images", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(2).setText(3, QtGui.QApplication.translate("MainWindow", "layer", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(3).setText(0, QtGui.QApplication.translate("MainWindow", "foreground", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(3).setText(1, QtGui.QApplication.translate("MainWindow", "1056-1150", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(3).setText(2, QtGui.QApplication.translate("MainWindow", "C:\\Users\\Mike\\Documents\\Scripts\\python\\PySide\\images", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(3).setText(3, QtGui.QApplication.translate("MainWindow", "layer", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(4).setText(0, QtGui.QApplication.translate("MainWindow", "background", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(4).setText(1, QtGui.QApplication.translate("MainWindow", "1001-1150", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(4).setText(2, QtGui.QApplication.translate("MainWindow", "C:\\Users\\Mike\\Documents\\Scripts\\python\\PySide\\images", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(4).setText(3, QtGui.QApplication.translate("MainWindow", "layer", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(2).setText(0, QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(3).setText(0, QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(4).setText(0, QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(5).setText(0, QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(6).setText(0, QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(7).setText(0, QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(8).setText(0, QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(9).setText(0, QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(10).setText(0, QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(11).setText(0, QtGui.QApplication.translate("MainWindow", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "Table Widget", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "H", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.item(0, 0).setText(QtGui.QApplication.translate("MainWindow", "Item 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(1, 1).setText(QtGui.QApplication.translate("MainWindow", "Item 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(2, 2).setText(QtGui.QApplication.translate("MainWindow", "Item 3", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(3, 3).setText(QtGui.QApplication.translate("MainWindow", "Item 4", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(4, 4).setText(QtGui.QApplication.translate("MainWindow", "Item 5", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(5, 5).setText(QtGui.QApplication.translate("MainWindow", "Item 6", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_12.setTitle(QtGui.QApplication.translate("MainWindow", "Column View", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Item Views", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_14.setTitle(QtGui.QApplication.translate("MainWindow", "Text Browser / Graphics View", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_15.setTitle(QtGui.QApplication.translate("MainWindow", "Calendar", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_16.setTitle(QtGui.QApplication.translate("MainWindow", "Progress Bars", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Display Widgets", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "Scroll Bars", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Scrollbars", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_13.setTitle(QtGui.QApplication.translate("MainWindow", "Mixed controls", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_6.setText(QtGui.QApplication.translate("MainWindow", "Type something here", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(0, QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(1, QtGui.QApplication.translate("MainWindow", "An", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(2, QtGui.QApplication.translate("MainWindow", "Item", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(3, QtGui.QApplication.translate("MainWindow", "From", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(4, QtGui.QApplication.translate("MainWindow", "This", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(5, QtGui.QApplication.translate("MainWindow", "ComboBox", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(6, QtGui.QApplication.translate("MainWindow", "Widget", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("MainWindow", "Button", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest.setText(QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMenu.setText(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.actionItems.setText(QtGui.QApplication.translate("MainWindow", "Items", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMore.setText(QtGui.QApplication.translate("MainWindow", "More", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest_2.setText(QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMenu_2.setText(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))

import rsc_rc
