# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tmp_app_launcher.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_appLaunch_scrollArea(object):
    def setupUi(self, appLaunch_scrollArea):
        appLaunch_scrollArea.setObjectName("appLaunch_scrollArea")
        appLaunch_scrollArea.resize(588, 365)
        appLaunch_scrollArea.setWidgetResizable(True)
        self.appLaunch_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.appLaunch_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 586, 363))
        self.appLaunch_scrollAreaWidgetContents.setObjectName("appLaunch_scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.appLaunch_scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.apps_gridLayout = QtWidgets.QGridLayout()
        self.apps_gridLayout.setObjectName("apps_gridLayout")
        self.c4d_toolButton = QtWidgets.QToolButton(self.appLaunch_scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c4d_toolButton.sizePolicy().hasHeightForWidth())
        self.c4d_toolButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rsc/rsc/app_icons_c4d.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/rsc/rsc/app_icons_c4d_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.c4d_toolButton.setIcon(icon)
        self.c4d_toolButton.setIconSize(QtCore.QSize(48, 48))
        self.c4d_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.c4d_toolButton.setObjectName("c4d_toolButton")
        self.apps_gridLayout.addWidget(self.c4d_toolButton, 0, 3, 1, 1)
        self.mudbox_toolButton = QtWidgets.QToolButton(self.appLaunch_scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mudbox_toolButton.sizePolicy().hasHeightForWidth())
        self.mudbox_toolButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/rsc/rsc/app_icon_mudbox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/rsc/rsc/app_icon_mudbox_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.mudbox_toolButton.setIcon(icon1)
        self.mudbox_toolButton.setIconSize(QtCore.QSize(48, 48))
        self.mudbox_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mudbox_toolButton.setObjectName("mudbox_toolButton")
        self.apps_gridLayout.addWidget(self.mudbox_toolButton, 0, 2, 1, 1)
        self.aftereffects_toolButton = QtWidgets.QToolButton(self.appLaunch_scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aftereffects_toolButton.sizePolicy().hasHeightForWidth())
        self.aftereffects_toolButton.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/rsc/rsc/app_icon_ae.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/rsc/rsc/app_icon_ae_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.aftereffects_toolButton.setIcon(icon2)
        self.aftereffects_toolButton.setIconSize(QtCore.QSize(48, 48))
        self.aftereffects_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.aftereffects_toolButton.setObjectName("aftereffects_toolButton")
        self.apps_gridLayout.addWidget(self.aftereffects_toolButton, 1, 2, 1, 1)
        self.nuke_toolButton = QtWidgets.QToolButton(self.appLaunch_scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nuke_toolButton.sizePolicy().hasHeightForWidth())
        self.nuke_toolButton.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/rsc/rsc/app_icon_nuke.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/rsc/rsc/app_icon_nuke_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.nuke_toolButton.setIcon(icon3)
        self.nuke_toolButton.setIconSize(QtCore.QSize(48, 48))
        self.nuke_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.nuke_toolButton.setObjectName("nuke_toolButton")
        self.apps_gridLayout.addWidget(self.nuke_toolButton, 1, 1, 1, 1)
        self.maya_toolButton = QtWidgets.QToolButton(self.appLaunch_scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maya_toolButton.sizePolicy().hasHeightForWidth())
        self.maya_toolButton.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/rsc/rsc/app_icon_maya.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/rsc/rsc/app_icon_maya_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.maya_toolButton.setIcon(icon4)
        self.maya_toolButton.setIconSize(QtCore.QSize(48, 48))
        self.maya_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.maya_toolButton.setObjectName("maya_toolButton")
        self.apps_gridLayout.addWidget(self.maya_toolButton, 0, 1, 1, 1)
        self.mari_toolButton = QtWidgets.QToolButton(self.appLaunch_scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mari_toolButton.sizePolicy().hasHeightForWidth())
        self.mari_toolButton.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/rsc/rsc/app_icon_mari.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/rsc/rsc/app_icon_mari_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.mari_toolButton.setIcon(icon5)
        self.mari_toolButton.setIconSize(QtCore.QSize(48, 48))
        self.mari_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mari_toolButton.setObjectName("mari_toolButton")
        self.apps_gridLayout.addWidget(self.mari_toolButton, 0, 4, 1, 1)
        self.realflow_toolButton = QtWidgets.QToolButton(self.appLaunch_scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.realflow_toolButton.sizePolicy().hasHeightForWidth())
        self.realflow_toolButton.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/rsc/rsc/app_icon_realflow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/rsc/rsc/app_icon_realflow_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.realflow_toolButton.setIcon(icon6)
        self.realflow_toolButton.setIconSize(QtCore.QSize(48, 48))
        self.realflow_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.realflow_toolButton.setObjectName("realflow_toolButton")
        self.apps_gridLayout.addWidget(self.realflow_toolButton, 1, 3, 1, 1)
        self.render_toolButton = QtWidgets.QToolButton(self.appLaunch_scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.render_toolButton.sizePolicy().hasHeightForWidth())
        self.render_toolButton.setSizePolicy(sizePolicy)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_render.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_render_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.render_toolButton.setIcon(icon7)
        self.render_toolButton.setIconSize(QtCore.QSize(48, 48))
        self.render_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.render_toolButton.setObjectName("render_toolButton")
        self.apps_gridLayout.addWidget(self.render_toolButton, 1, 4, 1, 1)
        self.browse_toolButton = QtWidgets.QToolButton(self.appLaunch_scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_toolButton.sizePolicy().hasHeightForWidth())
        self.browse_toolButton.setSizePolicy(sizePolicy)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_folder_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.browse_toolButton.setIcon(icon8)
        self.browse_toolButton.setIconSize(QtCore.QSize(48, 48))
        self.browse_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.browse_toolButton.setObjectName("browse_toolButton")
        self.apps_gridLayout.addWidget(self.browse_toolButton, 2, 4, 1, 1)
        self.openProdBoard_toolButton = QtWidgets.QToolButton(self.appLaunch_scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openProdBoard_toolButton.sizePolicy().hasHeightForWidth())
        self.openProdBoard_toolButton.setSizePolicy(sizePolicy)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_productionBoard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_productionBoard_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.openProdBoard_toolButton.setIcon(icon9)
        self.openProdBoard_toolButton.setIconSize(QtCore.QSize(48, 48))
        self.openProdBoard_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.openProdBoard_toolButton.setObjectName("openProdBoard_toolButton")
        self.apps_gridLayout.addWidget(self.openProdBoard_toolButton, 2, 3, 1, 1)
        self.openTerminal_toolButton = QtWidgets.QToolButton(self.appLaunch_scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openTerminal_toolButton.sizePolicy().hasHeightForWidth())
        self.openTerminal_toolButton.setSizePolicy(sizePolicy)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/rsc/rsc/app_icon_terminal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(":/rsc/rsc/app_icon_terminal_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.openTerminal_toolButton.setIcon(icon10)
        self.openTerminal_toolButton.setIconSize(QtCore.QSize(48, 48))
        self.openTerminal_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.openTerminal_toolButton.setObjectName("openTerminal_toolButton")
        self.apps_gridLayout.addWidget(self.openTerminal_toolButton, 2, 2, 1, 1)
        self.openReview_toolButton = QtWidgets.QToolButton(self.appLaunch_scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openReview_toolButton.sizePolicy().hasHeightForWidth())
        self.openReview_toolButton.setSizePolicy(sizePolicy)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_review.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap(":/rsc/rsc/icon_review_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.openReview_toolButton.setIcon(icon11)
        self.openReview_toolButton.setIconSize(QtCore.QSize(48, 48))
        self.openReview_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.openReview_toolButton.setObjectName("openReview_toolButton")
        self.apps_gridLayout.addWidget(self.openReview_toolButton, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.apps_gridLayout)
        appLaunch_scrollArea.setWidget(self.appLaunch_scrollAreaWidgetContents)

        self.retranslateUi(appLaunch_scrollArea)
        QtCore.QMetaObject.connectSlotsByName(appLaunch_scrollArea)

    def retranslateUi(self, appLaunch_scrollArea):
        _translate = QtCore.QCoreApplication.translate
        appLaunch_scrollArea.setWindowTitle(_translate("appLaunch_scrollArea", "ScrollArea"))
        self.c4d_toolButton.setToolTip(_translate("appLaunch_scrollArea", "Launch Cinema 4D"))
        self.c4d_toolButton.setStatusTip(_translate("appLaunch_scrollArea", "Launch Cinema 4D"))
        self.c4d_toolButton.setText(_translate("appLaunch_scrollArea", "Cinema 4D"))
        self.mudbox_toolButton.setToolTip(_translate("appLaunch_scrollArea", "Launch Mudbox"))
        self.mudbox_toolButton.setStatusTip(_translate("appLaunch_scrollArea", "Launch Mudbox"))
        self.mudbox_toolButton.setText(_translate("appLaunch_scrollArea", "Mudbox"))
        self.aftereffects_toolButton.setToolTip(_translate("appLaunch_scrollArea", "Launch After Effects"))
        self.aftereffects_toolButton.setStatusTip(_translate("appLaunch_scrollArea", "Launch After Effects"))
        self.aftereffects_toolButton.setText(_translate("appLaunch_scrollArea", "After Effects"))
        self.nuke_toolButton.setToolTip(_translate("appLaunch_scrollArea", "Launch Nuke"))
        self.nuke_toolButton.setStatusTip(_translate("appLaunch_scrollArea", "Launch Nuke"))
        self.nuke_toolButton.setText(_translate("appLaunch_scrollArea", "Nuke"))
        self.maya_toolButton.setToolTip(_translate("appLaunch_scrollArea", "Launch Maya"))
        self.maya_toolButton.setStatusTip(_translate("appLaunch_scrollArea", "Launch Maya"))
        self.maya_toolButton.setText(_translate("appLaunch_scrollArea", "Maya"))
        self.mari_toolButton.setToolTip(_translate("appLaunch_scrollArea", "Launch Mari"))
        self.mari_toolButton.setStatusTip(_translate("appLaunch_scrollArea", "Launch Mari"))
        self.mari_toolButton.setText(_translate("appLaunch_scrollArea", "Mari"))
        self.realflow_toolButton.setToolTip(_translate("appLaunch_scrollArea", "Launch RealFlow"))
        self.realflow_toolButton.setStatusTip(_translate("appLaunch_scrollArea", "Launch RealFlow"))
        self.realflow_toolButton.setText(_translate("appLaunch_scrollArea", "RealFlow"))
        self.render_toolButton.setToolTip(_translate("appLaunch_scrollArea", "Submit and monitor local and network renders"))
        self.render_toolButton.setStatusTip(_translate("appLaunch_scrollArea", "Submit and monitor local and network renders"))
        self.render_toolButton.setText(_translate("appLaunch_scrollArea", "Render"))
        self.browse_toolButton.setToolTip(_translate("appLaunch_scrollArea", "Browse project folders"))
        self.browse_toolButton.setStatusTip(_translate("appLaunch_scrollArea", "Browse project folders"))
        self.browse_toolButton.setText(_translate("appLaunch_scrollArea", "Browse"))
        self.openProdBoard_toolButton.setToolTip(_translate("appLaunch_scrollArea", "Open production board in web browser"))
        self.openProdBoard_toolButton.setStatusTip(_translate("appLaunch_scrollArea", "Open production board in web browser"))
        self.openProdBoard_toolButton.setText(_translate("appLaunch_scrollArea", "Board"))
        self.openTerminal_toolButton.setToolTip(_translate("appLaunch_scrollArea", "Enables the command-line prompt"))
        self.openTerminal_toolButton.setStatusTip(_translate("appLaunch_scrollArea", "Enables the command-line prompt"))
        self.openTerminal_toolButton.setText(_translate("appLaunch_scrollArea", "Terminal"))
        self.openReview_toolButton.setToolTip(_translate("appLaunch_scrollArea", "Launch HieroPlayer or djv_view"))
        self.openReview_toolButton.setStatusTip(_translate("appLaunch_scrollArea", "Launch HieroPlayer or djv_view"))
        self.openReview_toolButton.setText(_translate("appLaunch_scrollArea", "Review"))

import rsc_rc
