# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'queue_ui.ui'
#
# Created: Tue May 17 18:36:45 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 360)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.renderPblToolbar_frame = QtGui.QFrame(self.centralwidget)
        self.renderPblToolbar_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.renderPblToolbar_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.renderPblToolbar_frame.setObjectName("renderPblToolbar_frame")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.renderPblToolbar_frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.jobSubmit_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.jobSubmit_toolButton.setObjectName("jobSubmit_toolButton")
        self.horizontalLayout_10.addWidget(self.jobSubmit_toolButton)
        self.jobPauseResume_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.jobPauseResume_toolButton.setEnabled(False)
        self.jobPauseResume_toolButton.setObjectName("jobPauseResume_toolButton")
        self.horizontalLayout_10.addWidget(self.jobPauseResume_toolButton)
        self.jobPriorityInc_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.jobPriorityInc_toolButton.setObjectName("jobPriorityInc_toolButton")
        self.horizontalLayout_10.addWidget(self.jobPriorityInc_toolButton)
        self.jobPriorityDec_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.jobPriorityDec_toolButton.setObjectName("jobPriorityDec_toolButton")
        self.horizontalLayout_10.addWidget(self.jobPriorityDec_toolButton)
        self.jobEdit_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.jobEdit_toolButton.setEnabled(False)
        self.jobEdit_toolButton.setObjectName("jobEdit_toolButton")
        self.horizontalLayout_10.addWidget(self.jobEdit_toolButton)
        self.jobResubmit_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.jobResubmit_toolButton.setEnabled(False)
        self.jobResubmit_toolButton.setObjectName("jobResubmit_toolButton")
        self.horizontalLayout_10.addWidget(self.jobResubmit_toolButton)
        self.jobKill_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.jobKill_toolButton.setEnabled(False)
        self.jobKill_toolButton.setObjectName("jobKill_toolButton")
        self.horizontalLayout_10.addWidget(self.jobKill_toolButton)
        self.jobDelete_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.jobDelete_toolButton.setObjectName("jobDelete_toolButton")
        self.horizontalLayout_10.addWidget(self.jobDelete_toolButton)
        spacerItem = QtGui.QSpacerItem(16, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.taskComplete_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.taskComplete_toolButton.setEnabled(False)
        self.taskComplete_toolButton.setObjectName("taskComplete_toolButton")
        self.horizontalLayout_10.addWidget(self.taskComplete_toolButton)
        self.taskFail_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.taskFail_toolButton.setEnabled(False)
        self.taskFail_toolButton.setObjectName("taskFail_toolButton")
        self.horizontalLayout_10.addWidget(self.taskFail_toolButton)
        self.taskRequeue_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.taskRequeue_toolButton.setEnabled(False)
        self.taskRequeue_toolButton.setObjectName("taskRequeue_toolButton")
        self.horizontalLayout_10.addWidget(self.taskRequeue_toolButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.refresh_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.refresh_toolButton.setObjectName("refresh_toolButton")
        self.horizontalLayout_10.addWidget(self.refresh_toolButton)
        self.verticalLayout.addWidget(self.renderPblToolbar_frame)
        self.renderQueue_treeWidget = QtGui.QTreeWidget(self.centralwidget)
        self.renderQueue_treeWidget.setAlternatingRowColors(True)
        self.renderQueue_treeWidget.setRootIsDecorated(True)
        self.renderQueue_treeWidget.setUniformRowHeights(True)
        self.renderQueue_treeWidget.setAnimated(True)
        self.renderQueue_treeWidget.setHeaderHidden(False)
        self.renderQueue_treeWidget.setExpandsOnDoubleClick(True)
        self.renderQueue_treeWidget.setObjectName("renderQueue_treeWidget")
        self.renderQueue_treeWidget.header().setSortIndicatorShown(True)
        self.verticalLayout.addWidget(self.renderQueue_treeWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Render Queue", None, QtGui.QApplication.UnicodeUTF8))
        self.jobSubmit_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.jobPauseResume_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Pause / Resume", None, QtGui.QApplication.UnicodeUTF8))
        self.jobPriorityInc_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Increase Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.jobPriorityDec_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Decrease Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.jobEdit_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.jobResubmit_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Resubmit", None, QtGui.QApplication.UnicodeUTF8))
        self.jobKill_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Kill", None, QtGui.QApplication.UnicodeUTF8))
        self.jobDelete_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.taskComplete_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Complete", None, QtGui.QApplication.UnicodeUTF8))
        self.taskFail_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Fail", None, QtGui.QApplication.UnicodeUTF8))
        self.taskRequeue_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Requeue", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.setSortingEnabled(True)
        self.renderQueue_treeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Job / Task", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Frames", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(5, QtGui.QApplication.translate("MainWindow", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(6, QtGui.QApplication.translate("MainWindow", "Submitted", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(7, QtGui.QApplication.translate("MainWindow", "Elapsed time", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(8, QtGui.QApplication.translate("MainWindow", "Slave", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(9, QtGui.QApplication.translate("MainWindow", "Command", None, QtGui.QApplication.UnicodeUTF8))

