# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'queue_ui.ui'
#
# Created: Tue Apr 12 22:35:39 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 360)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.renderPblToolbar_frame = QtGui.QFrame(self.centralwidget)
        self.renderPblToolbar_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.renderPblToolbar_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.renderPblToolbar_frame.setObjectName("renderPblToolbar_frame")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.renderPblToolbar_frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.jobSubmit_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.jobSubmit_toolButton.setObjectName("jobSubmit_toolButton")
        self.horizontalLayout_10.addWidget(self.jobSubmit_toolButton)
        self.jobPauseResume_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.jobPauseResume_toolButton.setObjectName("jobPauseResume_toolButton")
        self.horizontalLayout_10.addWidget(self.jobPauseResume_toolButton)
        self.jobKill_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.jobKill_toolButton.setObjectName("jobKill_toolButton")
        self.horizontalLayout_10.addWidget(self.jobKill_toolButton)
        self.jobDelete_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.jobDelete_toolButton.setObjectName("jobDelete_toolButton")
        self.horizontalLayout_10.addWidget(self.jobDelete_toolButton)
        self.jobEdit_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.jobEdit_toolButton.setObjectName("jobEdit_toolButton")
        self.horizontalLayout_10.addWidget(self.jobEdit_toolButton)
        self.jobResubmit_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.jobResubmit_toolButton.setObjectName("jobResubmit_toolButton")
        self.horizontalLayout_10.addWidget(self.jobResubmit_toolButton)
        spacerItem = QtGui.QSpacerItem(16, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.taskComplete_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.taskComplete_toolButton.setObjectName("taskComplete_toolButton")
        self.horizontalLayout_10.addWidget(self.taskComplete_toolButton)
        self.taskFail_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.taskFail_toolButton.setObjectName("taskFail_toolButton")
        self.horizontalLayout_10.addWidget(self.taskFail_toolButton)
        self.taskRequeue_toolButton = QtGui.QToolButton(self.renderPblToolbar_frame)
        self.taskRequeue_toolButton.setObjectName("taskRequeue_toolButton")
        self.horizontalLayout_10.addWidget(self.taskRequeue_toolButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.renderPblToolbar_frame)
        self.renderQueue_treeWidget = QtGui.QTreeWidget(self.centralwidget)
        self.renderQueue_treeWidget.setAlternatingRowColors(True)
        self.renderQueue_treeWidget.setRootIsDecorated(True)
        self.renderQueue_treeWidget.setUniformRowHeights(True)
        self.renderQueue_treeWidget.setAnimated(True)
        self.renderQueue_treeWidget.setHeaderHidden(False)
        self.renderQueue_treeWidget.setExpandsOnDoubleClick(True)
        self.renderQueue_treeWidget.setObjectName("renderQueue_treeWidget")
        item_0 = QtGui.QTreeWidgetItem(self.renderQueue_treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.renderQueue_treeWidget)
        self.verticalLayout.addWidget(self.renderQueue_treeWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Render Queue", None, QtGui.QApplication.UnicodeUTF8))
        self.jobSubmit_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.jobPauseResume_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Pause / Resume", None, QtGui.QApplication.UnicodeUTF8))
        self.jobKill_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Kill", None, QtGui.QApplication.UnicodeUTF8))
        self.jobDelete_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.jobEdit_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.jobResubmit_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Resubmit", None, QtGui.QApplication.UnicodeUTF8))
        self.taskComplete_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Complete", None, QtGui.QApplication.UnicodeUTF8))
        self.taskFail_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Fail", None, QtGui.QApplication.UnicodeUTF8))
        self.taskRequeue_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Requeue", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.setSortingEnabled(False)
        self.renderQueue_treeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Job / Task", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Slave", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "Frames", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(5, QtGui.QApplication.translate("MainWindow", "Command", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.renderQueue_treeWidget.isSortingEnabled()
        self.renderQueue_treeWidget.setSortingEnabled(False)
        self.renderQueue_treeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "SH010_lighting_v007", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).setText(1, QtGui.QApplication.translate("MainWindow", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).setText(2, QtGui.QApplication.translate("MainWindow", "In Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).setText(4, QtGui.QApplication.translate("MainWindow", "1001-1050", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Task 1", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).child(0).setText(2, QtGui.QApplication.translate("MainWindow", "Completed", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).child(0).setText(3, QtGui.QApplication.translate("MainWindow", "3dws01", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).child(0).setText(4, QtGui.QApplication.translate("MainWindow", "1001-1010", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Task 2", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).child(1).setText(2, QtGui.QApplication.translate("MainWindow", "In Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).child(1).setText(3, QtGui.QApplication.translate("MainWindow", "3dws02", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).child(1).setText(4, QtGui.QApplication.translate("MainWindow", "1011-1020", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "Task 3", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).child(2).setText(2, QtGui.QApplication.translate("MainWindow", "In Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).child(2).setText(3, QtGui.QApplication.translate("MainWindow", "3dws01", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).child(2).setText(4, QtGui.QApplication.translate("MainWindow", "1021-1030", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).child(3).setText(0, QtGui.QApplication.translate("MainWindow", "Task 4", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).child(3).setText(2, QtGui.QApplication.translate("MainWindow", "Queued", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).child(3).setText(4, QtGui.QApplication.translate("MainWindow", "1031-1040", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).child(4).setText(0, QtGui.QApplication.translate("MainWindow", "Task 5", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).child(4).setText(2, QtGui.QApplication.translate("MainWindow", "Queued", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(0).child(4).setText(4, QtGui.QApplication.translate("MainWindow", "1041-1050", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "SH020_lighting_v003", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(1).setText(2, QtGui.QApplication.translate("MainWindow", "Queued", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.topLevelItem(1).setText(4, QtGui.QApplication.translate("MainWindow", "1001-1025", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.setSortingEnabled(__sortingEnabled)

