# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'queue_ui.ui'
#
# Created: Wed May 18 16:48:34 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 360)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.renderQueueToolbar_frame = QtGui.QFrame(self.centralwidget)
        self.renderQueueToolbar_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.renderQueueToolbar_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.renderQueueToolbar_frame.setObjectName("renderQueueToolbar_frame")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.renderQueueToolbar_frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.view_groupBox = QtGui.QGroupBox(self.renderQueueToolbar_frame)
        self.view_groupBox.setObjectName("view_groupBox")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.view_groupBox)
        self.horizontalLayout_4.setContentsMargins(6, 4, 6, 4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.refresh_toolButton = QtGui.QToolButton(self.view_groupBox)
        self.refresh_toolButton.setObjectName("refresh_toolButton")
        self.horizontalLayout_4.addWidget(self.refresh_toolButton)
        self.horizontalLayout_10.addWidget(self.view_groupBox)
        self.job_groupBox = QtGui.QGroupBox(self.renderQueueToolbar_frame)
        self.job_groupBox.setObjectName("job_groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.job_groupBox)
        self.horizontalLayout.setContentsMargins(6, 4, 6, 4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.jobSubmit_toolButton = QtGui.QToolButton(self.job_groupBox)
        self.jobSubmit_toolButton.setObjectName("jobSubmit_toolButton")
        self.horizontalLayout.addWidget(self.jobSubmit_toolButton)
        self.jobPauseResume_toolButton = QtGui.QToolButton(self.job_groupBox)
        self.jobPauseResume_toolButton.setEnabled(False)
        self.jobPauseResume_toolButton.setObjectName("jobPauseResume_toolButton")
        self.horizontalLayout.addWidget(self.jobPauseResume_toolButton)
        self.jobKill_toolButton = QtGui.QToolButton(self.job_groupBox)
        self.jobKill_toolButton.setEnabled(False)
        self.jobKill_toolButton.setObjectName("jobKill_toolButton")
        self.horizontalLayout.addWidget(self.jobKill_toolButton)
        self.jobDelete_toolButton = QtGui.QToolButton(self.job_groupBox)
        self.jobDelete_toolButton.setObjectName("jobDelete_toolButton")
        self.horizontalLayout.addWidget(self.jobDelete_toolButton)
        self.jobResubmit_toolButton = QtGui.QToolButton(self.job_groupBox)
        self.jobResubmit_toolButton.setEnabled(False)
        self.jobResubmit_toolButton.setObjectName("jobResubmit_toolButton")
        self.horizontalLayout.addWidget(self.jobResubmit_toolButton)
        spacerItem = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.jobPriority_label = QtGui.QLabel(self.job_groupBox)
        self.jobPriority_label.setObjectName("jobPriority_label")
        self.horizontalLayout.addWidget(self.jobPriority_label)
        self.jobPriority_slider = QtGui.QSlider(self.job_groupBox)
        self.jobPriority_slider.setMinimum(-100)
        self.jobPriority_slider.setMaximum(100)
        self.jobPriority_slider.setPageStep(0)
        self.jobPriority_slider.setProperty("value", 0)
        self.jobPriority_slider.setTracking(False)
        self.jobPriority_slider.setOrientation(QtCore.Qt.Horizontal)
        self.jobPriority_slider.setObjectName("jobPriority_slider")
        self.horizontalLayout.addWidget(self.jobPriority_slider)
        self.horizontalLayout_10.addWidget(self.job_groupBox)
        self.task_groupBox = QtGui.QGroupBox(self.renderQueueToolbar_frame)
        self.task_groupBox.setObjectName("task_groupBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.task_groupBox)
        self.horizontalLayout_2.setContentsMargins(6, 4, 6, 4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.taskComplete_toolButton = QtGui.QToolButton(self.task_groupBox)
        self.taskComplete_toolButton.setEnabled(False)
        self.taskComplete_toolButton.setObjectName("taskComplete_toolButton")
        self.horizontalLayout_2.addWidget(self.taskComplete_toolButton)
        self.taskFail_toolButton = QtGui.QToolButton(self.task_groupBox)
        self.taskFail_toolButton.setEnabled(False)
        self.taskFail_toolButton.setObjectName("taskFail_toolButton")
        self.horizontalLayout_2.addWidget(self.taskFail_toolButton)
        self.taskRequeue_toolButton = QtGui.QToolButton(self.task_groupBox)
        self.taskRequeue_toolButton.setEnabled(False)
        self.taskRequeue_toolButton.setObjectName("taskRequeue_toolButton")
        self.horizontalLayout_2.addWidget(self.taskRequeue_toolButton)
        self.horizontalLayout_10.addWidget(self.task_groupBox)
        self.render_groupBox = QtGui.QGroupBox(self.renderQueueToolbar_frame)
        self.render_groupBox.setObjectName("render_groupBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.render_groupBox)
        self.horizontalLayout_3.setContentsMargins(6, 4, 6, 4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.slave_toolButton = QtGui.QToolButton(self.render_groupBox)
        self.slave_toolButton.setObjectName("slave_toolButton")
        self.horizontalLayout_3.addWidget(self.slave_toolButton)
        self.horizontalLayout_10.addWidget(self.render_groupBox)
        self.verticalLayout.addWidget(self.renderQueueToolbar_frame)
        self.renderQueue_treeWidget = QtGui.QTreeWidget(self.centralwidget)
        self.renderQueue_treeWidget.setAlternatingRowColors(True)
        self.renderQueue_treeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.renderQueue_treeWidget.setRootIsDecorated(True)
        self.renderQueue_treeWidget.setUniformRowHeights(True)
        self.renderQueue_treeWidget.setAnimated(True)
        self.renderQueue_treeWidget.setHeaderHidden(False)
        self.renderQueue_treeWidget.setExpandsOnDoubleClick(True)
        self.renderQueue_treeWidget.setObjectName("renderQueue_treeWidget")
        self.renderQueue_treeWidget.header().setSortIndicatorShown(True)
        self.verticalLayout.addWidget(self.renderQueue_treeWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Render Queue", None, QtGui.QApplication.UnicodeUTF8))
        self.view_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.job_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Job", None, QtGui.QApplication.UnicodeUTF8))
        self.jobSubmit_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.jobPauseResume_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.jobKill_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Kill", None, QtGui.QApplication.UnicodeUTF8))
        self.jobDelete_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.jobResubmit_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Resubmit", None, QtGui.QApplication.UnicodeUTF8))
        self.jobPriority_label.setText(QtGui.QApplication.translate("MainWindow", "Reprioritise:", None, QtGui.QApplication.UnicodeUTF8))
        self.task_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Task", None, QtGui.QApplication.UnicodeUTF8))
        self.taskComplete_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Complete", None, QtGui.QApplication.UnicodeUTF8))
        self.taskFail_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Fail", None, QtGui.QApplication.UnicodeUTF8))
        self.taskRequeue_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Requeue", None, QtGui.QApplication.UnicodeUTF8))
        self.render_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Render", None, QtGui.QApplication.UnicodeUTF8))
        self.slave_toolButton.setText(QtGui.QApplication.translate("MainWindow", "Start Local Slave", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.setSortingEnabled(True)
        self.renderQueue_treeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Job / Task", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Frames", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(5, QtGui.QApplication.translate("MainWindow", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(6, QtGui.QApplication.translate("MainWindow", "Submitted", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(7, QtGui.QApplication.translate("MainWindow", "Elapsed time", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(8, QtGui.QApplication.translate("MainWindow", "Slave", None, QtGui.QApplication.UnicodeUTF8))
        self.renderQueue_treeWidget.headerItem().setText(9, QtGui.QApplication.translate("MainWindow", "Command", None, QtGui.QApplication.UnicodeUTF8))

