#!/usr/bin/python

# [Icarus] Batch Render Queue Manager queue__main__.py
# v0.1
#
# Mike Bonnington <mike.bonnington@gps-ldn.com>
# (c) 2016 Gramercy Park Studios
#
# A UI for managing the render queue.


from PySide import QtCore, QtGui
from queue_ui import * # <- import your app's UI file (as generated by pyside-uic)
import os, re, sys

# Initialise Icarus environment
os.environ['ICWORKINGDIR'] = "N:\Dev\icarus\core\ui" # temp assignment
sys.path.append(os.environ['ICWORKINGDIR'])
import env__init__
env__init__.setEnv()

# Import custom modules
#import osOps, rename, sequence


class gpsRenderQueueApp(QtGui.QMainWindow):

	def __init__(self, parent = None):
		super(gpsRenderQueueApp, self).__init__()
		self.ui = Ui_MainWindow()
		self.ui.setupUi(self)

		# Connect signals & slots

		self.updateTaskListView()


	def updateTaskListView(self):
		""" Populates the render queue tree view widget with entries for render jobs and tasks.
		"""
		pass


if __name__ == "__main__":
	app = QtGui.QApplication(sys.argv)

	import rsc_rc # TODO: Check why this isn't working from within the UI file

	#app.setStyle('fusion') # Set UI style - you can also use a flag e.g. '-style plastique'

	# Apply UI style sheet
	qss=os.path.join(os.environ['ICWORKINGDIR'], "style.qss")
	with open(qss, "r") as fh:
		app.setStyleSheet(fh.read())

	renderQueueApp = gpsRenderQueueApp()
	renderQueueApp.show()
	sys.exit(app.exec_())

else:
	renderQueueApp = gpsRenderQueueApp()
	renderQueueApp.show()

