# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'slave_ui.ui'
#
# Created: Wed May 18 23:14:13 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(768, 349)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.jobInfo_formLayout = QtGui.QFormLayout()
        self.jobInfo_formLayout.setObjectName("jobInfo_formLayout")
        self.slave_label = QtGui.QLabel(self.tab)
        self.slave_label.setObjectName("slave_label")
        self.jobInfo_formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.slave_label)
        self.user_label = QtGui.QLabel(self.tab)
        self.user_label.setObjectName("user_label")
        self.jobInfo_formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.user_label)
        self.job_label = QtGui.QLabel(self.tab)
        self.job_label.setObjectName("job_label")
        self.jobInfo_formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.job_label)
        self.slave_lineEdit = QtGui.QLineEdit(self.tab)
        self.slave_lineEdit.setReadOnly(True)
        self.slave_lineEdit.setObjectName("slave_lineEdit")
        self.jobInfo_formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.slave_lineEdit)
        self.job_lineEdit = QtGui.QLineEdit(self.tab)
        self.job_lineEdit.setReadOnly(True)
        self.job_lineEdit.setObjectName("job_lineEdit")
        self.jobInfo_formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.job_lineEdit)
        self.user_lineEdit = QtGui.QLineEdit(self.tab)
        self.user_lineEdit.setReadOnly(True)
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.jobInfo_formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.user_lineEdit)
        self.horizontalLayout.addLayout(self.jobInfo_formLayout)
        spacerItem = QtGui.QSpacerItem(12, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.timeInfo_formLayout = QtGui.QFormLayout()
        self.timeInfo_formLayout.setObjectName("timeInfo_formLayout")
        self.elapsed_label = QtGui.QLabel(self.tab)
        self.elapsed_label.setObjectName("elapsed_label")
        self.timeInfo_formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.elapsed_label)
        self.submitted_label = QtGui.QLabel(self.tab)
        self.submitted_label.setObjectName("submitted_label")
        self.timeInfo_formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.submitted_label)
        self.submitted_lineEdit = QtGui.QLineEdit(self.tab)
        self.submitted_lineEdit.setReadOnly(True)
        self.submitted_lineEdit.setObjectName("submitted_lineEdit")
        self.timeInfo_formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.submitted_lineEdit)
        self.elapsed_lineEdit = QtGui.QLineEdit(self.tab)
        self.elapsed_lineEdit.setReadOnly(True)
        self.elapsed_lineEdit.setObjectName("elapsed_lineEdit")
        self.timeInfo_formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.elapsed_lineEdit)
        self.started_label = QtGui.QLabel(self.tab)
        self.started_label.setObjectName("started_label")
        self.timeInfo_formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.started_label)
        self.started_lineEdit = QtGui.QLineEdit(self.tab)
        self.started_lineEdit.setReadOnly(True)
        self.started_lineEdit.setObjectName("started_lineEdit")
        self.timeInfo_formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.started_lineEdit)
        self.horizontalLayout.addLayout(self.timeInfo_formLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.mayaInfo_formLayout = QtGui.QFormLayout()
        self.mayaInfo_formLayout.setObjectName("mayaInfo_formLayout")
        self.scene_label = QtGui.QLabel(self.tab)
        self.scene_label.setObjectName("scene_label")
        self.mayaInfo_formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.scene_label)
        self.scene_lineEdit = QtGui.QLineEdit(self.tab)
        self.scene_lineEdit.setReadOnly(True)
        self.scene_lineEdit.setObjectName("scene_lineEdit")
        self.mayaInfo_formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.scene_lineEdit)
        self.project_label = QtGui.QLabel(self.tab)
        self.project_label.setObjectName("project_label")
        self.mayaInfo_formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.project_label)
        self.project_lineEdit = QtGui.QLineEdit(self.tab)
        self.project_lineEdit.setReadOnly(True)
        self.project_lineEdit.setObjectName("project_lineEdit")
        self.mayaInfo_formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.project_lineEdit)
        self.flags_label = QtGui.QLabel(self.tab)
        self.flags_label.setObjectName("flags_label")
        self.mayaInfo_formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.flags_label)
        self.flags_lineEdit = QtGui.QLineEdit(self.tab)
        self.flags_lineEdit.setReadOnly(True)
        self.flags_lineEdit.setObjectName("flags_lineEdit")
        self.mayaInfo_formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.flags_lineEdit)
        self.command_label = QtGui.QLabel(self.tab)
        self.command_label.setObjectName("command_label")
        self.mayaInfo_formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.command_label)
        self.command_lineEdit = QtGui.QLineEdit(self.tab)
        self.command_lineEdit.setReadOnly(True)
        self.command_lineEdit.setObjectName("command_lineEdit")
        self.mayaInfo_formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.command_lineEdit)
        self.verticalLayout_3.addLayout(self.mayaInfo_formLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab, "")
        self.output_tab = QtGui.QWidget()
        self.output_tab.setObjectName("output_tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.output_tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.output_textEdit = QtGui.QTextEdit(self.output_tab)
        self.output_textEdit.setReadOnly(True)
        self.output_textEdit.setObjectName("output_textEdit")
        self.verticalLayout.addWidget(self.output_textEdit)
        self.tabWidget.addTab(self.output_tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.stopAfterTask_checkBox = QtGui.QCheckBox(Dialog)
        self.stopAfterTask_checkBox.setObjectName("stopAfterTask_checkBox")
        self.verticalLayout_2.addWidget(self.stopAfterTask_checkBox)
        self.buttonBox_horizontalLayout = QtGui.QHBoxLayout()
        self.buttonBox_horizontalLayout.setObjectName("buttonBox_horizontalLayout")
        self.close_pushButton = QtGui.QPushButton(Dialog)
        self.close_pushButton.setAutoDefault(False)
        self.close_pushButton.setObjectName("close_pushButton")
        self.buttonBox_horizontalLayout.addWidget(self.close_pushButton)
        self.verticalLayout_2.addLayout(self.buttonBox_horizontalLayout)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Render Slave", None, QtGui.QApplication.UnicodeUTF8))
        self.slave_label.setText(QtGui.QApplication.translate("Dialog", "Slave:", None, QtGui.QApplication.UnicodeUTF8))
        self.user_label.setText(QtGui.QApplication.translate("Dialog", "User:", None, QtGui.QApplication.UnicodeUTF8))
        self.job_label.setText(QtGui.QApplication.translate("Dialog", "Job:", None, QtGui.QApplication.UnicodeUTF8))
        self.elapsed_label.setText(QtGui.QApplication.translate("Dialog", "Elapsed:", None, QtGui.QApplication.UnicodeUTF8))
        self.submitted_label.setText(QtGui.QApplication.translate("Dialog", "Submitted:", None, QtGui.QApplication.UnicodeUTF8))
        self.started_label.setText(QtGui.QApplication.translate("Dialog", "Started:", None, QtGui.QApplication.UnicodeUTF8))
        self.scene_label.setText(QtGui.QApplication.translate("Dialog", "Scene:", None, QtGui.QApplication.UnicodeUTF8))
        self.project_label.setText(QtGui.QApplication.translate("Dialog", "Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.flags_label.setText(QtGui.QApplication.translate("Dialog", "Flags:", None, QtGui.QApplication.UnicodeUTF8))
        self.command_label.setText(QtGui.QApplication.translate("Dialog", "Command:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.output_tab), QtGui.QApplication.translate("Dialog", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.stopAfterTask_checkBox.setToolTip(QtGui.QApplication.translate("Dialog", "Stop this slave when the current task completes.", None, QtGui.QApplication.UnicodeUTF8))
        self.stopAfterTask_checkBox.setText(QtGui.QApplication.translate("Dialog", "Stop after current task", None, QtGui.QApplication.UnicodeUTF8))
        self.close_pushButton.setText(QtGui.QApplication.translate("Dialog", "Stop Slave", None, QtGui.QApplication.UnicodeUTF8))

